# Import

In [1]:
import os

# import unicodedata

import pandas as pd

# Files

In [2]:
directory = '/home/jake/Documents/ALIO/'
data_directory = directory + 'data/'
files = os.listdir(directory)

file_names = [
    '임직원.csv',  # 0

    '평균보수-정직원.csv',  # 1
    '평균보수-신입사원.csv',
    '평균보수-무기계약직.csv',
    
    '채용-신입.csv',  # 4
    '채용-청년인턴_유연근무.csv',
    
    '복리후생-예산-비급여-선택적_경로효친.csv',  # 6
    '복리후생-예산-급여-기념품_기타.csv',
    '복리후생-예산-급여-보육_선택적.csv',
    '복리후생-예산-비급여-문화여가_기타.csv',
    '복리후생-예산-비급여-보육_경조비.csv',
    '그밖의복리후생.csv',
    
    '기관장업무추진비.csv',  # 12
    '임원연봉-기관장_상임감사.csv',
    '임원연봉-상임이사.csv',
    '임원연봉-비상임감사.csv',
    '임원연봉-비상임이사.csv',
    
    'welfare.tsv',  # 17
    
    'loss_gain_connected.csv',  # 18
    'loss_gain_integrated.csv',
    'loss_gain_normal.csv',
]

# print(file_names)

# Functions

In [3]:
def get_raw_from_file(file_name):
    directory = '/home/jake/Documents/ALIO/'
    with open(directory + file_name, encoding='euckr') as f:
        head = f.readline()
        head = head.replace(' ', '')
        head = head.replace('2018단위', '2018,단위')
        body = f.read()
    raw = head + body
    return raw

def get_df_from_raw(raw, sep=','):
    from io import StringIO
    sio = StringIO(raw)
    df = pd.read_csv(sio, sep=sep)
    df['항목'] = df['항목'].apply(str.strip)
    return df

def get_df_from_file(file, sep=','):
    raw = get_raw_from_file(file)
    df = get_df_from_raw(raw, sep=sep)
    return df

# 비정규직

## Load Data: df_emp

In [4]:
df_emp = get_df_from_file(file_names[0]); df_emp.head(2)
df_emp['항목'] = df_emp['항목'].str.strip()
df_emp['부설기관여부'] = df_emp['부설기관여부'].str.strip(); df_emp.head(2)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 상임 정원,1.0,1.0,1.0,1.0,1.0,1.0,명,N
1,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 비상임,0.0,0.0,0.0,0.0,0.0,0.0,명,N

## Index, Columns

In [5]:
idx_end_계 = (df_emp['항목'].str[-1]=='계')
idx_tmp = df_emp['항목'].isin(['임직원수 > 비정규직 > 비정규직 계', '임직원수 > 무기계약직 > 현원 > 계', '임직원수 > 소속외인력 > 소속외인력 계'])
idx_all = df_emp['항목'] == '임직원수 > 임직원 총계'
idx_woman = df_emp['항목'] == '임직원수 > 여성 현원'

col_year = ['2013', '2014', '2015', '2016', '2017', '2018']
col_general = ['기관명', '기관유형', '부설기관여부',]
cols = ['기관명', '기관유형', '부설기관여부', '2013', '2014', '2015', '2016', '2017', '2018']

In [6]:
# df_emp.loc[(df_emp['기관명']=='(사)남북교류협력지원협회') & (idx_tmp | idx_all)]
# df_emp.loc[(df_emp['기관명']=='전략물자관리원') & (idx_tmp | idx_all)]
# df_emp.loc[(df_emp['기관명']=='전략물자관리원')]
df_emp.loc[idx_woman]

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
34,(사)남북교류협력지원협회,기타공공기관,임직원수 > 여성 현원,4.00,4.000,9.00,8.00,7.500,11.000,명,N
73,(재)APEC기후센터,기타공공기관,임직원수 > 여성 현원,26.00,26.000,33.00,34.00,34.000,33.000,명,N
112,(재)국제원산지정보원,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,0.00,0.000,16.000,명,N
151,(재)예술경영지원센터,기타공공기관,임직원수 > 여성 현원,17.00,23.000,22.00,38.00,32.000,35.000,명,N
190,(재)우체국금융개발원,준정부기관(위탁집행형),임직원수 > 여성 현원,254.13,254.130,294.38,284.25,335.130,362.630,명,N
229,(재)우체국물류지원단,준정부기관(위탁집행형),임직원수 > 여성 현원,17.00,62.000,73.50,51.38,100.280,99.530,명,N
268,(재)우체국시설관리단,기타공공기관,임직원수 > 여성 현원,1153.00,1294.000,1347.00,1309.00,1292.000,1250.000,명,N
307,(재)일제강제동원피해자지원재단,기타공공기관,임직원수 > 여성 현원,0.00,3.000,5.00,5.00,7.000,14.000,명,N
346,(재)정동극장,기타공공기관,임직원수 > 여성 현원,24.00,27.000,13.00,12.00,23.000,21.000,명,N
385,(재)중소기업연구원,기타공공기관,임직원수 > 여성 현원,13.00,14.000,14.00,16.00,16.000,38.000,명,N
424,(재)한국스마트그리드사업단,기타공공기관,임직원수 > 여성 현원,2.00,2.000,4.00,7.00,7.000,5.000,명,N
463,(재)한국우편사업진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,117.50,126.875,132.50,166.25,231.500,256.250,명,N
502,(재)한국형수치예보모델개발사업단,기타공공기관,임직원수 > 여성 현원,35.00,24.000,25.00,25.00,36.000,35.000,명,N
541,(재)한식진흥원,기타공공기관,임직원수 > 여성 현원,7.00,12.000,12.00,15.00,11.000,21.000,명,N
580,(주)강원랜드,공기업(시장형),임직원수 > 여성 현원,875.00,936.000,936.00,935.00,1003.000,957.000,명,N
619,(주)워터웨이플러스,기타공공기관,임직원수 > 여성 현원,7.00,7.000,9.00,9.00,11.000,42.000,명,N
658,(주)한국가스기술공사,공기업(준시장형),임직원수 > 여성 현원,32.00,45.000,44.50,44.50,59.500,76.000,명,N
697,(주)한국건설관리공사,기타공공기관,임직원수 > 여성 현원,8.00,7.000,7.00,10.00,13.000,15.000,명,N
736,88관광개발(주),기타공공기관,임직원수 > 여성 현원,12.00,11.000,11.00,12.00,12.000,11.000,명,N
775,IOM이민정책연구원,기타공공기관,임직원수 > 여성 현원,8.00,8.000,12.00,12.00,15.000,12.000,명,N
814,KDI국제정책대학원,부설기관(한국개발연구원),임직원수 > 여성 현원,11.00,27.000,31.00,29.00,31.625,31.000,명,Y
853,가축위생방역지원본부,기타공공기관,임직원수 > 여성 현원,71.00,74.000,109.00,114.00,159.670,377.000,명,N
892,강릉원주대학교치과병원,기타공공기관,임직원수 > 여성 현원,62.00,57.000,63.00,66.00,72.000,84.000,명,N
931,강원대학교병원,기타공공기관,임직원수 > 여성 현원,456.00,478.000,494.00,617.00,724.000,764.000,명,N
970,건강보험심사평가원,준정부기관(위탁집행형),임직원수 > 여성 현원,1435.75,1621.250,1848.50,1916.75,2127.500,2312.000,명,N
1009,건설근로자공제회,기타공공기관,임직원수 > 여성 현원,17.00,17.000,21.00,23.00,37.500,42.500,명,N
1048,건축도시공간연구소,부설기관(국토연구원),임직원수 > 여성 현원,10.00,11.000,19.00,23.00,23.000,25.000,명,Y
1087,게임물관리위원회,기타공공기관,임직원수 > 여성 현원,5.00,5.000,9.00,11.00,23.000,21.000,명,N
1126,경북대학교병원,기타공공기관,임직원수 > 여성 현원,1572.00,1614.000,1732.00,1855.00,1934.000,2360.000,명,N
1165,경북대학교치과병원,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,64.00,69.000,77.000,명,N
...,...,...,...,...,...,...,...,...,...,...,...
12904,한국체육산업개발(주),기타공공기관,임직원수 > 여성 현원,81.00,81.000,104.00,132.80,132.000,537.260,명,N
12943,한국출판문화산업진흥원,기타공공기관,임직원수 > 여성 현원,19.00,19.000,20.75,24.75,44.750,43.000,명,N
12982,한국콘텐츠진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,60.00,53.500,61.75,96.25,121.250,127.500,명,N
13021,한국토지주택공사,공기업(준시장형),임직원수 > 여성 현원,1151.40,1061.400,1055.75,1214.25,2263.750,2559.125,명,N
13060,한국투자공사,기타공공기관,임직원수 > 여성 현원,40.00,51.000,57.00,66.00,76.500,79.000,명,N
13099,한국특허전략개발원,준정부기관(위탁집행형),임직원수 > 여성 현원,15.00,17.000,24.00,43.50,52.750,66.500,명,N
13138,한국특허정보원,기타공공기관,임직원수 > 여성 현원,76.00,87.000,109.00,144.75,156.000,159.000,명,N
13177,한국표준과학연구원,기타공공기관,임직원수 > 여성 현원,44.00,47.000,50.50,48.50,50.500,59.500,명,N
13216,한국학중앙연구원,기타공공기관,임직원수 > 여성 현원,63.00,66.000,66.00,67.00,79.000,100.500,명,N
13255,한국한의학연구원,기타공공기관,임직원수 > 여성 현원,48.00,56.000,61.00,61.00,59.000,54.750,명,N
13294,한국항공우주연구원,기타공공기관,임직원수 > 여성 현원,67.00,67.000,70.60,70.80,71.100,89.600,명,N
13333,한국항로표지기술원,기타공공기관,임직원수 > 여성 현원,6.00,6.000,6.00,7.00,6.000,10.000,명,N
13372,한국해양과학기술원,기타공공기관,임직원수 > 여성 현원,51.00,48.000,59.00,60.00,60.000,101.000,명,N
13411,한국해양수산개발원,기타공공기관,임직원수 > 여성 현원,32.00,39.000,48.00,52.00,56.000,85.000,명,N
13450,한국해양수산연수원,준정부기관(위탁집행형),임직원수 > 여성 현원,22.00,22.000,22.00,23.00,31.000,36.000,명,N
13489,한국해양조사협회,기타공공기관,임직원수 > 여성 현원,9.00,8.000,8.00,7.00,8.000,9.000,명,N
13528,한국행정연구원,기타공공기관,임직원수 > 여성 현원,16.00,19.000,19.00,25.00,26.000,47.000,명,N
13567,한국형사정책연구원,기타공공기관,임직원수 > 여성 현원,0.00,24.000,26.63,32.00,29.750,34.000,명,N
13606,한국화학연구원,기타공공기관,임직원수 > 여성 현원,61.00,63.000,64.00,69.00,77.000,78.000,명,N
13645,한국환경공단,준정부기관(위탁집행형),임직원수 > 여성 현원,337.00,413.500,459.38,526.00,525.180,664.000,명,N
13684,한국환경산업기술원,준정부기관(위탁집행형),임직원수 > 여성 현원,78.00,88.500,116.00,124.50,185.300,194.325,명,N
13723,한국환경정책평가연구원,기타공공기관,임직원수 > 여성 현원,42.00,45.000,54.00,65.00,63.000,64.000,명,N
13762,한약진흥재단,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,22.00,23.000,49.000,명,N
13801,한전KDN,공기업(준시장형),임직원수 > 여성 현원,124.50,127.500,157.50,169.50,186.500,210.000,명,N
13840,한전KPS(주),공기업(준시장형),임직원수 > 여성 현원,130.00,157.000,209.00,214.75,231.000,281.500,명,N
13879,한전원자력연료주식회사,기타공공기관,임직원수 > 여성 현원,60.00,69.000,71.00,67.00,68.000,72.625,명,N
13918,항공안전기술원,기타공공기관,임직원수 > 여성 현원,2.00,3.000,7.00,7.00,13.000,25.000,명,N
13957,해양수산과학기술진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,18.00,19.000,21.75,21.75,26.000,28.000,명,N
13996,해양환경공단,공기업(준시장형),임직원수 > 여성 현원,58.63,61.250,65.88,67.75,75.250,94.630,명,N
14035,환경보전협회,기타공공기관,임직원수 > 여성 현원,24.00,27.000,42.00,49.00,46.000,43.000,명,N

## df_emp_all

In [7]:
df_emp_all = df_emp.loc[idx_all, cols].rename(columns={y: y+'_임직원총계' for y in col_year})

df_emp_all.head(1)

,기관명,기관유형,부설기관여부,2013_임직원총계,2014_임직원총계,2015_임직원총계,2016_임직원총계,2017_임직원총계,2018_임직원총계
33,(사)남북교류협력지원협회,기타공공기관,N,26.0,26.0,26.0,26.0,29.0,29.0

## df_emp_tmp

In [8]:
df_emp_tmp = df_emp.loc[idx_tmp, ['기관명', *col_year]].groupby('기관명').agg({y: 'sum' for y in col_year})\
.rename(columns={y: y+'_총비정규직' for y in col_year}); df_emp_tmp
df_emp_tmp.head(1)

,2013_총비정규직,2014_총비정규직,2015_총비정규직,2016_총비정규직,2017_총비정규직,2018_총비정규직
기관명,,,,,,
(사)남북교류협력지원협회,0.0,0.0,0.0,0.0,3.0,4.0

## df_emp2 (all+tmp)

In [9]:
df_emp2 = df_emp_all.merge(df_emp_tmp, left_on='기관명', right_index=True, how='left'); df_emp2.head(1)

,기관명,기관유형,부설기관여부,2013_임직원총계,2014_임직원총계,2015_임직원총계,2016_임직원총계,2017_임직원총계,2018_임직원총계,2013_총비정규직,2014_총비정규직,2015_총비정규직,2016_총비정규직,2017_총비정규직,2018_총비정규직
33,(사)남북교류협력지원협회,기타공공기관,N,26.0,26.0,26.0,26.0,29.0,29.0,0.0,0.0,0.0,0.0,3.0,4.0

## **#비정규직 비율 랭킹**

In [10]:
df_emp2['2018_정규직+비정규직'] = df_emp2['2018_임직원총계']+df_emp2['2018_총비정규직']
df_emp2['2018_총비정규직비율'] = df_emp2['2018_총비정규직'] / df_emp2['2018_정규직+비정규직'] * 100
col_2018 = ['기관명', '기관유형', '부설기관여부', '2018_임직원총계', '2018_정규직+비정규직', '2018_총비정규직', '2018_총비정규직비율']
df_emp2.loc[::, col_2018].sort_values('2018_총비정규직비율', ascending=False)

,기관명,기관유형,부설기관여부,2018_임직원총계,2018_정규직+비정규직,2018_총비정규직,2018_총비정규직비율
11694,한국잡월드,기타공공기관,N,56.0,397.500,341.500,85.911950
5064,인천국제공항공사,공기업(시장형),N,1538.0,9599.000,8061.000,83.977498
6585,코레일테크(주),기타공공기관,N,661.0,3942.425,3281.425,83.233670
11889,한국저작권보호원,기타공공기관,N,108.0,453.000,345.000,76.158940
1827,국립박물관문화재단,기타공공기관,N,80.0,276.000,196.000,71.014493
7599,한국교육개발원,기타공공기관,N,196.0,567.000,371.000,65.432099
7326,한국과학기술원,기타공공기관,N,1340.0,3832.000,2492.000,65.031315
5883,주식회사 공영홈쇼핑,기타공공기관,N,339.0,936.000,597.000,63.782051
6624,태권도진흥재단,기타공공기관,N,81.0,222.000,141.000,63.513514
6156,중소기업유통센터,기타공공기관,N,214.0,578.000,364.000,62.975779
8535,한국도로공사,공기업(준시장형),N,6320.0,16842.125,10522.125,62.475044
11811,한국장학재단,준정부기관(위탁집행형),N,440.0,1160.000,720.000,62.068966
4206,세종학당재단,기타공공기관,N,85.0,218.000,133.000,61.009174
2646,기초과학연구원,기타공공기관,N,415.0,1051.000,636.000,60.513796
7209,한국공항공사,공기업(시장형),N,2534.0,6414.750,3880.750,60.497291
7755,한국교통연구원,기타공공기관,N,135.0,340.000,205.000,60.294118
1437,광주과학기술원,기타공공기관,N,447.0,1090.000,643.000,58.990826
2958,대구경북과학기술원,기타공공기관,N,313.0,740.000,427.000,57.702703
8730,한국마사회,공기업(준시장형),N,3110.4,7103.950,3993.550,56.215908
3348,독립기념관,준정부기관(위탁집행형),N,139.0,316.800,177.800,56.123737
3270,대한체육회,기타공공기관,N,262.0,594.000,332.000,55.892256
5610,전쟁기념사업회,기타공공기관,N,104.0,234.000,130.000,55.555556
12591,한국직업능력개발원,기타공공기관,N,166.0,372.000,206.000,55.376344
4908,울산과학기술원,기타공공기관,N,635.0,1416.500,781.500,55.171197
10992,한국여성인권진흥원,기타공공기관,N,104.0,225.700,121.700,53.921134
1866,국립부산과학관,기타공공기관,N,70.0,151.000,81.000,53.642384
852,가축위생방역지원본부,기타공공기관,N,1061.0,2256.500,1195.500,52.980279
8145,한국나노기술원,기타공공기관,N,75.0,159.500,84.500,52.978056
8925,한국문화예술위원회,준정부기관(기금관리형),N,197.0,414.000,217.000,52.415459
2685,나노종합기술원,부설기관(한국과학기술원),Y,85.0,176.000,91.000,51.704545
...,...,...,...,...,...,...,...
6429,코레일관광개발(주),기타공공기관,N,1065.0,1186.750,121.750,10.259111
2919,농업정책보험금융원,기타공공기관,N,70.0,78.000,8.000,10.256410
2802,농림수산식품교육문화정보원,준정부기관(위탁집행형),N,160.0,178.250,18.250,10.238429
5532,전략물자관리원,기타공공기관,N,53.0,59.000,6.000,10.169492
6819,한국가스안전공사,준정부기관(위탁집행형),N,1414.0,1573.000,159.000,10.108074
7872,한국국제보건의료재단,기타공공기관,N,92.0,102.000,10.000,9.803922
4440,신용보증기금,준정부기관(기금관리형),N,2620.5,2905.000,284.500,9.793460
9042,한국문화진흥주식회사,기타공공기관,N,142.0,157.000,15.000,9.554140
6078,주택도시보증공사,공기업(준시장형),N,779.0,858.000,79.000,9.207459
891,강릉원주대학교치과병원,기타공공기관,N,198.0,218.000,20.000,9.174312
5220,재단법인 의료기관평가인증원,기타공공기관,N,80.0,88.000,8.000,9.090909
10953,한국에너지정보문화재단,기타공공기관,N,41.0,45.000,4.000,8.888889
72,(재)APEC기후센터,기타공공기관,N,90.0,98.000,8.000,8.163265
5454,재외동포재단,기타공공기관,N,71.0,77.000,6.000,7.792208
9783,한국산업기술진흥원,준정부기관(위탁집행형),N,363.0,393.000,30.000,7.633588
5142,재단법인 국악방송,기타공공기관,N,62.0,67.000,5.000,7.462687
13995,해양환경공단,공기업(준시장형),N,666.0,717.730,51.730,7.207446
10563,한국승강기안전공단,준정부기관(위탁집행형),N,1234.0,1329.000,95.000,7.148232
3738,사단법인 한국산학연협회,기타공공기관,N,40.0,43.000,3.000,6.976744
9666,한국사회적기업진흥원,기타공공기관,N,98.0,105.000,7.000,6.666667
5181,재단법인 대한건설기계안전관리원,기타공공기관,N,198.0,212.000,14.000,6.603774
1164,경북대학교치과병원,기타공공기관,N,176.0,186.000,10.000,5.376344
11967,한국전기안전공사,준정부기관(위탁집행형),N,3063.0,3185.790,122.790,3.854303
1359,과학기술일자리진흥원,기타공공기관,N,42.0,43.000,1.000,2.325581
4089,선박안전기술공단,준정부기관(위탁집행형),N,418.0,427.000,9.000,2.107728
5766,정부법무공단,기타공공기관,N,124.0,126.000,2.000,1.587302
12318,한국조폐공사,공기업(준시장형),N,1550.0,1574.000,24.000,1.524778
5922,주식회사 부산항보안공사,기타공공기관,N,485.0,486.000,1.000,0.205761
735,88관광개발(주),기타공공기관,N,43.0,43.000,0.000,0.000000
423,(재)한국스마트그리드사업단,기타공공기관,N,40.0,40.000,0.000,0.000000

## Export: df_emp2

In [11]:
# df_emp2.loc[::, col_2018].sort_values('2018_총비정규직비율', ascending=False).head(15).to_csv(data_directory+'tmp_emp.tsv', sep='\t', index=False)

In [12]:
col_2017 = ['기관명', '기관유형', '부설기관여부', '2017_임직원총계', '2017_정규직+비정규직', '2017_총비정규직', '2017_총비정규직비율']
df_emp2.loc[df_emp['기관명']=='한국전력공사', col_2017]

/home/jake/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

,기관명,기관유형,부설기관여부,2017_임직원총계,2017_정규직+비정규직,2017_총비정규직,2017_총비정규직비율
12084,한국전력공사,공기업(시장형),N,22125.0,NaN,8368.88,NaN

## **#비정규직 6년 추이**

In [13]:
col_임직원총계 = [y + '_임직원총계' for y in col_year]
col_총비정규직 = [y + '_총비정규직' for y in col_year]


tmp = df_emp2[[*col_임직원총계, *col_총비정규직]].sum()
print(tmp)

data = []
for y in col_year:
    datum = {
        '연도': y,
        '총비정규직': tmp[f'{y}_총비정규직'],
        '임직원총계': tmp[f'{y}_임직원총계'],
        '총비정규직비율': tmp[f'{y}_총비정규직'] / (tmp[f'{y}_임직원총계'] + tmp[f'{y}_총비정규직']) * 100
        
    }
    data.append(datum)

df_total_tmp = pd.DataFrame(data)

del tmp
df_total_tmp

2013_임직원총계    287426.00000
2014_임직원총계    305194.00000
2015_임직원총계    315505.50000
2016_임직원총계    329316.00000
2017_임직원총계    347231.42000
2018_임직원총계    378867.52000
2013_총비정규직    127796.85300
2014_총비정규직    138945.26500
2015_총비정규직    145532.20000
2016_총비정규직    146915.80500
2017_총비정규직    153012.73625
2018_총비정규직    159108.99600
dtype: float64

     연도      임직원총계         총비정규직    총비정규직비율
0  2013  287426.00  127796.85300  30.777895
1  2014  305194.00  138945.26500  31.284166
2  2015  315505.50  145532.20000  31.566225
3  2016  329316.00  146915.80500  30.849642
4  2017  347231.42  153012.73625  30.587611
5  2018  378867.52  159108.99600  29.575454

# 무기계약직

## Load Data: df_pay

In [14]:
tmp = get_df_from_file(file_names[1]); tmp.head(20)  # 정규직
tmp2 = get_df_from_file(file_names[3]); tmp2.head(20)  # 무기계약직
df_pay = tmp.append(tmp2)
df_pay['항목'] = df_pay['항목'].str.strip()
df_pay['항목'] = df_pay['항목'].str.replace('직원 평균보수 현황 > 직원평균보수 > ', '')
df_pay['항목'] = df_pay['항목'].str.replace('> ', '')
df_pay['항목'] = df_pay['항목'].str.replace(' ', '_')

df_pay['부설기관여부'] = df_pay['부설기관여부'].str.strip()

del tmp, tmp2

df_pay.head(13)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액,46337.00,47237.00,48380.00,52787.00,52560.00,53752.00,천원,N
1,(사)남북교류협력지원협회,기타공공기관,정규직_기본급,28112.00,28921.00,29472.00,30546.00,34417.00,36261.00,천원,N
2,(사)남북교류협력지원협회,기타공공기관,정규직_고정수당,15525.00,15303.00,15595.00,15433.00,7852.00,14548.00,천원,N
3,(사)남북교류협력지원협회,기타공공기관,정규직_실적수당,2028.00,2214.00,2625.00,3229.00,2751.00,2142.00,천원,N
4,(사)남북교류협력지원협회,기타공공기관,정규직_급여성_복리후생비,672.00,799.00,688.00,838.00,798.00,801.00,천원,N
5,(사)남북교류협력지원협회,기타공공기관,정규직_경영평가_성과급,0.00,0.00,0.00,1386.00,1257.00,0.00,천원,N
6,(사)남북교류협력지원협회,기타공공기관,정규직_기타성과_상여금,0.00,0.00,0.00,1355.00,5485.00,0.00,천원,N
7,(사)남북교류협력지원협회,기타공공기관,정규직_상시종업원수,22.17,22.83,26.75,28.42,26.83,27.00,명,N
8,(사)남북교류협력지원협회,기타공공기관,정규직_평균근속연수,3.37,3.93,4.37,4.77,5.93,6.99,명,N
9,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액_(남성),0.00,0.00,0.00,0.00,59476.00,61398.00,명,N
10,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액_(여성),0.00,0.00,0.00,0.00,35775.00,35592.00,명,N
11,(사)남북교류협력지원협회,기타공공기관,정규직_상시종업원수_(남성),0.00,0.00,0.00,0.00,19.00,19.00,명,N
12,(사)남북교류협력지원협회,기타공공기관,정규직_상시종업원수_(여성),0.00,0.00,0.00,0.00,7.83,8.00,명,N

In [15]:
df_pay.loc[df_pay['기관명']=='한국전력공사']

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
4635,한국전력공사,공기업(시장형),정규직_1인당_평균_보수액,76082.00,75356.00,78935.00,84961.00,82409.00,78667.0,천원,N
4636,한국전력공사,공기업(시장형),정규직_기본급,50234.00,50797.00,52342.00,52812.00,54008.00,58491.0,천원,N
4637,한국전력공사,공기업(시장형),정규직_고정수당,1348.00,2238.00,2524.00,2633.00,2883.00,4181.0,천원,N
4638,한국전력공사,공기업(시장형),정규직_실적수당,5829.00,5976.00,5412.00,5613.00,5190.00,3410.0,천원,N
4639,한국전력공사,공기업(시장형),정규직_급여성_복리후생비,1700.00,1455.00,1449.00,1363.00,1212.00,1929.0,천원,N
4640,한국전력공사,공기업(시장형),정규직_경영평가_성과급,7003.00,5521.00,7483.00,13157.00,8400.00,0.0,천원,N
4641,한국전력공사,공기업(시장형),정규직_기타성과_상여금,9968.00,9369.00,9725.00,9383.00,10716.00,10656.0,천원,N
4642,한국전력공사,공기업(시장형),정규직_상시종업원수,19416.90,19605.20,19895.17,20451.36,21019.23,22329.0,명,N
4643,한국전력공사,공기업(시장형),정규직_평균근속연수,18.78,18.96,18.47,17.76,17.00,0.0,명,N
4644,한국전력공사,공기업(시장형),정규직_1인당_평균_보수액_(남성),0.00,0.00,0.00,0.00,86176.00,0.0,명,N
4645,한국전력공사,공기업(시장형),정규직_1인당_평균_보수액_(여성),0.00,0.00,0.00,0.00,65884.00,0.0,명,N
4646,한국전력공사,공기업(시장형),정규직_상시종업원수_(남성),0.00,0.00,0.00,0.00,17117.23,0.0,명,N
4647,한국전력공사,공기업(시장형),정규직_상시종업원수_(여성),0.00,0.00,0.00,0.00,3902.00,0.0,명,N
4648,한국전력공사,공기업(시장형),정규직_평균근속연수_(남성),0.00,0.00,0.00,0.00,17.81,0.0,명,N
4649,한국전력공사,공기업(시장형),정규직_평균근속연수_(여성),0.00,0.00,0.00,0.00,13.58,0.0,명,N
3945,한국전력공사,공기업(시장형),무기계약직_1인당_평균_보수액,0.00,106549.00,110693.00,125390.00,0.00,0.0,천원,N
3946,한국전력공사,공기업(시장형),무기계약직_기본급,0.00,73513.00,72210.00,80774.00,0.00,0.0,천원,N
3947,한국전력공사,공기업(시장형),무기계약직_고정수당,0.00,6271.00,6610.00,7359.00,0.00,0.0,천원,N
3948,한국전력공사,공기업(시장형),무기계약직_실적수당,0.00,4632.00,3218.00,4371.00,0.00,0.0,천원,N
3949,한국전력공사,공기업(시장형),무기계약직_급여성_복리후생비,0.00,2097.00,1702.00,1976.00,0.00,0.0,천원,N
3950,한국전력공사,공기업(시장형),무기계약직_경영평가_성과급,0.00,8398.00,19368.00,8333.00,0.00,0.0,천원,N
3951,한국전력공사,공기업(시장형),무기계약직_기타성과_상여금,0.00,11638.00,7585.00,22577.00,0.00,0.0,천원,N
3952,한국전력공사,공기업(시장형),무기계약직_상시종업원수,0.00,6.67,10.00,6.42,0.00,0.0,명,N
3953,한국전력공사,공기업(시장형),무기계약직_평균근속연수,0.00,17.40,18.40,20.00,0.00,0.0,명,N
3954,한국전력공사,공기업(시장형),무기계약직_1인당_평균_보수액_(남성),0.00,0.00,0.00,0.00,0.00,0.0,명,N
3955,한국전력공사,공기업(시장형),무기계약직_1인당_평균_보수액_(여성),0.00,0.00,0.00,0.00,0.00,0.0,명,N
3956,한국전력공사,공기업(시장형),무기계약직_상시종업원수_(남성),0.00,0.00,0.00,0.00,0.00,0.0,명,N
3957,한국전력공사,공기업(시장형),무기계약직_상시종업원수_(여성),0.00,0.00,0.00,0.00,0.00,0.0,명,N
3958,한국전력공사,공기업(시장형),무기계약직_평균근속연수_(남성),0.00,0.00,0.00,0.00,0.00,0.0,명,N
3959,한국전력공사,공기업(시장형),무기계약직_평균근속연수_(여성),0.00,0.00,0.00,0.00,0.00,0.0,명,N

## Index, Columns

In [16]:
'''
1인당 평균 보수액
상시종업원수
평균근속연수
'''

idx_pay = df_pay['항목'].str.contains('1인당_평균_보수액')
idx_pay_emp_no = df_pay['항목'].str.contains('상시종업원수')
idx_pay_serve = df_pay['항목'].str.contains('평균근속연수')
df_pay.loc[idx_pay].head(2)

# idx_end_계 = (df_emp['항목'].str[-1]=='계')
# idx_tmp = df_emp['항목'].isin(['임직원수 > 비정규직 > 비정규직 계', '임직원수 > 무기계약직 > 현원 > 계', '임직원수 > 소속외인력 > 소속외인력 계'])
# idx_all = df_emp['항목'] == '임직원수 > 임직원 총계'

# col_year = ['2013', '2014', '2015', '2016', '2017', '2018']
# col_general = ['기관명', '기관유형', '부설기관여부',]
# cols = ['기관명', '기관유형', '부설기관여부', '2013', '2014', '2015', '2016', '2017', '2018']

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액,46337.0,47237.0,48380.0,52787.0,52560.0,53752.0,천원,N
9,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,59476.0,61398.0,명,N

In [17]:
# 직원 평균보수 현황 > 직원평균보수 > 
idx_tmp = df_pay['기관명'] == '전략물자관리원'
df_pay.loc[idx_pay & idx_tmp]

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
2130,전략물자관리원,기타공공기관,정규직_1인당_평균_보수액,54553.0,51348.0,49727.0,50333.0,52061.0,46762.0,천원,N
2139,전략물자관리원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,42272.0,34292.0,명,N
2140,전략물자관리원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,9789.0,12470.0,명,N
1800,전략물자관리원,기타공공기관,무기계약직_1인당_평균_보수액,0.0,0.0,0.0,0.0,0.0,3026.0,천원,N
1809,전략물자관리원,기타공공기관,무기계약직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,0.0,0.0,명,N
1810,전략물자관리원,기타공공기관,무기계약직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,0.0,3026.0,명,N

In [18]:
df_pay_pivot = df_pay.loc[idx_pay].pivot(index='기관명', columns='항목', values=col_year).fillna(0)
df_pay_pivot.head(1)

                          2013                                              \
항목            무기계약직_1인당_평균_보수액 무기계약직_1인당_평균_보수액_(남성) 무기계약직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회              0.0                   0.0                   0.0

                                                                      \
항목            정규직_1인당_평균_보수액 정규직_1인당_평균_보수액_(남성) 정규직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회        46337.0                 0.0                 0.0

                          2014                                              \
항목            무기계약직_1인당_평균_보수액 무기계약직_1인당_평균_보수액_(남성) 무기계약직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회              0.0                   0.0                   0.0

                                     ...                          2017  \
항목            정규직_1인당_평균_보수액         ...         무기계약직_1인당_평균_보수액_(여성)
기관명                                  ...
(사)남북교류협력지원협회        47237.0         ...                           0.0

                                                                      \
항목            정규직_1인당_평균_보수액 정규직_1인당_평균_보수액_(남성) 정규직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회        52560.0             59476.0             35775.0

                          2018                                              \
항목            무기계약직_1인당_평균_보수액 무기계약직_1인당_평균_보수액_(남성) 무기계약직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회          49268.0               54927.0               46439.0


항목            정규직_1인당_평균_보수액 정규직_1인당_평균_보수액_(남성) 정규직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회        53752.0             61398.0             35592.0

[1 rows x 36 columns]

## **#무기계약직 임금 격차**

In [19]:
'''
무기계약직_1인당_평균_보수액_(여성)
무기계약직_1인당_평균_보수액_(남성)
무기계약직_1인당_평균_보수액
정규직_1인당_평균_보수액_(여성)
정규직_1인당_평균_보수액_(남성)
정규직_1인당_평균_보수액
'''
col_pay = [
    '무기계약직_1인당_평균_보수액_(여성)',
    '무기계약직_1인당_평균_보수액_(남성)',
    '무기계약직_1인당_평균_보수액',
    '정규직_1인당_평균_보수액_(여성)',
    '정규직_1인당_평균_보수액_(남성)',
    '정규직_1인당_평균_보수액',
]
df_pay_pivot.loc[::, [('2018', c) for c in col_pay]]
# df_pay_pivot[('2018', col_pay[0])]
df_pay_pivot.loc[(df_pay_pivot.index=='한국여성인권진흥원'), [('2018', '정규직_1인당_평균_보수액')]] = 40242

for y in col_year:
    df_pay_pivot[(y, '정규직_대비_무기계약직_보수_비율')] = df_pay_pivot[(y, col_pay[2])] / df_pay_pivot[(y, col_pay[5])] * 100

col_pay_rate = '정규직_대비_무기계약직_보수_비율'
idx_pay_pivot_not_zero = df_pay_pivot[('2018', '정규직_대비_무기계약직_보수_비율')] != 0

df_pay_pivot_rate_2018 = df_pay_pivot.loc[idx_pay_pivot_not_zero, [('2018', c) for c in [col_pay[2], col_pay[5], col_pay_rate]]]

idx_outlier = (df_pay_pivot_rate_2018.index == '전략물자관리원')
df_pay_pivot_rate_2018.loc[~idx_outlier, ::].sort_values(('2018', col_pay_rate), ascending=True)

                            2018
항목              무기계약직_1인당_평균_보수액 정규직_1인당_평균_보수액 정규직_대비_무기계약직_보수_비율
기관명
한국항로표지기술원                20131.0        67396.0          29.869725
예금보험공사                   27326.0        84947.0          32.168293
한국마사회                    29060.0        86834.0          33.466154
한국자산관리공사                 27382.0        79620.0          34.390857
학교법인한국폴리텍                26109.0        73944.0          35.309153
동북아역사재단                  24392.0        67860.0          35.944592
한국주택금융공사                 31060.0        85653.0          36.262594
한국과학기술원                  36381.0        99971.0          36.391554
한국세라믹기술원                 33569.0        91399.0          36.727973
한국콘텐츠진흥원                 22011.0        59571.0          36.949187
중소기업진흥공단                 29272.0        78400.0          37.336735
기술보증기금                   32499.0        86305.0          37.655987
국민연금공단                   23993.0        63428.0          37.827143
한국남부발전(주)                31628.0        82495.0          38.339293
한국수산자원관리공단               29500.0        76680.0          38.471570
울산과학기술원                  39878.0       103374.0          38.576431
서울올림픽기념국민체육진흥공단          26277.0        67506.0          38.925429
국민건강보험공단                 23237.0        59392.0          39.124798
독립기념관                    25124.0        63439.0          39.603399
한국체육산업개발(주)              23727.0        59743.0          39.715113
한국광물자원공사                 29904.0        75117.0          39.809897
국토연구원                    35248.0        86570.0          40.716183
한국산업안전보건공단               26608.0        65145.0          40.844270
한국무역보험공사                 38432.0        91987.0          41.779817
한국국토정보공사                 33366.0        79563.0          41.936579
국립암센터                    31649.0        74657.0          42.392542
한국개발연구원                  34956.0        81240.0          43.028065
한국석유공사                   38524.0        88363.0          43.597433
한국투자공사                   36325.0        82575.0          43.990312
한국교통연구원                  36000.0        81675.0          44.077135
...                          ...            ...                ...
한국수출입은행                  74989.0        93400.0          80.288009
수도권매립지관리공사               56119.0        69710.0          80.503515
한국건강증진개발원                48265.0        58542.0          82.445082
(재)우체국시설관리단              47674.0        57728.0          82.583841
국가과학기술인력개발원              54762.0        66262.0          82.644653
한국예탁결제원                  92143.0       111367.0          82.738154
(재)우체국물류지원단              43034.0        51906.0          82.907564
한국지역난방공사                 61271.0        73744.0          83.086082
한국보건산업진흥원                56496.0        67303.0          83.942766
창업진흥원                    51930.0        60859.0          85.328382
(주)워터웨이플러스               36947.0        42920.0          86.083411
국립광주과학관                  49274.0        56907.0          86.586887
부산항만공사                   63939.0        73532.0          86.953979
인천항만공사                   64637.0        74279.0          87.019211
한국양성평등교육진흥원              46119.0        52285.0          88.206943
노사발전재단                   41330.0        46519.0          88.845418
소상공인시장진흥공단               43386.0        47860.0          90.651901
코레일관광개발(주)               31480.0        34543.0          91.132791
사립학교교직원연금공단              58970.0        64379.0          91.598192
(사)남북교류협력지원협회            49268.0        53752.0          91.657985
한국인터넷진흥원                 60520.0        65130.0          92.921849
국제방송교류재단                 55537.0        58799.0          94.452287
한국어촌어항공단                 46273.0        48898.0          94.631682
한국여성인권진흥원                40242.0        40242.0         100.000000
서울요양원                    26094.0        26094.0         100.000000
울산항만공사                   64060.0        63148.0         101.444226
여수광양항만공사                 77461.0        75517.0         102.574255
한국사학진흥재단                 54349.0        51845.0         104.829781
한국보건복지인력개발원              54419.0        46711.0         116.501466
한약진흥재단                  270516.0        62816.0         430.648242

[297 rows x 3 columns]

## **#정규직 보수 랭킹**

In [20]:
# df_pay_pivot_rate_2018.sort_values(('2018', col_pay[5]), ascending=False)
col_tmp = ('2018', '정규직_1인당_평균_보수액')

df_tmp = df_pay_pivot.loc[::, [col_tmp]].sort_values(col_tmp, ascending=False)
print(len(df_tmp))
df_tmp

361

                             2018
항목                 정규직_1인당_평균_보수액
기관명
한국예탁결제원                  111367.0
한국전기연구원                  104542.0
울산과학기술원                  103374.0
한국전력국제원자력대학원대학교          103351.0
한국과학기술원                   99971.0
광주과학기술원                   99155.0
한국원자력연구원                  99062.0
한국에너지기술연구원                98125.0
한국항공우주연구원                 96623.0
한국산업은행                    96591.0
선박해양플랜트연구소                96529.0
한국지질자원연구원                 95096.0
국방과학연구소                   94761.0
한국조폐공사                    93667.0
대구경북과학기술원                 93486.0
한국수출입은행                   93400.0
한국철도기술연구원                 93153.0
한국과학기술연구원                 92863.0
중소기업은행                    92707.0
한국무역보험공사                  91987.0
한국전력거래소                   91433.0
한국세라믹기술원                  91399.0
에너지경제연구원                  91279.0
한국건설기술연구원                 90468.0
신용보증기금                    89522.0
한국산업기술시험원                 88798.0
KDI국제정책대학원                88471.0
정보통신정책연구원                 88452.0
한국연구재단                    88436.0
한국석유공사                    88363.0
...                           ...
코레일유통(주)                  47491.0
한국문화정보원                   47491.0
한국지식재산보호원                 47169.0
전략물자관리원                   46762.0
한국보건복지인력개발원               46711.0
한국공예디자인문화진흥원              46535.0
노사발전재단                    46519.0
식품안전정보원                   46370.0
국제식물검역인증원                 45721.0
한국청소년활동진흥원                45512.0
태권도진흥재단                   45355.0
(재)국제원산지정보원               45164.0
한국사회복지협의회                 45160.0
한국문화예술교육진흥원               44741.0
(재)예술경영지원센터               44676.0
국방전직교육원                   44204.0
(주)워터웨이플러스                42920.0
한국기상산업기술원                 42908.0
강릉원주대학교치과병원               42732.0
한국예술인복지재단                 41985.0
(재)일제강제동원피해자지원재단          41458.0
한국여성인권진흥원                 40242.0
주택관리공단(주)                 39148.0
코레일로지스(주)                 38894.0
재단법인 한국여성과학기술인지원센터        38760.0
한국건강가정진흥원                 38647.0
한국보육진흥원                   37095.0
코레일관광개발(주)                34543.0
서울요양원                     26094.0
사단법인 한국기술자격검정원            20292.0

[361 rows x 1 columns]

# 여성

## 여성 임직원 수

### df_emp_pivot_woman

In [21]:
df_emp_pivot_woman = df_emp.loc[idx_all | idx_woman].pivot(index='기관명', columns='항목', values=col_year)
df_emp_pivot_woman.columns.set_levels(['여성 현원', '임직원 총계'], level=1, inplace=True)
df_emp_pivot_woman

                      2013              2014             2015          \
항목                   여성 현원  임직원 총계     여성 현원  임직원 총계    여성 현원  임직원 총계
기관명
(사)남북교류협력지원협회         4.00    26.0     4.000    26.0     9.00    26.0
(재)APEC기후센터          26.00    70.0    26.000    90.0    33.00    90.0
(재)국제원산지정보원           0.00    50.0     0.000    50.0     0.00    50.0
(재)예술경영지원센터          17.00    25.0    23.000    35.0    22.00    35.0
(재)우체국금융개발원         254.13   189.0   254.130   688.0   294.38   710.0
(재)우체국물류지원단          17.00   944.0    62.000  1400.0    73.50  1400.0
(재)우체국시설관리단        1153.00  1989.0  1294.000  2709.0  1347.00  2709.0
(재)일제강제동원피해자지원재단      0.00     0.0     3.000    52.0     5.00    52.0
(재)정동극장              24.00    63.0    27.000    66.0    13.00    40.0
(재)중소기업연구원           13.00    48.0    14.000    50.0    14.00    55.0
(재)한국스마트그리드사업단        2.00    28.0     2.000    28.0     4.00    27.0
(재)한국우편사업진흥원        117.50   116.0   126.875   305.0   132.50   273.0
(재)한국형수치예보모델개발사업단    35.00    58.0    24.000    58.0    25.00    58.0
(재)한식진흥원              7.00     9.0    12.000    21.0    12.00    21.0
(주)강원랜드             875.00  2906.0   936.000  3243.0   936.00  3498.0
(주)워터웨이플러스            7.00    65.0     7.000    65.0     9.00    65.0
(주)한국가스기술공사          32.00  1173.0    45.000  1289.0    44.50  1359.0
(주)한국건설관리공사           8.00   416.0     7.000   416.0     7.00   416.0
88관광개발(주)            12.00    48.0    11.000    48.0    11.00    48.0
IOM이민정책연구원            8.00    17.0     8.000    17.0    12.00    17.0
KDI국제정책대학원           11.00    55.0    27.000    99.0    31.00    99.0
가축위생방역지원본부           71.00   462.0    74.000   504.0   109.00   681.0
강릉원주대학교치과병원          62.00   190.0    57.000   190.0    63.00   190.0
강원대학교병원             456.00   786.0   478.000   967.0   494.00  1004.0
건강보험심사평가원          1435.75  1917.0  1621.250  2117.0  1848.50  2377.0
건설근로자공제회             17.00    92.0    17.000    97.0    21.00    97.0
건축도시공간연구소            10.00    35.0    11.000    49.0    19.00    55.0
게임물관리위원회              5.00    75.0     5.000    78.0     9.00    82.0
경북대학교병원            1572.00  2843.0  1614.000  2929.0  1732.00  3010.0
경북대학교치과병원             0.00     0.0     0.000     0.0     0.00     0.0
...                    ...     ...       ...     ...      ...     ...
한국체육산업개발(주)          81.00   821.0    81.000   826.0   104.00   826.0
한국출판문화산업진흥원          19.00    55.0    19.000    62.0    20.75    65.0
한국콘텐츠진흥원             60.00   198.0    53.500   186.0    61.75   226.0
한국토지주택공사           1151.40  6100.0  1061.400  6418.0  1055.75  6418.0
한국투자공사               40.00   146.0    51.000   177.0    57.00   231.0
한국특허전략개발원            15.00    81.0    17.000    81.0    24.00   161.0
한국특허정보원              76.00   688.0    87.000   340.0   109.00   368.0
한국표준과학연구원            44.00   421.0    47.000   430.0    50.50   436.0
한국학중앙연구원             63.00   220.0    66.000   227.0    66.00   227.0
한국한의학연구원             48.00   152.0    56.000   167.0    61.00   182.0
한국항공우주연구원            67.00   754.0    67.000   790.0    70.60   821.0
한국항로표지기술원             6.00    48.0     6.000    48.0     6.00    48.0
한국해양과학기술원            51.00   505.0    48.000   389.0    59.00   400.0
한국해양수산개발원            32.00   136.0    39.000   148.0    48.00   155.0
한국해양수산연수원            22.00   149.0    22.000   152.0    22.00   152.0
한국해양조사협회              9.00    43.0     8.000    45.0     8.00    45.0
한국행정연구원              16.00    60.0    19.000    66.0    19.00    80.0
한국형사정책연구원             0.00    58.0    24.000    64.0    26.63    70.0
한국화학연구원              61.00   384.0    63.000   397.0    64.00   419.0
한국환경공단              337.00  2127.0   413.500  2159.0   459.38  2219.0
한국환경산업기술원            78.00   188.0    88.500   308.0   116.00   321.0
한국환경정책평가연구원          42.00   147.0    45.000   149.0    54.00   157.0
한약진흥재단                0.00     0.0     0.000     0.0     0.00     0.0
한전KDN               124.50  1846.0   127.500  1846.0   157.50  2267.0
한전KPS(주)            130.00  4877.0   157.000  5167.0   209.00  5464.0
한전원자력연료주식회사          60.00   998.0    69.000  1070.0    71.00  1111.0
항공안전기술원               2.00    50.0     3.000    50.0     7.00    36.0
해양수산과학기술진흥원          18.00    62.0    19.000    74.0    21.75    74.0
해양환경공단               58.63   570.0    61.250   579.0    65.88   579.0
환경보전협회               24.00   251.0    27.000   251.0    42.00   251.0

                      2016              2017              2018
항목                   여성 현원  임직원 총계     여성 현원  임직원 총계     여성 현원  임직원 총계
기관명
(사)남북교류협력지원협회         8.00    26.0     7.500    29.0    11.000    29.0
(재)APEC기후센터          34.00    90.0    34.000    90.0    33.000    90.0
(재)국제원산지정보원           0.00    50.0     0.000    50.0    16.000    50.0
(재)예술경영지원센터          38.00    50.0    32.000    53.0    35.000    69.0
(재)우체국금융개발원         284.25   710.0   335.130   723.0   362.630   748.0
(재)우체국물류지원단          51.38  1413.0   100.280  1535.0    99.530  1601.5
(재)우체국시설관리단        1309.00  2709.0  1292.000  2709.0  1250.000  2709.0
(재)일제강제동원피해자지원재단      5.00    52.0     7.000    37.0    14.000    37.0
(재)정동극장              12.00    41.0    23.000    62.0    21.000    61.0
(재)중소기업연구원           16.00    59.0    16.000    59.0    38.000    95.0
(재)한국스마트그리드사업단        7.00    39.0     7.000    40.0     5.000    40.0
(재)한국우편사업진흥원        166.25   273.0   231.500   279.0   256.250   443.0
(재)한국형수치예보모델개발사업단    25.00    60.0    36.000    60.0    35.000    60.0
(재)한식진흥원             15.00    21.0    11.000    25.0    21.000    42.0
(주)강원랜드             935.00  3604.0  1003.000  3680.0   957.000  3701.0
(주)워터웨이플러스            9.00    65.0    11.000    70.0    42.000    95.0
(주)한국가스기술공사          44.50  1423.0    59.500  1478.0    76.000  1564.0
(주)한국건설관리공사          10.00   416.0    13.000   381.0    15.000   380.0
88관광개발(주)            12.00    48.0    12.000    43.0    11.000    43.0
IOM이민정책연구원           12.00    17.0    15.000    17.0    12.000    21.0
KDI국제정책대학원           29.00   101.0    31.625   101.0    31.000   101.0
가축위생방역지원본부          114.00   738.0   159.670   786.0   377.000  1061.0
강릉원주대학교치과병원          66.00   193.0    72.000   193.0    84.000   198.0
강원대학교병원             617.00  1035.0   724.000  1123.0   764.000  1542.0
건강보험심사평가원          1916.75  2529.0  2127.500  2790.0  2312.000  3222.0
건설근로자공제회             23.00   116.0    37.500   150.5    42.500   156.5
건축도시공간연구소            23.00    62.0    23.000    62.0    25.000    62.0
게임물관리위원회             11.00    82.0    23.000    86.0    21.000    93.0
경북대학교병원            1855.00  3044.0  1934.000  3141.0  2360.000  3862.0
경북대학교치과병원            64.00   152.0    69.000   168.0    77.000   176.0
...                    ...     ...       ...     ...       ...     ...
한국체육산업개발(주)         132.80   477.0   132.000  1167.0   537.260  1455.0
한국출판문화산업진흥원          24.75    68.0    44.750    92.0    43.000    92.0
한국콘텐츠진흥원             96.25   268.0   121.250   317.0   127.500   314.0
한국토지주택공사           1214.25  6589.0  2263.750  8251.0  2559.125  8539.0
한국투자공사               66.00   243.0    76.500   267.0    79.000   285.0
한국특허전략개발원            43.50   161.0    52.750   224.0    66.500   224.0
한국특허정보원             144.75   378.0   156.000   382.0   159.000   382.0
한국표준과학연구원            48.50   444.0    50.500   461.0    59.500   464.0
한국학중앙연구원             67.00   237.0    79.000   248.0   100.500   271.0
한국한의학연구원             61.00   185.0    59.000   195.0    54.750   203.0
한국항공우주연구원            70.80   855.0    71.100   888.0    89.600   967.0
한국항로표지기술원             7.00    48.0     6.000    44.0    10.000    51.0
한국해양과학기술원            60.00   442.0    60.000   442.0   101.000   518.0
한국해양수산개발원            52.00   155.0    56.000   165.0    85.000   218.0
한국해양수산연수원            23.00   162.0    31.000   177.0    36.000   191.0
한국해양조사협회              7.00    46.0     8.000    46.0     9.000    53.0
한국행정연구원              25.00    84.0    26.000    84.0    47.000   126.0
한국형사정책연구원            32.00    72.0    29.750    73.0    34.000    92.0
한국화학연구원              69.00   431.0    77.000   440.0    78.000   583.0
한국환경공단              526.00  2353.0   525.180  2390.0   664.000  2749.0
한국환경산업기술원           124.50   344.0   185.300   478.0   194.325   514.0
한국환경정책평가연구원          65.00   176.0    63.000   176.0    64.000   180.0
한약진흥재단               22.00    56.0    23.000    66.0    49.000   139.0
한전KDN               169.50  2392.0   186.500  2502.0   210.000  2554.0
한전KPS(주)            214.75  5718.0   231.000  6300.0   281.500  6236.0
한전원자력연료주식회사          67.00  1166.0    68.000  1178.0    72.625  1186.0
항공안전기술원               7.00    36.0    13.000    90.0    25.000    92.0
해양수산과학기술진흥원          21.75    75.0    26.000    75.0    28.000    80.0
해양환경공단               67.75   594.0    75.250   618.0    94.630   666.0
환경보전협회               49.00   251.0    46.000   251.0    43.000   251.0

[360 rows x 12 columns]

### **#여성 비율 랭킹**

In [22]:
for y in col_year:
    df_emp_pivot_woman[(y, '여성 비율')] = df_emp_pivot_woman[(y, '여성 현원')] / df_emp_pivot_woman[(y, '임직원 총계')] * 100

df_emp_pivot_woman.sort_values(('2018', '여성 비율'), ascending=True)

                        2013               2014               2015           \
항목                     여성 현원   임직원 총계     여성 현원   임직원 총계     여성 현원   임직원 총계
기관명
대한석탄공사                44.000   1720.0    38.000   1384.0    38.000   1384.0
(주)한국건설관리공사            8.000    416.0     7.000    416.0     7.000    416.0
한전KPS(주)             130.000   4877.0   157.000   5167.0   209.000   5464.0
(주)한국가스기술공사           32.000   1173.0    45.000   1289.0    44.500   1359.0
선박해양플랜트연구소             0.000      0.0     5.000    143.0     7.000    148.0
나노종합기술원                4.000     75.0     4.000     78.0     4.000     78.0
한전원자력연료주식회사           60.000    998.0    69.000   1070.0    71.000   1111.0
(재)우체국물류지원단           17.000    944.0    62.000   1400.0    73.500   1400.0
재료연구소                 12.000    240.0    15.000    251.0    20.000    268.0
한국전기안전공사             125.000   2693.0   118.000   2703.0   142.000   2743.0
코레일로지스(주)             11.000     99.0     9.000    101.0     7.000    101.0
주식회사 부산항보안공사          12.000    320.0    14.000    325.0    14.000    325.0
한국기계연구원               22.000    342.0    27.000    358.0    35.000    373.0
한국원자력연구원              78.000   1309.0    86.000   1328.0    91.000   1345.0
한국철도기술연구원             19.000    297.0    21.000    310.0    24.000    319.0
한전KDN                124.500   1846.0   127.500   1846.0   157.500   2267.0
한국전기연구원               32.000    395.0    32.000    404.0    34.000    410.0
한국전력기술주식회사           193.000   2330.0   208.000   2336.0   197.000   2336.0
국방기술품질원               69.000    509.0    77.000    509.0    93.000    602.0
한국항공우주연구원             67.000    754.0    67.000    790.0    70.600    821.0
한국어촌어항공단               2.000     68.0     5.000    107.0     6.000    111.0
한국도로공사               474.000   4484.0   471.125   5686.0   506.500   5826.0
한국철도공사              2294.000  27981.0  2390.500  27981.0  2395.750  27981.0
한국남동발전(주)            210.875   2049.0   222.750   2149.0   222.500   2189.0
주식회사 에스알               0.000      6.0     1.000    437.0    18.000    437.0
한국산업기술시험원             24.000    354.0    49.000    580.0    68.500    580.0
한국공항공사               143.125   1782.0   162.750   1857.0   179.250   1888.0
주식회사 인천항보안공사          19.000    203.0    21.000    209.0    23.000    213.0
한국가스공사               336.000   3256.0   346.000   3441.0   350.000   3521.0
한국승강기안전공단             62.250    831.0    69.750    928.0    86.875   1011.0
...                      ...      ...       ...      ...       ...      ...
재단법인 한국장기조직기증원         0.000      0.0     0.000      0.0     0.000      0.0
(재)한국형수치예보모델개발사업단     35.000     58.0    24.000     58.0    25.000     58.0
대한적십자사              1810.000   3314.0  1988.000   3365.0  2068.000   3409.0
한국문학번역원               19.000     36.0    18.500     36.0    19.000     38.0
세종학당재단                12.000     20.0    15.000     22.0    16.000     27.0
경북대학교병원             1572.000   2843.0  1614.000   2929.0  1732.000   3010.0
국방전직교육원                0.000      0.0     0.000      0.0    14.000     26.0
부산대학교병원             2285.000   3429.0  2461.000   3978.0  2662.000   4341.0
한국보훈복지의료공단          2318.250   4432.0  2581.600   4662.0  3016.350   4721.0
국립중앙의료원              591.000    928.0   589.000    937.0   608.000    966.0
한국건강증진개발원             37.000     49.0    41.000     55.0    42.000     60.0
전북대학교병원             1120.000   2282.0  1155.000   2369.0  1218.000   2515.0
충남대학교병원             1096.000   2426.0  1151.000   2417.0  1195.000   2536.0
국립암센터                735.000   1197.0   752.000   1203.0   731.000   1216.0
의료법인 한전의료재단 한일병원     376.000    654.0   363.000    654.0   383.000    654.0
아시아문화원                 0.000      0.0     0.000      0.0    25.000     96.0
한국여성정책연구원             78.000    101.0    79.000    106.0    82.000    106.0
충북대학교병원              663.000   1149.0   679.000   1189.0   718.000   1247.0
서울대학교병원             3390.000   6016.0  3712.000   6232.0  3749.000   6259.0
육아정책연구소               26.000     38.0    29.000     41.0    31.000     50.0
북한이탈주민지원재단            19.000     43.0    16.000     44.0    16.000     46.0
한국건강가정진흥원              0.000     23.0     0.000     23.0    77.000     92.0
분당서울대학교병원           1706.000   2534.0  1756.000   2552.0  1827.000   2575.0
한국보건의료연구원             51.000     77.0    51.000     79.0    55.000     82.0
건강보험심사평가원           1435.750   1917.0  1621.250   2117.0  1848.500   2377.0
한국문화예술교육진흥원           24.000     39.0    25.000     47.0    33.000     56.0
재단법인 한국여성과학기술인지원센터    15.000     25.0    18.000     25.0    18.000     25.0
한국보육진흥원              155.000     59.0   206.000    228.0   249.500    306.0
서울요양원                  0.000      0.0     0.000     80.0     0.000     80.0
코레일테크(주)               8.000     59.0     8.000     59.0     6.000     59.0

                        2016               2017               2018             \
항목                     여성 현원   임직원 총계     여성 현원   임직원 총계     여성 현원     임직원 총계
기관명
대한석탄공사                40.000   1399.0    42.000   1251.0    40.500   1135.000
(주)한국건설관리공사           10.000    416.0    13.000    381.0    15.000    380.000
한전KPS(주)             214.750   5718.0   231.000   6300.0   281.500   6236.000
(주)한국가스기술공사           44.500   1423.0    59.500   1478.0    76.000   1564.000
선박해양플랜트연구소            10.000    197.0    12.000    207.0    12.000    221.000
나노종합기술원                5.000     81.0     6.000     83.0     5.000     85.000
한전원자력연료주식회사           67.000   1166.0    68.000   1178.0    72.625   1186.000
(재)우체국물류지원단           51.380   1413.0   100.280   1535.0    99.530   1601.500
재료연구소                 22.000    279.0    23.000    290.0    22.000    350.000
한국전기안전공사             153.000   2848.0   158.000   3002.0   195.190   3063.000
코레일로지스(주)              8.000    101.0     5.000    132.0     8.750    132.000
주식회사 부산항보안공사          14.000    364.0    22.000    456.0    33.000    485.000
한국기계연구원               36.000    389.0    36.000    394.0    36.000    468.000
한국원자력연구원             108.500   1469.0   103.500   1506.0   134.000   1652.000
한국철도기술연구원             26.000    325.0    28.000    327.0    27.000    331.000
한전KDN                169.500   2392.0   186.500   2502.0   210.000   2554.000
한국전기연구원               37.000    422.0    43.375    426.0    45.000    535.000
한국전력기술주식회사           206.000   2336.0   211.000   2370.0   213.000   2360.000
국방기술품질원               89.000    721.0    81.000    747.0    81.000    891.000
한국항공우주연구원             70.800    855.0    71.100    888.0    89.600    967.000
한국어촌어항공단               5.000    115.0     5.000    124.0    16.000    172.000
한국도로공사               528.125   6003.0   576.725   6076.0   611.125   6320.000
한국철도공사              2526.250  28441.0  2717.625  28773.0  2876.125  29602.000
한국남동발전(주)            222.625   2289.0   246.000   2349.0   237.000   2417.000
주식회사 에스알              49.000    526.0    52.000    526.0    62.000    624.000
한국산업기술시험원             78.500    720.0    76.500    749.0    77.500    761.000
한국공항공사               204.250   2088.0   240.000   2186.0   261.000   2534.000
주식회사 인천항보안공사          23.000    341.0    28.000    341.0    36.000    340.000
한국가스공사               390.000   3735.0   411.350   3853.0   436.200   4111.000
한국승강기안전공단             95.375   1025.0   109.125   1232.0   134.375   1234.000
...                      ...      ...       ...      ...       ...        ...
재단법인 한국장기조직기증원         0.000      0.0    64.000    100.0    58.000    100.000
(재)한국형수치예보모델개발사업단     25.000     60.0    36.000     60.0    35.000     60.000
대한적십자사              2139.000   3528.0  2150.500   3671.0  2296.000   3909.000
한국문학번역원               20.000     41.0    28.000     42.0    29.000     49.000
세종학당재단                41.000     62.0    38.000     82.0    51.000     85.000
경북대학교병원             1855.000   3044.0  1934.000   3141.0  2360.000   3862.000
국방전직교육원               14.000     27.0    13.000     27.0    24.000     39.000
부산대학교병원             2792.000   4568.0  2872.000   4725.0  3687.000   5943.000
한국보훈복지의료공단          3223.050   4906.0  3272.925   5202.0  3957.600   6356.125
국립중앙의료원              682.000   1048.0   667.000   1052.0   808.000   1286.000
한국건강증진개발원             49.000     75.0    46.000     76.0    82.000    128.000
전북대학교병원             1272.000   2524.0  1348.000   2619.0  1680.000   2619.000
충남대학교병원             1665.000   2640.0  1848.130   2752.0  2056.500   3191.600
국립암센터                796.000   1292.0   841.000   1332.0   917.050   1420.100
의료법인 한전의료재단 한일병원     431.000    705.0   450.000    751.0   486.000    751.000
아시아문화원                48.000     96.0    55.000     96.0   160.000    247.000
한국여성정책연구원             82.000    109.0    81.000    112.0    87.000    134.000
충북대학교병원              939.000   1341.0  1113.000   1484.0  1186.000   1762.000
서울대학교병원             4027.000   6268.0  4255.000   6383.0  4426.000   6564.000
육아정책연구소               34.000     49.0    34.000     49.0    38.000     56.000
북한이탈주민지원재단            18.000     52.0    22.000     54.0   121.000    178.000
한국건강가정진흥원             81.000    142.0   101.000    176.0   124.000    181.000
분당서울대학교병원           1862.000   2639.0  2000.000   2775.0  2187.000   3143.000
한국보건의료연구원             70.000     97.0    94.500    145.0   106.630    151.000
건강보험심사평가원           1916.750   2529.0  2127.500   2790.0  2312.000   3222.000
한국문화예술교육진흥원           44.000     90.0    84.000    116.0    89.000    120.000
재단법인 한국여성과학기술인지원센터    17.000     36.0    17.750     41.0    30.750     41.000
한국보육진흥원              253.000    328.0   239.500    328.0   320.000    371.000
서울요양원                 23.000     80.0    79.000    118.0   110.000    118.000
코레일테크(주)               8.000     58.0     9.000    582.0  1350.775    661.000

                          2013       2014       2015       2016       2017  \
항목                       여성 비율      여성 비율      여성 비율      여성 비율      여성 비율
기관명
대한석탄공사                2.558140   2.745665   2.745665   2.859185   3.357314
(주)한국건설관리공사           1.923077   1.682692   1.682692   2.403846   3.412073
한전KPS(주)              2.665573   3.038514   3.825037   3.755684   3.666667
(주)한국가스기술공사           2.728048   3.491078   3.274467   3.127196   4.025710
선박해양플랜트연구소                 NaN   3.496503   4.729730   5.076142   5.797101
나노종합기술원               5.333333   5.128205   5.128205   6.172840   7.228916
한전원자력연료주식회사           6.012024   6.448598   6.390639   5.746141   5.772496
(재)우체국물류지원단           1.800847   4.428571   5.250000   3.636235   6.532899
재료연구소                 5.000000   5.976096   7.462687   7.885305   7.931034
한국전기안전공사              4.641664   4.365520   5.176814   5.372191   5.263158
코레일로지스(주)            11.111111   8.910891   6.930693   7.920792   3.787879
주식회사 부산항보안공사          3.750000   4.307692   4.307692   3.846154   4.824561
한국기계연구원               6.432749   7.541899   9.383378   9.254499   9.137056
한국원자력연구원              5.958747   6.475904   6.765799   7.385977   6.872510
한국철도기술연구원             6.397306   6.774194   7.523511   8.000000   8.562691
한전KDN                 6.744312   6.906826   6.947508   7.086120   7.454037
한국전기연구원               8.101266   7.920792   8.292683   8.767773  10.181925
한국전력기술주식회사            8.283262   8.904110   8.433219   8.818493   8.902954
국방기술품질원              13.555992  15.127701  15.448505  12.343967  10.843373
한국항공우주연구원             8.885942   8.481013   8.599269   8.280702   8.006757
한국어촌어항공단              2.941176   4.672897   5.405405   4.347826   4.032258
한국도로공사               10.570919   8.285702   8.693786   8.797684   9.491853
한국철도공사                8.198420   8.543297   8.562060   8.882423   9.445053
한국남동발전(주)            10.291606  10.365286  10.164459   9.725863  10.472542
주식회사 에스알              0.000000   0.228833   4.118993   9.315589   9.885932
한국산업기술시험원             6.779661   8.448276  11.810345  10.902778  10.213618
한국공항공사                8.031706   8.764136   9.494174   9.782088  10.978957
주식회사 인천항보안공사          9.359606  10.047847  10.798122   6.744868   8.211144
한국가스공사               10.319410  10.055217   9.940358  10.441767  10.676097
한국승강기안전공단             7.490975   7.516164   8.592977   9.304878   8.857549
...                        ...        ...        ...        ...        ...
재단법인 한국장기조직기증원             NaN        NaN        NaN        NaN  64.000000
(재)한국형수치예보모델개발사업단    60.344828  41.379310  43.103448  41.666667  60.000000
대한적십자사               54.616777  59.078752  60.662951  60.629252  58.580768
한국문학번역원              52.777778  51.388889  50.000000  48.780488  66.666667
세종학당재단               60.000000  68.181818  59.259259  66.129032  46.341463
경북대학교병원              55.293704  55.104131  57.541528  60.939553  61.572748
국방전직교육원                    NaN        NaN  53.846154  51.851852  48.148148
부산대학교병원              66.637504  61.865259  61.322276  61.120841  60.783069
한국보훈복지의료공단           52.307085  55.375375  63.892184  65.696086  62.916667
국립중앙의료원              63.685345  62.860192  62.939959  65.076336  63.403042
한국건강증진개발원            75.510204  74.545455  70.000000  65.333333  60.526316
전북대학교병원              49.079755  48.754749  48.429423  50.396197  51.470027
충남대학교병원              45.177246  47.621018  47.121451  63.068182  67.155887
국립암센터                61.403509  62.510391  60.115132  61.609907  63.138138
의료법인 한전의료재단 한일병원     57.492355  55.504587  58.562691  61.134752  59.920107
아시아문화원                     NaN        NaN  26.041667  50.000000  57.291667
한국여성정책연구원            77.227723  74.528302  77.358491  75.229358  72.321429
충북대학교병원              57.702350  57.106812  57.578188  70.022371  75.000000
서울대학교병원              56.349734  59.563543  59.897747  64.246969  66.661444
육아정책연구소              68.421053  70.731707  62.000000  69.387755  69.387755
북한이탈주민지원재단           44.186047  36.363636  34.782609  34.615385  40.740741
한국건강가정진흥원             0.000000   0.000000  83.695652  57.042254  57.386364
분당서울대학교병원            67.324388  68.808777  70.951456  70.557029  72.072072
한국보건의료연구원            66.233766  64.556962  67.073171  72.164948  65.172414
건강보험심사평가원            74.895670  76.582428  77.766092  75.790826  76.254480
한국문화예술교육진흥원          61.538462  53.191489  58.928571  48.888889  72.413793
재단법인 한국여성과학기술인지원센터   60.000000  72.000000  72.000000  47.222222  43.292683
한국보육진흥원             262.711864  90.350877  81.535948  77.134146  73.018293
서울요양원                      NaN   0.000000   0.000000  28.750000  66.949153
코레일테크(주)             13.559322  13.559322  10.169492  13.793103   1.546392

                          2018
항목                       여성 비율
기관명
대한석탄공사                3.568282
(주)한국건설관리공사           3.947368
한전KPS(주)              4.514112
(주)한국가스기술공사           4.859335
선박해양플랜트연구소            5.429864
나노종합기술원               5.882353
한전원자력연료주식회사           6.123524
(재)우체국물류지원단           6.214799
재료연구소                 6.285714
한국전기안전공사              6.372511
코레일로지스(주)             6.628788
주식회사 부산항보안공사          6.804124
한국기계연구원               7.692308
한국원자력연구원              8.111380
한국철도기술연구원             8.157100
한전KDN                 8.222396
한국전기연구원               8.411215
한국전력기술주식회사            9.025424
국방기술품질원               9.090909
한국항공우주연구원             9.265770
한국어촌어항공단              9.302326
한국도로공사                9.669699
한국철도공사                9.715982
한국남동발전(주)             9.805544
주식회사 에스알              9.935897
한국산업기술시험원            10.183968
한국공항공사               10.299921
주식회사 인천항보안공사         10.588235
한국가스공사               10.610557
한국승강기안전공단            10.889384
...                        ...
재단법인 한국장기조직기증원       58.000000
(재)한국형수치예보모델개발사업단    58.333333
대한적십자사               58.736250
한국문학번역원              59.183673
세종학당재단               60.000000
경북대학교병원              61.108234
국방전직교육원              61.538462
부산대학교병원              62.039374
한국보훈복지의료공단           62.264351
국립중앙의료원              62.830482
한국건강증진개발원            64.062500
전북대학교병원              64.146621
충남대학교병원              64.434766
국립암센터                64.576438
의료법인 한전의료재단 한일병원     64.713715
아시아문화원               64.777328
한국여성정책연구원            64.925373
충북대학교병원              67.309875
서울대학교병원              67.428397
육아정책연구소              67.857143
북한이탈주민지원재단           67.977528
한국건강가정진흥원            68.508287
분당서울대학교병원            69.583201
한국보건의료연구원            70.615894
건강보험심사평가원            71.756673
한국문화예술교육진흥원          74.166667
재단법인 한국여성과학기술인지원센터   75.000000
한국보육진흥원              86.253369
서울요양원                93.220339
코레일테크(주)            204.353253

[360 rows x 18 columns]

### **#여성 6년 추이**

In [23]:
col_임직원총계 = [(y, '임직원 총계') for y in col_year]
col_여성 = [(y, '여성 현원') for y in col_year]


tmp = df_emp_pivot_woman[[*col_임직원총계, *col_여성]].sum()
print(tmp)

data = []
for y in col_year:
    datum = {
        '연도': y,
        '여성': tmp[(y, '여성 현원')],
        '임직원총계': tmp[(y, '임직원 총계')],
        '총 여성 비율': tmp[(y, '여성 현원')] / tmp[(y, '임직원 총계')] * 100
        
    }
    data.append(datum)

df_total_woman = pd.DataFrame(data)

del tmp
df_total_woman

      항목
2013  임직원 총계    287426.0000
2014  임직원 총계    305194.0000
2015  임직원 총계    315505.5000
2016  임직원 총계    329316.0000
2017  임직원 총계    347231.4200
2018  임직원 총계    378867.5200
2013  여성 현원      74057.7050
2014  여성 현원      78909.1650
2015  여성 현원      83661.9680
2016  여성 현원      90880.8150
2017  여성 현원      99605.5325
2018  여성 현원     115020.0575
dtype: float64

            여성    연도      임직원총계    총 여성 비율
0   74057.7050  2013  287426.00  25.765834
1   78909.1650  2014  305194.00  25.855412
2   83661.9680  2015  315505.50  26.516802
3   90880.8150  2016  329316.00  27.596842
4   99605.5325  2017  347231.42  28.685633
5  115020.0575  2018  378867.52  30.358912

## **#여성 임금 격차 랭킹**

In [24]:
'''
정규직_1인당_평균_보수액_(남성)
정규직_1인당_평균_보수액_(여성)
'''
idx_pay_man = df_pay['항목'] == '정규직_1인당_평균_보수액_(남성)'
idx_pay_woman = df_pay['항목'] == '정규직_1인당_평균_보수액_(여성)'
df_pay.loc[idx_pay_man | idx_pay_woman].head(100)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
9,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,59476.0,61398.0,명,N
10,(사)남북교류협력지원협회,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,35775.0,35592.0,명,N
24,(재)APEC기후센터,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,62366.0,62946.0,명,N
25,(재)APEC기후센터,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,54040.0,57468.0,명,N
39,(재)국제원산지정보원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,46792.0,46539.0,명,N
40,(재)국제원산지정보원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,43444.0,43209.0,명,N
54,(재)예술경영지원센터,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,53712.0,54179.0,명,N
55,(재)예술경영지원센터,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,40458.0,41616.0,명,N
69,(재)우체국금융개발원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,61292.0,62824.0,명,N
70,(재)우체국금융개발원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,51151.0,52430.0,명,N
84,(재)우체국물류지원단,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,53766.0,51117.0,명,N
85,(재)우체국물류지원단,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,46009.0,41459.0,명,N
99,(재)우체국시설관리단,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,58909.0,59724.0,명,N
100,(재)우체국시설관리단,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,40937.0,44266.0,명,N
114,(재)일제강제동원피해자지원재단,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,45171.0,43270.0,명,N
115,(재)일제강제동원피해자지원재단,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,28199.0,34976.0,명,N
129,(재)정동극장,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,48704.0,57532.0,명,N
130,(재)정동극장,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,36825.0,47632.0,명,N
144,(재)중소기업연구원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,70411.0,78978.0,명,N
145,(재)중소기업연구원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,57344.0,58181.0,명,N
159,(재)한국스마트그리드사업단,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,61105.0,63276.0,명,N
160,(재)한국스마트그리드사업단,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,41766.0,43937.0,명,N
174,(재)한국우편사업진흥원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,52235.0,52969.0,명,N
175,(재)한국우편사업진흥원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,47113.0,45984.0,명,N
189,(재)한국형수치예보모델개발사업단,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,82374.0,85528.0,명,N
190,(재)한국형수치예보모델개발사업단,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,73636.0,72242.0,명,N
204,(재)한식진흥원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,64766.0,63912.0,명,N
205,(재)한식진흥원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,61733.0,63912.0,명,N
219,(주)강원랜드,공기업(시장형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,74596.0,75591.0,명,N
220,(주)강원랜드,공기업(시장형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,63217.0,64975.0,명,N
...,...,...,...,...,...,...,...,...,...,...,...
534,과학기술정책연구원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,79531.0,84822.0,명,N
535,과학기술정책연구원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,57218.0,61024.0,명,N
549,광주과학기술원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,102365.0,102365.0,명,N
550,광주과학기술원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,81570.0,81570.0,명,N
564,국가과학기술연구회,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,87215.0,79220.0,명,N
565,국가과학기술연구회,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,57232.0,69058.0,명,N
579,국가과학기술인력개발원,부설기관(한국과학기술기획평가원),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,81494.0,71668.0,명,Y
580,국가과학기술인력개발원,부설기관(한국과학기술기획평가원),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,73000.0,56697.0,명,Y
594,국가수리과학연구소,부설기관(기초과학연구원),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,75754.0,77710.0,명,Y
595,국가수리과학연구소,부설기관(기초과학연구원),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,64288.0,65324.0,명,Y
609,국가평생교육진흥원,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,78978.0,0.0,명,N
610,국가평생교육진흥원,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,69281.0,0.0,명,N
624,국가핵융합연구소,부설기관(한국기초과학지원연구원),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,78463.0,78463.0,명,Y
625,국가핵융합연구소,부설기관(한국기초과학지원연구원),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,78463.0,78463.0,명,Y
639,국립공원관리공단,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,56784.0,56588.0,명,N
640,국립공원관리공단,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,44272.0,44087.0,명,N
654,국립광주과학관,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,53747.0,57409.0,명,N
655,국립광주과학관,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,54141.0,56205.0,명,N
669,국립낙동강생물자원관,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,65981.0,64104.0,명,N
670,국립낙동강생물자원관,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,50928.0,50910.0,명,N
684,국립대구과학관,기타공공기관,정규직_1인당_평균_보수액_(남성),38208.0,56812.0,56853.0,62291.0,60159.0,62009.0,명,N
685,국립대구과학관,기타공공기관,정규직_1인당_평균_보수액_(여성),25072.0,37280.0,37307.0,40876.0,39477.0,47055.0,명,N
699,국립박물관문화재단,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,57662.0,0.0,명,N
700,국립박물관문화재단,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,41292.0,0.0,명,N
714,국립부산과학관,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,66614.0,63832.0,명,N
715,국립부산과학관,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,53121.0,49011.0,명,N
729,국립생태원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,64699.0,66491.0,명,N
730,국립생태원,준정부기관(위탁집행형),정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,52758.0,57307.0,명,N
744,국립암센터,기타공공기관,정규직_1인당_평균_보수액_(남성),0.0,0.0,0.0,0.0,93471.0,99515.0,명,N
745,국립암센터,기타공공기관,정규직_1인당_평균_보수액_(여성),0.0,0.0,0.0,0.0,59514.0,63362.0,명,N

In [25]:
df_pay_pivot_woman = df_pay.loc[idx_pay_man | idx_pay_woman].pivot(index='기관명', columns='항목', values=col_year)
df_pay_pivot_woman.columns.set_levels(['남성 보수', '여성 보수'], level=1, inplace=True)

import numpy as np
df_pay_pivot_woman.replace(0.0, np.nan, inplace=True)

df_pay_pivot_woman

                       2013               2014               2015           \
항목                    남성 보수    여성 보수     남성 보수    여성 보수     남성 보수    여성 보수
기관명
(사)남북교류협력지원협회           NaN      NaN       NaN      NaN       NaN      NaN
(재)APEC기후센터             NaN      NaN       NaN      NaN       NaN      NaN
(재)국제원산지정보원             NaN      NaN       NaN      NaN       NaN      NaN
(재)예술경영지원센터             NaN      NaN       NaN      NaN       NaN      NaN
(재)우체국금융개발원             NaN      NaN       NaN      NaN       NaN      NaN
(재)우체국물류지원단             NaN      NaN       NaN      NaN       NaN      NaN
(재)우체국시설관리단             NaN      NaN       NaN      NaN       NaN      NaN
(재)일제강제동원피해자지원재단        NaN      NaN       NaN      NaN       NaN      NaN
(재)정동극장                 NaN      NaN       NaN      NaN       NaN      NaN
(재)중소기업연구원              NaN      NaN       NaN      NaN       NaN      NaN
(재)한국스마트그리드사업단          NaN      NaN       NaN      NaN       NaN      NaN
(재)한국우편사업진흥원            NaN      NaN       NaN      NaN       NaN      NaN
(재)한국형수치예보모델개발사업단       NaN      NaN       NaN      NaN       NaN      NaN
(재)한식진흥원                NaN      NaN       NaN      NaN       NaN      NaN
(주)강원랜드                 NaN      NaN       NaN      NaN       NaN      NaN
(주)워터웨이플러스              NaN      NaN       NaN      NaN       NaN      NaN
(주)한국가스기술공사             NaN      NaN       NaN      NaN       NaN      NaN
(주)한국건설관리공사             NaN      NaN       NaN      NaN       NaN      NaN
88관광개발(주)               NaN      NaN       NaN      NaN       NaN      NaN
IOM이민정책연구원              NaN      NaN       NaN      NaN       NaN      NaN
KDI국제정책대학원         107988.0  76044.0  110745.0  85362.0  101319.0  77940.0
가축위생방역지원본부              NaN      NaN       NaN      NaN       NaN      NaN
강릉원주대학교치과병원         33640.0  28506.0   34230.0  30670.0   38810.0  32770.0
강원대학교병원                 NaN      NaN       NaN      NaN       NaN      NaN
건강보험심사평가원               NaN      NaN       NaN      NaN       NaN      NaN
건설근로자공제회                NaN      NaN       NaN      NaN       NaN      NaN
건축도시공간연구소               NaN      NaN       NaN      NaN       NaN      NaN
게임물관리위원회                NaN      NaN       NaN      NaN       NaN      NaN
경북대학교병원                 NaN      NaN       NaN      NaN       NaN      NaN
경북대학교치과병원               NaN      NaN       NaN      NaN       NaN      NaN
...                     ...      ...       ...      ...       ...      ...
한국체육산업개발(주)             NaN      NaN       NaN      NaN       NaN      NaN
한국출판문화산업진흥원             NaN      NaN       NaN      NaN       NaN      NaN
한국콘텐츠진흥원                NaN      NaN       NaN      NaN       NaN      NaN
한국토지주택공사                NaN      NaN       NaN      NaN       NaN      NaN
한국투자공사                  NaN      NaN       NaN      NaN       NaN      NaN
한국특허전략개발원               NaN      NaN       NaN      NaN       NaN      NaN
한국특허정보원                 NaN      NaN       NaN      NaN       NaN      NaN
한국표준과학연구원               NaN      NaN       NaN      NaN       NaN      NaN
한국학중앙연구원                NaN      NaN       NaN      NaN       NaN      NaN
한국한의학연구원                NaN      NaN       NaN      NaN       NaN      NaN
한국항공우주연구원               NaN      NaN       NaN      NaN       NaN      NaN
한국항로표지기술원               NaN      NaN       NaN      NaN       NaN      NaN
한국해양과학기술원               NaN      NaN       NaN      NaN       NaN      NaN
한국해양수산개발원               NaN      NaN       NaN      NaN       NaN      NaN
한국해양수산연수원               NaN      NaN       NaN      NaN       NaN      NaN
한국해양조사협회                NaN      NaN       NaN      NaN       NaN      NaN
한국행정연구원                 NaN      NaN       NaN      NaN       NaN      NaN
한국형사정책연구원               NaN      NaN       NaN      NaN       NaN      NaN
한국화학연구원                 NaN      NaN       NaN      NaN       NaN      NaN
한국환경공단                  NaN      NaN       NaN      NaN       NaN      NaN
한국환경산업기술원               NaN      NaN       NaN      NaN       NaN      NaN
한국환경정책평가연구원             NaN      NaN       NaN      NaN       NaN      NaN
한약진흥재단                  NaN      NaN       NaN      NaN       NaN      NaN
한전KDN                   NaN      NaN       NaN      NaN       NaN      NaN
한전KPS(주)                NaN      NaN       NaN      NaN       NaN      NaN
한전원자력연료주식회사             NaN      NaN       NaN      NaN       NaN      NaN
항공안전기술원                 NaN      NaN       NaN      NaN       NaN      NaN
해양수산과학기술진흥원             NaN      NaN       NaN      NaN       NaN      NaN
해양환경공단                  NaN      NaN       NaN      NaN       NaN      NaN
환경보전협회                  NaN      NaN       NaN      NaN       NaN      NaN

                      2016               2017              2018
항목                   남성 보수    여성 보수     남성 보수    여성 보수    남성 보수    여성 보수
기관명
(사)남북교류협력지원협회          NaN      NaN   59476.0  35775.0  61398.0  35592.0
(재)APEC기후센터            NaN      NaN   62366.0  54040.0  62946.0  57468.0
(재)국제원산지정보원            NaN      NaN   46792.0  43444.0  46539.0  43209.0
(재)예술경영지원센터            NaN      NaN   53712.0  40458.0  54179.0  41616.0
(재)우체국금융개발원            NaN      NaN   61292.0  51151.0  62824.0  52430.0
(재)우체국물류지원단            NaN      NaN   53766.0  46009.0  51117.0  41459.0
(재)우체국시설관리단            NaN      NaN   58909.0  40937.0  59724.0  44266.0
(재)일제강제동원피해자지원재단       NaN      NaN   45171.0  28199.0  43270.0  34976.0
(재)정동극장                NaN      NaN   48704.0  36825.0  57532.0  47632.0
(재)중소기업연구원             NaN      NaN   70411.0  57344.0  78978.0  58181.0
(재)한국스마트그리드사업단         NaN      NaN   61105.0  41766.0  63276.0  43937.0
(재)한국우편사업진흥원           NaN      NaN   52235.0  47113.0  52969.0  45984.0
(재)한국형수치예보모델개발사업단      NaN      NaN   82374.0  73636.0  85528.0  72242.0
(재)한식진흥원               NaN      NaN   64766.0  61733.0  63912.0  63912.0
(주)강원랜드                NaN      NaN   74596.0  63217.0  75591.0  64975.0
(주)워터웨이플러스             NaN      NaN   46877.0  32753.0  57423.0  40121.0
(주)한국가스기술공사            NaN      NaN   71727.0  52764.0  71071.0  52294.0
(주)한국건설관리공사            NaN      NaN   60683.0  33221.0  62261.0  34085.0
88관광개발(주)              NaN      NaN   39647.0  19031.0  39647.0  19031.0
IOM이민정책연구원             NaN      NaN   51866.0  43393.0  49230.0  50679.0
KDI국제정책대학원         89885.0  75597.0   92986.0  74080.0  92869.0  74086.0
가축위생방역지원본부             NaN      NaN   68808.0  51720.0  69496.0  52237.0
강릉원주대학교치과병원        39790.0  34550.0   40860.0  35640.0  41200.0  36500.0
강원대학교병원                NaN      NaN   68749.0  49877.0  70536.0  51174.0
건강보험심사평가원              NaN      NaN   71007.0  60741.0  63251.0  63251.0
건설근로자공제회               NaN      NaN   90701.0  58686.0  90336.0  60722.0
건축도시공간연구소              NaN      NaN   78153.0  74983.0  76373.0  73275.0
게임물관리위원회               NaN      NaN   52423.0  41687.0  54541.0  43371.0
경북대학교병원                NaN      NaN   71896.0  60162.0  73334.0  61967.0
경북대학교치과병원              NaN      NaN   61518.0  57284.0  64188.0  59813.0
...                    ...      ...       ...      ...      ...      ...
한국체육산업개발(주)            NaN      NaN   60087.0  46134.0  60849.0  48545.0
한국출판문화산업진흥원            NaN      NaN   57195.0  43331.0  63140.0  44634.0
한국콘텐츠진흥원               NaN      NaN   69134.0  49660.0  67085.0  48188.0
한국토지주택공사               NaN      NaN   77875.0  54136.0  70453.0  48976.0
한국투자공사                 NaN      NaN  121245.0  84017.0  89258.0  64904.0
한국특허전략개발원              NaN      NaN   65157.0  46721.0  66782.0  47513.0
한국특허정보원                NaN      NaN   59023.0  43421.0  59124.0  44020.0
한국표준과학연구원              NaN      NaN   93670.0  77845.0  82646.0  68684.0
한국학중앙연구원               NaN      NaN   71950.0  57184.0  71821.0  57081.0
한국한의학연구원               NaN      NaN   79216.0  74717.0  79216.0  74717.0
한국항공우주연구원              NaN      NaN   98799.0  73285.0  98799.0  73285.0
한국항로표지기술원              NaN      NaN   60606.0  49687.0  69587.0  50660.0
한국해양과학기술원              NaN      NaN   86829.0  75233.0  88597.0  76764.0
한국해양수산개발원              NaN      NaN   84830.0  54680.0  84000.0  53000.0
한국해양수산연수원              NaN      NaN   63733.0  52175.0  64447.0  52743.0
한국해양조사협회               NaN      NaN   55429.0  44674.0  56378.0  45791.0
한국행정연구원                NaN      NaN   69347.0  56564.0  70615.0  70615.0
한국형사정책연구원              NaN      NaN   69885.0  59134.0  78425.0  62298.0
한국화학연구원                NaN      NaN   96714.0  82208.0  83444.0  69940.0
한국환경공단                 NaN      NaN   60694.0  44704.0  61118.0  45091.0
한국환경산업기술원              NaN      NaN   70704.0  58070.0  72189.0  60476.0
한국환경정책평가연구원            NaN      NaN   79303.0  62666.0  75447.0  60080.0
한약진흥재단                 NaN      NaN   56991.0  49077.0  64475.0  59993.0
한전KDN                  NaN      NaN   78301.0  57020.0  69622.0  50700.0
한전KPS(주)               NaN      NaN   80707.0  58901.0  77249.0  58115.0
한전원자력연료주식회사            NaN      NaN   72692.0  55404.0  55923.0  55923.0
항공안전기술원                NaN      NaN   83324.0  57985.0  81412.0  60173.0
해양수산과학기술진흥원            NaN      NaN   78532.0  60677.0  80766.0  62431.0
해양환경공단                 NaN      NaN   70774.0  64651.0  69881.0  62167.0
환경보전협회                 NaN      NaN   62009.0  47507.0  56324.0  42210.0

[360 rows x 12 columns]

In [26]:
for y in col_year:
    df_pay_pivot_woman[(y, '임금 격차')] = df_pay_pivot_woman[(y, '남성 보수')] - df_pay_pivot_woman[(y, '여성 보수')]

df_pay_pivot_woman.head()
# df_pay_pivot_woman.sort_values(('2018', '여성 비율'), ascending=True)

               2013        2014        2015        2016           2017  \
항목            남성 보수 여성 보수 남성 보수 여성 보수 남성 보수 여성 보수 남성 보수 여성 보수    남성 보수
기관명
(사)남북교류협력지원협회   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  59476.0
(재)APEC기후센터     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  62366.0
(재)국제원산지정보원     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  46792.0
(재)예술경영지원센터     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  53712.0
(재)우체국금융개발원     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  61292.0

                           2018           2013  2014  2015  2016     2017  \
항목               여성 보수    남성 보수    여성 보수 임금 격차 임금 격차 임금 격차 임금 격차    임금 격차
기관명
(사)남북교류협력지원협회  35775.0  61398.0  35592.0   NaN   NaN   NaN   NaN  23701.0
(재)APEC기후센터    54040.0  62946.0  57468.0   NaN   NaN   NaN   NaN   8326.0
(재)국제원산지정보원    43444.0  46539.0  43209.0   NaN   NaN   NaN   NaN   3348.0
(재)예술경영지원센터    40458.0  54179.0  41616.0   NaN   NaN   NaN   NaN  13254.0
(재)우체국금융개발원    51151.0  62824.0  52430.0   NaN   NaN   NaN   NaN  10141.0

                  2018
항목               임금 격차
기관명
(사)남북교류협력지원협회  25806.0
(재)APEC기후센터     5478.0
(재)국제원산지정보원     3330.0
(재)예술경영지원센터    12563.0
(재)우체국금융개발원    10394.0

In [27]:
idx_pay_woman_na = df_pay_pivot_woman[('2018', '임금 격차')].isna()
woman_na_list = df_pay_pivot_woman.loc[idx_pay_woman_na].index.tolist()
print(woman_na_list)
df_pay_pivot_woman.loc[idx_pay_woman_na, ('2018', '임금 격차')] = df_pay_pivot_woman.loc[idx_pay_woman_na, ('2017', '임금 격차')]
df_pay_pivot_woman.sort_values(('2018', '임금 격차'), ascending=False)

['국가평생교육진흥원', '국립박물관문화재단', '국립중앙의료원', '대한법률구조공단', '대한석탄공사', '대한장애인체육회', '대한적십자사', '선박안전기술공단', '주식회사 에스알', '주택관리공단(주)', '주택도시보증공사', '한국건강가정진흥원', '한국나노기술원', '한국산업인력공단', '한국여성정책연구원', '한국전력공사', '한국전력국제원자력대학원대학교', '한국천문연구원']

                     2013               2014               2015           \
항목                  남성 보수    여성 보수     남성 보수    여성 보수     남성 보수    여성 보수
기관명
정부법무공단            91784.0  46189.0   88672.0  42471.0   99054.0  40196.0
한국산업은행                NaN      NaN       NaN      NaN       NaN      NaN
한국전력국제원자력대학원대학교       NaN      NaN       NaN      NaN       NaN      NaN
한국수출입은행               NaN      NaN       NaN      NaN       NaN      NaN
한국전기연구원               NaN      NaN       NaN      NaN       NaN      NaN
국민건강보험공단 일산병원         NaN      NaN       NaN      NaN       NaN      NaN
국립암센터                 NaN      NaN       NaN      NaN       NaN      NaN
한국전력거래소               NaN      NaN       NaN      NaN       NaN      NaN
한국예탁결제원               NaN      NaN       NaN      NaN       NaN      NaN
한국주택금융공사              NaN      NaN       NaN      NaN       NaN      NaN
동남권원자력의학원             NaN      NaN       NaN      NaN       NaN      NaN
한국건설기술연구원             NaN      NaN       NaN      NaN       NaN      NaN
울산과학기술원               NaN      NaN       NaN      NaN       NaN      NaN
한국무역보험공사              NaN      NaN       NaN      NaN       NaN      NaN
한국조세재정연구원             NaN      NaN       NaN      NaN       NaN      NaN
한국원자력환경공단             NaN      NaN       NaN      NaN       NaN      NaN
대외경제정책연구원             NaN      NaN       NaN      NaN       NaN      NaN
한국원자력의학원              NaN      NaN       NaN      NaN       NaN      NaN
한국해양수산개발원             NaN      NaN       NaN      NaN       NaN      NaN
고등과학원                 NaN      NaN       NaN      NaN       NaN      NaN
영화진흥위원회               NaN      NaN       NaN      NaN       NaN      NaN
예금보험공사                NaN      NaN       NaN      NaN       NaN      NaN
국방기술품질원               NaN      NaN       NaN      NaN       NaN      NaN
한국철도기술연구원             NaN      NaN       NaN      NaN       NaN      NaN
건설근로자공제회              NaN      NaN       NaN      NaN       NaN      NaN
영상물등급위원회              NaN      NaN       NaN      NaN       NaN      NaN
기초과학연구원               NaN      NaN       NaN      NaN       NaN      NaN
축산물품질평가원              NaN      NaN       NaN      NaN       NaN      NaN
한국장학재단                NaN      NaN       NaN      NaN       NaN      NaN
한국과학기술원          103199.0  77938.0  103351.0  78280.0  104669.0  78294.0
...                   ...      ...       ...      ...       ...      ...
한국개발연구원               NaN      NaN       NaN      NaN       NaN      NaN
한전원자력연료주식회사           NaN      NaN       NaN      NaN       NaN      NaN
재외동포재단                NaN      NaN       NaN      NaN       NaN      NaN
국민건강보험공단              NaN      NaN       NaN      NaN       NaN      NaN
제주대학교병원               NaN      NaN       NaN      NaN       NaN      NaN
한국공예디자인문화진흥원          NaN      NaN       NaN      NaN       NaN      NaN
(재)한식진흥원              NaN      NaN       NaN      NaN       NaN      NaN
한국행정연구원               NaN      NaN       NaN      NaN       NaN      NaN
국토연구원                 NaN      NaN       NaN      NaN       NaN      NaN
한국문화정보원               NaN      NaN       NaN      NaN       NaN      NaN
그랜드코리아레저(주)           NaN      NaN       NaN      NaN       NaN      NaN
건강보험심사평가원             NaN      NaN       NaN      NaN       NaN      NaN
한국산업기술진흥원             NaN      NaN       NaN      NaN       NaN      NaN
재단법인 국악방송             NaN      NaN       NaN      NaN       NaN      NaN
한국언론진흥재단              NaN      NaN       NaN      NaN       NaN      NaN
국가핵융합연구소              NaN      NaN       NaN      NaN       NaN      NaN
서울요양원                 NaN      NaN       NaN      NaN       NaN      NaN
한국문화관광연구원             NaN      NaN       NaN      NaN       NaN      NaN
한국에너지공단               NaN      NaN       NaN      NaN       NaN      NaN
재단법인 한국장기조직기증원        NaN      NaN       NaN      NaN       NaN      NaN
한국조폐공사                NaN      NaN       NaN      NaN       NaN      NaN
국제식물검역인증원             NaN      NaN       NaN      NaN       NaN      NaN
한국여성정책연구원             NaN      NaN       NaN      NaN       NaN      NaN
IOM이민정책연구원            NaN      NaN       NaN      NaN       NaN      NaN
한국교육과정평가원             NaN      NaN       NaN      NaN       NaN      NaN
한국건강가정진흥원             NaN      NaN       NaN      NaN       NaN      NaN
극지연구소                 NaN      NaN       NaN      NaN       NaN      NaN
육아정책연구소               NaN      NaN       NaN      NaN       NaN      NaN
한국세라믹기술원              NaN      NaN       NaN      NaN       NaN      NaN
한국양성평등교육진흥원           NaN      NaN       NaN      NaN       NaN      NaN

                     2016               2017               2018           \
항목                  남성 보수    여성 보수     남성 보수    여성 보수     남성 보수    여성 보수
기관명
정부법무공단           104452.0  43903.0  108235.0  51197.0  112000.0  54321.0
한국산업은행                NaN      NaN  122344.0  66247.0  115861.0  62684.0
한국전력국제원자력대학원대학교       NaN      NaN  105599.0  62561.0       NaN      NaN
한국수출입은행               NaN      NaN  113491.0  71648.0  107716.0  68318.0
한국전기연구원               NaN      NaN  105790.0  67793.0  107940.0  69190.0
국민건강보험공단 일산병원         NaN      NaN   92603.0  57825.0  100062.0  62482.0
국립암센터                 NaN      NaN   93471.0  59514.0   99515.0  63362.0
한국전력거래소               NaN      NaN   94474.0  59263.0   96930.0  60804.0
한국예탁결제원               NaN      NaN  119077.0  84701.0  120049.0  85056.0
한국주택금융공사              NaN      NaN   95388.0  61789.0   96933.0  62461.0
동남권원자력의학원             NaN      NaN   89506.0  59121.0   90985.0  57027.0
한국건설기술연구원             NaN      NaN   95343.0  61690.0   95343.0  61690.0
울산과학기술원               NaN      NaN  108345.0  72192.0  109265.0  75960.0
한국무역보험공사              NaN      NaN  100817.0  68074.0  102430.0  69163.0
한국조세재정연구원             NaN      NaN   96662.0  60022.0   94666.0  61402.0
한국원자력환경공단             NaN      NaN   85995.0  57111.0   83450.0  50666.0
대외경제정책연구원             NaN      NaN   82183.0  50879.0   82467.0  51055.0
한국원자력의학원              NaN      NaN   94885.0  63844.0   94885.0  63844.0
한국해양수산개발원             NaN      NaN   84830.0  54680.0   84000.0  53000.0
고등과학원                 NaN      NaN   84813.0  54613.0   86982.0  56028.0
영화진흥위원회               NaN      NaN   75867.0  45732.0   77840.0  46921.0
예금보험공사                NaN      NaN   94546.0  62577.0   91229.0  60647.0
국방기술품질원               NaN      NaN   85752.0  60522.0   89643.0  59733.0
한국철도기술연구원             NaN      NaN   95558.0  65657.0   95558.0  65657.0
건설근로자공제회              NaN      NaN   90701.0  58686.0   90336.0  60722.0
영상물등급위원회              NaN      NaN   62795.0  38196.0   75438.0  45886.0
기초과학연구원               NaN      NaN   88904.0  59433.0   88904.0  59433.0
축산물품질평가원              NaN      NaN   66870.0  37947.0   68270.0  38985.0
한국장학재단                NaN      NaN   86896.0  58064.0   85864.0  57029.0
한국과학기술원          105678.0  78399.0  105894.0  78805.0  106751.0  78191.0
...                   ...      ...       ...      ...       ...      ...
한국개발연구원               NaN      NaN   81945.0  62818.0   81240.0  81240.0
한전원자력연료주식회사           NaN      NaN   72692.0  55404.0   55923.0  55923.0
재외동포재단                NaN      NaN   54080.0  52086.0   51000.0  51000.0
국민건강보험공단              NaN      NaN   68406.0  54082.0   59392.0  59392.0
제주대학교병원               NaN      NaN   67708.0  50652.0   54798.0  54798.0
한국공예디자인문화진흥원          NaN      NaN   49314.0  45285.0   46535.0  46535.0
(재)한식진흥원              NaN      NaN   64766.0  61733.0   63912.0  63912.0
한국행정연구원               NaN      NaN   69347.0  56564.0   70615.0  70615.0
국토연구원                 NaN      NaN   78328.0  71190.0   86570.0  86570.0
한국문화정보원               NaN      NaN   49435.0  39663.0   47491.0  47491.0
그랜드코리아레저(주)           NaN      NaN   67733.0  62736.0   62006.0  62006.0
건강보험심사평가원             NaN      NaN   71007.0  60741.0   63251.0  63251.0
한국산업기술진흥원             NaN      NaN   73335.0  58941.0   69962.0  69962.0
재단법인 국악방송             NaN      NaN   46210.0  43012.0   48000.0  48000.0
한국언론진흥재단              NaN      NaN   87583.0  59906.0   79372.0  79372.0
국가핵융합연구소              NaN      NaN   78463.0  78463.0   78463.0  78463.0
서울요양원                 NaN      NaN   23857.0  23235.0   26094.0  26094.0
한국문화관광연구원             NaN      NaN   71840.0  55923.0   68457.0  68461.0
한국에너지공단               NaN      NaN   66043.0  51026.0   61678.0  61696.0
재단법인 한국장기조직기증원        NaN      NaN   51723.0  51868.0   51288.0  51685.0
한국조폐공사                NaN      NaN   83852.0  84347.0   93550.0  94102.0
국제식물검역인증원             NaN      NaN   46895.0  47904.0   45721.0  46376.0
한국여성정책연구원             NaN      NaN   65328.0  66269.0       NaN      NaN
IOM이민정책연구원            NaN      NaN   51866.0  43393.0   49230.0  50679.0
한국교육과정평가원             NaN      NaN   81544.0  83306.0   78639.0  80307.0
한국건강가정진흥원             NaN      NaN   39178.0  41230.0       NaN      NaN
극지연구소                 NaN      NaN   77066.0  79591.0   77066.0  79591.0
육아정책연구소               NaN      NaN   60319.0  56038.0   61424.0  66206.0
한국세라믹기술원              NaN      NaN   89189.0  94072.0   91113.0  96122.0
한국양성평등교육진흥원           NaN      NaN   49431.0  55103.0   49191.0  54836.0

                    2013     2014     2015     2016     2017     2018
항목                 임금 격차    임금 격차    임금 격차    임금 격차    임금 격차    임금 격차
기관명
정부법무공단           45595.0  46201.0  58858.0  60549.0  57038.0  57679.0
한국산업은행               NaN      NaN      NaN      NaN  56097.0  53177.0
한국전력국제원자력대학원대학교      NaN      NaN      NaN      NaN  43038.0  43038.0
한국수출입은행              NaN      NaN      NaN      NaN  41843.0  39398.0
한국전기연구원              NaN      NaN      NaN      NaN  37997.0  38750.0
국민건강보험공단 일산병원        NaN      NaN      NaN      NaN  34778.0  37580.0
국립암센터                NaN      NaN      NaN      NaN  33957.0  36153.0
한국전력거래소              NaN      NaN      NaN      NaN  35211.0  36126.0
한국예탁결제원              NaN      NaN      NaN      NaN  34376.0  34993.0
한국주택금융공사             NaN      NaN      NaN      NaN  33599.0  34472.0
동남권원자력의학원            NaN      NaN      NaN      NaN  30385.0  33958.0
한국건설기술연구원            NaN      NaN      NaN      NaN  33653.0  33653.0
울산과학기술원              NaN      NaN      NaN      NaN  36153.0  33305.0
한국무역보험공사             NaN      NaN      NaN      NaN  32743.0  33267.0
한국조세재정연구원            NaN      NaN      NaN      NaN  36640.0  33264.0
한국원자력환경공단            NaN      NaN      NaN      NaN  28884.0  32784.0
대외경제정책연구원            NaN      NaN      NaN      NaN  31304.0  31412.0
한국원자력의학원             NaN      NaN      NaN      NaN  31041.0  31041.0
한국해양수산개발원            NaN      NaN      NaN      NaN  30150.0  31000.0
고등과학원                NaN      NaN      NaN      NaN  30200.0  30954.0
영화진흥위원회              NaN      NaN      NaN      NaN  30135.0  30919.0
예금보험공사               NaN      NaN      NaN      NaN  31969.0  30582.0
국방기술품질원              NaN      NaN      NaN      NaN  25230.0  29910.0
한국철도기술연구원            NaN      NaN      NaN      NaN  29901.0  29901.0
건설근로자공제회             NaN      NaN      NaN      NaN  32015.0  29614.0
영상물등급위원회             NaN      NaN      NaN      NaN  24599.0  29552.0
기초과학연구원              NaN      NaN      NaN      NaN  29471.0  29471.0
축산물품질평가원             NaN      NaN      NaN      NaN  28923.0  29285.0
한국장학재단               NaN      NaN      NaN      NaN  28832.0  28835.0
한국과학기술원          25261.0  25071.0  26375.0  27279.0  27089.0  28560.0
...                  ...      ...      ...      ...      ...      ...
한국개발연구원              NaN      NaN      NaN      NaN  19127.0      0.0
한전원자력연료주식회사          NaN      NaN      NaN      NaN  17288.0      0.0
재외동포재단               NaN      NaN      NaN      NaN   1994.0      0.0
국민건강보험공단             NaN      NaN      NaN      NaN  14324.0      0.0
제주대학교병원              NaN      NaN      NaN      NaN  17056.0      0.0
한국공예디자인문화진흥원         NaN      NaN      NaN      NaN   4029.0      0.0
(재)한식진흥원             NaN      NaN      NaN      NaN   3033.0      0.0
한국행정연구원              NaN      NaN      NaN      NaN  12783.0      0.0
국토연구원                NaN      NaN      NaN      NaN   7138.0      0.0
한국문화정보원              NaN      NaN      NaN      NaN   9772.0      0.0
그랜드코리아레저(주)          NaN      NaN      NaN      NaN   4997.0      0.0
건강보험심사평가원            NaN      NaN      NaN      NaN  10266.0      0.0
한국산업기술진흥원            NaN      NaN      NaN      NaN  14394.0      0.0
재단법인 국악방송            NaN      NaN      NaN      NaN   3198.0      0.0
한국언론진흥재단             NaN      NaN      NaN      NaN  27677.0      0.0
국가핵융합연구소             NaN      NaN      NaN      NaN      0.0      0.0
서울요양원                NaN      NaN      NaN      NaN    622.0      0.0
한국문화관광연구원            NaN      NaN      NaN      NaN  15917.0     -4.0
한국에너지공단              NaN      NaN      NaN      NaN  15017.0    -18.0
재단법인 한국장기조직기증원       NaN      NaN      NaN      NaN   -145.0   -397.0
한국조폐공사               NaN      NaN      NaN      NaN   -495.0   -552.0
국제식물검역인증원            NaN      NaN      NaN      NaN  -1009.0   -655.0
한국여성정책연구원            NaN      NaN      NaN      NaN   -941.0   -941.0
IOM이민정책연구원           NaN      NaN      NaN      NaN   8473.0  -1449.0
한국교육과정평가원            NaN      NaN      NaN      NaN  -1762.0  -1668.0
한국건강가정진흥원            NaN      NaN      NaN      NaN  -2052.0  -2052.0
극지연구소                NaN      NaN      NaN      NaN  -2525.0  -2525.0
육아정책연구소              NaN      NaN      NaN      NaN   4281.0  -4782.0
한국세라믹기술원             NaN      NaN      NaN      NaN  -4883.0  -5009.0
한국양성평등교육진흥원          NaN      NaN      NaN      NaN  -5672.0  -5645.0

[360 rows x 18 columns]

# 근속연수

In [28]:
idx_lasting = df_pay['항목'].str.contains('평균근속연수')
df_pay.loc[idx_lasting].sort_values(['기관명', '항목']).head()

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
8,(사)남북교류협력지원협회,기타공공기관,무기계약직_평균근속연수,0.00,0.00,0.00,0.00,0.00,1.86,명,N
13,(사)남북교류협력지원협회,기타공공기관,무기계약직_평균근속연수_(남성),0.00,0.00,0.00,0.00,0.00,2.86,명,N
14,(사)남북교류협력지원협회,기타공공기관,무기계약직_평균근속연수_(여성),0.00,0.00,0.00,0.00,0.00,1.36,명,N
8,(사)남북교류협력지원협회,기타공공기관,정규직_평균근속연수,3.37,3.93,4.37,4.77,5.93,6.99,명,N
13,(사)남북교류협력지원협회,기타공공기관,정규직_평균근속연수_(남성),0.00,0.00,0.00,0.00,6.30,7.51,명,N

In [29]:
df_pay_pivot_lasting = df_pay.loc[idx_lasting].pivot(index='기관명', columns='항목', values=col_year)
df_pay_pivot_lasting.columns.set_levels(['무기_전체', '무기_남성', '무기_여성', '정규직_전체', '정규직_남성', '정규직_여성'], level=1, inplace=True)
df_pay_pivot_lasting

                    2013                                    2014              \
항목                 무기_전체 무기_남성 무기_여성 정규직_전체 정규직_남성 정규직_여성  무기_전체 무기_남성 무기_여성
기관명
(사)남북교류협력지원협회       0.00  0.00   0.0   3.37   0.00   0.00   0.00  0.00  0.00
(재)APEC기후센터          NaN   NaN   NaN   2.38   0.00   0.00    NaN   NaN   NaN
(재)국제원산지정보원         1.00  0.00   0.0   2.20   0.00   0.00   2.00  0.00  0.00
(재)예술경영지원센터         0.00  0.00   0.0   5.20   0.00   0.00   2.30  0.00  0.00
(재)우체국금융개발원         6.43  0.00   0.0  10.70   0.00   0.00   6.58  0.00  0.00
(재)우체국물류지원단         7.80  0.00   0.0  16.50   0.00   0.00   3.70  0.00  0.00
(재)우체국시설관리단         4.58  0.00   0.0   7.08   0.00   0.00   4.00  0.00  0.00
(재)일제강제동원피해자지원재단    0.00  0.00   0.0   0.00   0.00   0.00   0.00  0.00  0.00
(재)정동극장             3.92  0.00   0.0   6.36   0.00   0.00   3.00  0.00  0.00
(재)중소기업연구원          0.00  0.00   0.0   5.94   0.00   0.00   0.00  0.00  0.00
(재)한국스마트그리드사업단      2.00  0.00   0.0   3.44   0.00   0.00   3.00  0.00  0.00
(재)한국우편사업진흥원        5.99  0.00   0.0  12.47   0.00   0.00   7.00  0.00  0.00
(재)한국형수치예보모델개발사업단   0.00  0.00   0.0   2.90   0.00   0.00   0.00  0.00  0.00
(재)한식진흥원             NaN   NaN   NaN   1.58   0.00   0.00    NaN   NaN   NaN
(주)강원랜드             2.70  0.00   0.0   9.70   0.00   0.00   3.70  0.00  0.00
(주)워터웨이플러스          2.00  0.00   0.0   2.50   0.00   0.00   3.50  0.00  0.00
(주)한국가스기술공사         0.00  0.00   0.0  13.90   0.00   0.00   0.00  0.00  0.00
(주)한국건설관리공사         2.80  0.00   0.0  18.07   0.00   0.00   3.60  0.00  0.00
88관광개발(주)            NaN   NaN   NaN  13.70   0.00   0.00    NaN   NaN   NaN
IOM이민정책연구원          3.81  3.81   0.0   2.82   0.00   0.00   4.81  4.81  0.00
KDI국제정책대학원          0.00  0.00   0.0   9.40   9.46   9.08   6.00  6.08  5.94
가축위생방역지원본부          9.80  0.00   0.0   6.70   0.00   0.00   6.10  0.00  0.00
강릉원주대학교치과병원         1.00  0.00   1.0  12.00  12.00   8.00   1.00  0.00  1.00
강원대학교병원             1.66  0.00   0.0   7.25   0.00   0.00   1.37  0.00  0.00
건강보험심사평가원           0.00  0.00   0.0  13.71   0.00   0.00   0.00  0.00  0.00
건설근로자공제회            0.00  0.00   0.0   6.42   0.00   0.00   0.00  0.00  0.00
건축도시공간연구소           2.80  0.00   0.0   5.00   0.00   0.00   2.70  0.00  0.00
게임물관리위원회           54.50  0.00   0.0   5.52   0.00   0.00   0.00  0.00  0.00
경북대학교병원             1.87  0.00   0.0  10.84   0.00   0.00   2.74  0.00  0.00
경북대학교치과병원            NaN   NaN   NaN   0.00   0.00   0.00    NaN   NaN   NaN
...                  ...   ...   ...    ...    ...    ...    ...   ...   ...
한국체육산업개발(주)         6.30  0.00   0.0  17.40   0.00   0.00   6.80  0.00  0.00
한국출판문화산업진흥원         2.70  0.00   0.0  13.90   0.00   0.00   2.70  0.00  0.00
한국콘텐츠진흥원            4.40  0.00   0.0   4.20   0.00   0.00   4.60  0.00  0.00
한국토지주택공사            0.00  0.00   0.0  16.00   0.00   0.00   4.60  0.00  0.00
한국투자공사              2.73  0.00   0.0   2.92   0.00   0.00   3.29  0.00  0.00
한국특허전략개발원           2.46  0.00   0.0   3.49   0.00   0.00   2.98  0.00  0.00
한국특허정보원             2.98  0.00   0.0   9.97   0.00   0.00   3.40  0.00  0.00
한국표준과학연구원           0.10  0.10   0.1  16.30   0.00   0.00   1.10  1.10  1.10
한국학중앙연구원            3.20  0.00   0.0  10.45   0.00   0.00   3.38  0.00  0.00
한국한의학연구원            2.50  0.00   0.0   6.68   0.00   0.00   3.00  0.00  0.00
한국항공우주연구원           4.80  0.00   0.0  11.25   0.00   0.00   5.80  0.00  0.00
한국항로표지기술원           1.00  0.00   0.0   6.20   0.00   0.00   2.00  0.00  0.00
한국해양과학기술원           1.60  0.00   0.0  13.91   0.00   0.00   1.89  0.00  0.00
한국해양수산개발원          10.90  0.00   0.0  13.60   0.00   0.00  11.31  0.00  0.00
한국해양수산연수원           3.10  0.00   0.0  13.70   0.00   0.00   4.10  0.00  0.00
한국해양조사협회            0.00  0.00   0.0   3.90   0.00   0.00   0.00  0.00  0.00
한국행정연구원             0.00  0.00   0.0   9.16   0.00   0.00   0.80  0.00  0.00
한국형사정책연구원           4.10  0.00   0.0  11.60   0.00   0.00   4.80  0.00  0.00
한국화학연구원             0.00  0.00   0.0  16.70   0.00   0.00   0.00  0.00  0.00
한국환경공단              1.00  0.00   0.0  15.20   0.00   0.00   1.80  0.00  0.00
한국환경산업기술원           3.18  0.00   0.0   6.38   0.00   0.00   3.44  0.00  0.00
한국환경정책평가연구원         7.81  0.00   0.0  10.06   0.00   0.00   6.53  0.00  0.00
한약진흥재단              0.00  0.00   0.0   0.00   0.00   0.00   0.00  0.00  0.00
한전KDN               7.00  0.00   0.0  13.90   0.00   0.00   7.40  0.00  0.00
한전KPS(주)            8.55  0.00   0.0  17.00   0.00   0.00   4.34  0.00  0.00
한전원자력연료주식회사          NaN   NaN   NaN  12.64   0.00   0.00    NaN   NaN   NaN
항공안전기술원             0.00  0.00   0.0   0.97   0.00   0.00   0.00  0.00  0.00
해양수산과학기술진흥원         0.00  0.00   0.0   4.35   0.00   0.00   0.00  0.00  0.00
해양환경공단               NaN   NaN   NaN  10.15   0.00   0.00    NaN   NaN   NaN
환경보전협회              0.00  0.00   0.0  11.63   0.00   0.00   0.00  0.00  0.00

                          ...     2017                        2018        \
항목                정규직_전체  ...    무기_여성 정규직_전체 정규직_남성 정규직_여성  무기_전체 무기_남성
기관명                       ...
(사)남북교류협력지원협회       3.93  ...     0.00   5.93   6.30   4.76   1.86  2.86
(재)APEC기후센터         2.76  ...      NaN   4.66   4.55   4.79    NaN   NaN
(재)국제원산지정보원         2.80  ...     0.00   4.56   4.59   4.51   0.00  0.00
(재)예술경영지원센터         3.90  ...     3.20   5.40   5.40   5.40   2.60  2.80
(재)우체국금융개발원        11.50  ...     5.60  11.11  12.29   8.44   6.59  6.57
(재)우체국물류지원단        17.40  ...     3.10  19.66  19.84  12.02   3.77  3.92
(재)우체국시설관리단         6.16  ...     6.68   8.60   9.10   6.44   7.68  7.78
(재)일제강제동원피해자지원재단    0.47  ...     1.58   2.22   2.50   1.80   0.70  0.88
(재)정동극장             7.33  ...     3.71   8.08  10.75   3.33   5.08  5.50
(재)중소기업연구원          6.22  ...     0.00   7.68   7.57   7.97   0.00  0.00
(재)한국스마트그리드사업단      4.06  ...     2.00   3.67   3.93   3.00   0.00  0.00
(재)한국우편사업진흥원       12.64  ...     5.56  11.19  14.69  10.45   8.40  2.51
(재)한국형수치예보모델개발사업단   3.80  ...     3.11   3.85   3.68   4.02   0.00  0.00
(재)한식진흥원            1.91  ...      NaN   2.67   2.15   3.27    NaN   NaN
(주)강원랜드             9.70  ...     4.14  11.16  11.33  10.82   6.47  7.56
(주)워터웨이플러스          3.50  ...     5.00   5.02   5.05   4.90   4.67  4.60
(주)한국가스기술공사        12.90  ...     0.00  14.12  14.33   9.12   1.00  1.00
(주)한국건설관리공사        18.77  ...     1.20  19.19  19.59   2.63   2.24  2.52
88관광개발(주)          14.70  ...      NaN  19.00  13.00   6.00    NaN   NaN
IOM이민정책연구원          3.22  ...     0.33   3.72   4.60   3.24   1.33  0.00
KDI국제정책대학원          9.70  ...     5.46  10.96  10.59  12.18   6.46  6.46
가축위생방역지원본부          7.60  ...     4.00   8.70   8.30   9.10   0.00  0.00
강릉원주대학교치과병원        11.00  ...     4.00  12.00  15.00  10.00   5.00  1.00
강원대학교병원             7.10  ...     2.59   7.53   8.11   7.21   2.64  2.83
건강보험심사평가원          13.10  ...     1.65  11.12  13.94  10.22   1.76  2.00
건설근로자공제회            7.02  ...     0.25   7.32   8.44   4.33   1.07  1.05
건축도시공간연구소           5.60  ...     3.29   6.07   6.09   6.05   5.13  6.10
게임물관리위원회            0.92  ...     1.21   3.49   3.75   2.59   2.89  2.98
경북대학교병원            11.18  ...     4.13  12.80  14.63  11.87   5.00  6.80
경북대학교치과병원           0.00  ...      NaN   6.72   6.14   7.41    NaN   NaN
...                  ...  ...      ...    ...    ...    ...    ...   ...
한국체육산업개발(주)        16.34  ...     8.69  18.75  19.32  12.59   1.90  1.57
한국출판문화산업진흥원        11.70  ...     1.84  13.11  15.21   9.90   2.79  3.29
한국콘텐츠진흥원            4.74  ...     2.05   6.44   7.28   5.19   3.36  3.83
한국토지주택공사           17.60  ...     1.27  18.70  19.67  14.48   1.52  2.11
한국투자공사              4.04  ...     1.82   4.80   4.89   4.56   2.49  3.04
한국특허전략개발원           4.27  ...     1.28   4.83   5.33   4.07   2.12  1.96
한국특허정보원             9.12  ...     2.87   9.33   8.89  10.18   4.12  5.11
한국표준과학연구원          16.10  ...     4.10  17.01  17.79  10.39   5.10  5.10
한국학중앙연구원           11.19  ...     3.08  11.57  11.89  10.93   2.85  2.64
한국한의학연구원            7.02  ...     6.09   9.04   9.05   9.02   6.88  6.73
한국항공우주연구원          11.96  ...     0.49  13.47  13.50  13.50   3.42  2.93
한국항로표지기술원           7.08  ...     3.60   8.60   8.30   9.90   1.00  1.00
한국해양과학기술원          13.96  ...     5.35  14.96  15.11  14.01   6.57  7.38
한국해양수산개발원          13.66  ...    12.43  12.23  14.15   7.76  11.00  8.00
한국해양수산연수원          18.12  ...     6.01  11.10  11.02  15.04   4.10  1.02
한국해양조사협회            4.20  ...     0.00   5.49   5.20   6.63   0.00  0.00
한국행정연구원             9.21  ...     1.88  10.04  10.54   8.86   1.33  0.59
한국형사정책연구원          10.70  ...     5.25  11.02  11.89  10.09   5.75  5.38
한국화학연구원            16.20  ...     1.02  16.71  17.20  14.30   2.00  2.25
한국환경공단             15.60  ...     2.73  13.43  14.78   8.39   4.07  4.22
한국환경산업기술원           6.76  ...     4.27   7.37   7.91   6.28   4.87  4.35
한국환경정책평가연구원        10.06  ...     8.16  10.50  11.15   9.31   7.38  5.21
한약진흥재단              0.00  ...     7.90   5.01   4.78   5.35   4.38  3.12
한전KDN              14.49  ...     9.30  15.25  15.98   9.18   7.41  7.35
한전KPS(주)           16.50  ...     4.50  15.90  16.30   6.40   5.30  5.20
한전원자력연료주식회사        13.12  ...      NaN  14.03  14.23  10.89    NaN   NaN
항공안전기술원             1.52  ...     0.00   2.22   2.34   1.89   1.00  1.00
해양수산과학기술진흥원         4.58  ...     1.99   6.73   7.27   5.71   5.00  7.01
해양환경공단             10.09  ...      NaN  12.03  12.28  10.21    NaN   NaN
환경보전협회             12.10  ...     4.54  10.00  10.76   7.82   4.54  4.64


항목                 무기_여성 정규직_전체 정규직_남성 정규직_여성
기관명
(사)남북교류협력지원협회       1.36   6.99   7.51   5.76
(재)APEC기후센터          NaN   5.67   5.61   5.74
(재)국제원산지정보원         0.00   5.56   5.59   5.51
(재)예술경영지원센터         2.60   5.60   5.60   5.60
(재)우체국금융개발원         6.60  12.11  13.29   9.44
(재)우체국물류지원단         3.27  19.54  19.73  11.73
(재)우체국시설관리단         7.68   9.60  10.10   7.44
(재)일제강제동원피해자지원재단    0.97   2.66   3.58   1.97
(재)정동극장             4.71   8.58  11.13   4.33
(재)중소기업연구원          0.00   7.57   7.89   6.93
(재)한국스마트그리드사업단      0.00   4.67   4.93   4.00
(재)한국우편사업진흥원        5.68  11.20  14.71  10.47
(재)한국형수치예보모델개발사업단   0.00   0.00   0.00   0.00
(재)한식진흥원             NaN   3.67   3.15   4.27
(주)강원랜드             4.83  11.97  12.20  11.45
(주)워터웨이플러스          5.00   5.02   5.05   4.90
(주)한국가스기술공사         1.00  15.12  15.33  10.12
(주)한국건설관리공사         1.13  19.44  19.84   2.88
88관광개발(주)            NaN  19.00  13.00   6.00
IOM이민정책연구원          1.33   4.72   5.60   4.24
KDI국제정책대학원          6.46  11.96  11.59  13.18
가축위생방역지원본부          0.00   0.00   0.00   0.00
강릉원주대학교치과병원         4.00  13.00  16.00  11.00
강원대학교병원             2.59   7.53   8.11   7.21
건강보험심사평가원           1.60  11.15  13.77  10.32
건설근로자공제회            1.08   6.24   8.42   3.22
건축도시공간연구소           4.29   7.07   7.09   7.05
게임물관리위원회            2.21   4.49   4.75   3.59
경북대학교병원             4.33  13.10  14.80  12.11
경북대학교치과병원            NaN   7.26   6.71   7.94
...                  ...    ...    ...    ...
한국체육산업개발(주)         2.37  17.43  18.07  11.00
한국출판문화산업진흥원         2.71  14.20  16.26  10.81
한국콘텐츠진흥원            3.05   7.44   8.28   6.19
한국토지주택공사            1.22  17.80  18.90  13.35
한국투자공사              2.27   5.76   5.86   5.51
한국특허전략개발원           2.28   5.83   6.33   5.07
한국특허정보원             3.50  10.12   9.79  10.74
한국표준과학연구원           5.10  17.01  17.79  10.39
한국학중앙연구원            3.01  10.16  10.59   9.37
한국한의학연구원            7.09   9.82   9.85   9.76
한국항공우주연구원           0.49  13.47  13.00  14.00
한국항로표지기술원           1.00  10.00   9.80  10.90
한국해양과학기술원           5.35  14.96  15.11  14.01
한국해양수산개발원          13.00  13.00  15.00   8.00
한국해양수산연수원           6.01  12.10  12.01  16.04
한국해양조사협회            0.00   0.00   0.00   0.00
한국행정연구원             1.89   9.94  10.29   8.88
한국형사정책연구원           6.25  12.02  12.89  11.09
한국화학연구원             1.69  16.75  17.28  14.20
한국환경공단              3.73  14.43  15.78   9.39
한국환경산업기술원           5.27   8.37   8.91   7.28
한국환경정책평가연구원         8.56  10.84  11.35   9.60
한약진흥재단              8.00   4.83   4.85   4.80
한전KDN               8.79  14.79  15.74   8.10
한전KPS(주)            5.50  16.90  17.30   7.40
한전원자력연료주식회사          NaN  14.03  14.23  10.89
항공안전기술원             1.00   3.22   3.34   2.89
해양수산과학기술진흥원         2.99   7.57   7.93   6.87
해양환경공단               NaN  12.38  12.71  10.21
환경보전협회              4.23  10.01  10.67   8.16

[361 rows x 36 columns]

In [30]:
for y in col_year:
    df_pay_pivot_lasting[(y, '무기_근속연수_격차')] = df_pay_pivot_lasting[(y, '정규직_전체')] - df_pay_pivot_lasting[(y, '무기_전체')]
    df_pay_pivot_lasting[(y, '여성_근속연수_격차')] = df_pay_pivot_lasting[(y, '정규직_남성')] - df_pay_pivot_lasting[(y, '정규직_여성')]

df_pay_pivot_lasting.head()
# df_pay_pivot_woman.sort_values(('2018', '여성 비율'), ascending=True)

               2013                                   2014                     \
항목            무기_전체 무기_남성 무기_여성 정규직_전체 정규직_남성 정규직_여성 무기_전체 무기_남성 무기_여성 정규직_전체
기관명
(사)남북교류협력지원협회  0.00   0.0   0.0   3.37    0.0    0.0  0.00   0.0   0.0   3.93
(재)APEC기후센터     NaN   NaN   NaN   2.38    0.0    0.0   NaN   NaN   NaN   2.76
(재)국제원산지정보원    1.00   0.0   0.0   2.20    0.0    0.0  2.00   0.0   0.0   2.80
(재)예술경영지원센터    0.00   0.0   0.0   5.20    0.0    0.0  2.30   0.0   0.0   3.90
(재)우체국금융개발원    6.43   0.0   0.0  10.70    0.0    0.0  6.58   0.0   0.0  11.50

                 ...                                 2015             \
항목               ...     무기_근속연수_격차 여성_근속연수_격차 무기_근속연수_격차 여성_근속연수_격차
기관명              ...
(사)남북교류협력지원협회    ...           3.93        0.0       4.37        0.0
(재)APEC기후센터      ...            NaN        0.0        NaN        0.0
(재)국제원산지정보원      ...           0.80        0.0       0.20        0.0
(재)예술경영지원센터      ...           1.60        0.0       1.60        0.0
(재)우체국금융개발원      ...           4.92        0.0       6.50        0.0

                    2016                  2017                  2018  \
항목            무기_근속연수_격차 여성_근속연수_격차 무기_근속연수_격차 여성_근속연수_격차 무기_근속연수_격차
기관명
(사)남북교류협력지원협회       4.77        0.0       5.93       1.54       5.13
(재)APEC기후센터          NaN        0.0        NaN      -0.24        NaN
(재)국제원산지정보원         3.54        0.0       4.56       0.08       5.56
(재)예술경영지원센터         2.40        0.0       2.20       0.00       3.00
(재)우체국금융개발원         5.85        0.0       5.52       3.85       5.52


항목            여성_근속연수_격차
기관명
(사)남북교류협력지원협회       1.75
(재)APEC기후센터        -0.13
(재)국제원산지정보원         0.08
(재)예술경영지원센터         0.00
(재)우체국금융개발원         3.85

[5 rows x 48 columns]

## **#무기계약직 근속연수 랭킹**

In [31]:
'''
한국나노기술원: 정규직 평근근속연수가 0이다. 입력을 안한듯. 예외처리 필요.
'''
idx_remove_nano = df_pay_pivot_lasting.index != '한국나노기술원'
year = '2018'
col_lasting = [(year, '정규직_전체'), (year, '무기_전체'), (year, '무기_근속연수_격차'),
               (year, '정규직_남성'), (year, '정규직_여성'), (year, '여성_근속연수_격차')]
df_pay_pivot_lasting.loc[idx_remove_nano, col_lasting].sort_values(('2018', '무기_근속연수_격차'), ascending=True)

                    2018
항목                정규직_전체  무기_전체 무기_근속연수_격차 정규직_남성 정규직_여성 여성_근속연수_격차
기관명
통일연구원              11.00  16.30      -5.30  11.00  10.90       0.10
인천항만공사              8.36  11.82      -3.46   8.73   7.19       1.54
국제방송교류재단           13.60  16.60      -3.00  15.10  10.20       4.90
울산항만공사              6.30   8.00      -1.70   7.30   4.60       2.70
한국저작권보호원            3.27   4.73      -1.46   3.38   2.93       0.45
한국보육진흥원             4.15   5.32      -1.17   4.29   4.13       0.16
대구경북과학기술원           6.53   7.25      -0.72   6.99   4.61       2.38
한국건강가정진흥원           3.50   3.90      -0.40   3.60   3.50       0.10
한국뇌연구원              2.40   2.75      -0.35   2.87   1.13       1.74
서민금융진흥원             2.05   2.19      -0.14   2.07   2.02       0.05
국립박물관문화재단           0.00   0.00       0.00   0.00   0.00       0.00
예금보험공사              0.00   0.00       0.00   0.00   0.00       0.00
국립암센터               0.00   0.00       0.00   0.00   0.00       0.00
국립중앙의료원             0.00   0.00       0.00   0.00   0.00       0.00
한국전력공사              0.00   0.00       0.00   0.00   0.00       0.00
국립생태원               0.00   0.00       0.00   0.00   0.00       0.00
가축위생방역지원본부          0.00   0.00       0.00   0.00   0.00       0.00
대한법률구조공단            0.00   0.00       0.00   0.00   0.00       0.00
한국공정거래조정원           0.00   0.00       0.00   0.00   0.00       0.00
서울올림픽기념국민체육진흥공단     0.00   0.00       0.00   0.00   0.00       0.00
한국해양조사협회            0.00   0.00       0.00   0.00   0.00       0.00
(재)한국형수치예보모델개발사업단   0.00   0.00       0.00   0.00   0.00       0.00
대한석탄공사              0.00   0.00       0.00   0.00   0.00       0.00
대한적십자사              0.00   0.00       0.00   0.00   0.00       0.00
한국산업인력공단            0.00   0.00       0.00   0.00   0.00       0.00
선박안전기술공단            0.00   0.00       0.00   0.00   0.00       0.00
태권도진흥재단             5.20   4.90       0.30   5.30   5.00       0.30
한국벤처투자              4.38   4.08       0.30   4.64   3.69       0.95
(주)워터웨이플러스          5.02   4.67       0.35   5.05   4.90       0.15
국가과학기술연구회           4.16   3.79       0.37   4.25   3.92       0.33
...                  ...    ...        ...    ...    ...        ...
주택도시보증공사           11.15    NaN        NaN   0.00   0.00       0.00
중소기업유통센터           12.45    NaN        NaN  12.96  11.43       1.53
코레일테크(주)           10.00    NaN        NaN  10.43   8.54       1.89
한국가스공사              0.00    NaN        NaN   0.00   0.00       0.00
한국건설기술연구원          16.63    NaN        NaN  17.09  14.06       3.03
한국과학영재학교            7.82    NaN        NaN   7.97   7.63       0.34
한국국제보건의료재단          4.44    NaN        NaN   6.52   4.70       1.82
한국노동연구원            16.70    NaN        NaN  16.66  16.78      -0.12
한국동서발전(주)          16.37    NaN        NaN  17.28   9.82       7.46
한국디자인진흥원           12.00    NaN        NaN  14.70   7.70       7.00
한국방송광고진흥공사         19.07    NaN        NaN  19.98  17.03       2.95
한국서부발전(주)          15.04    NaN        NaN  15.97   8.13       7.84
한국석유관리원             0.00    NaN        NaN   0.00   0.00       0.00
한국수목원관리원            1.24    NaN        NaN   1.25   1.23       0.02
한국여성인권진흥원            NaN   5.64        NaN    NaN    NaN        NaN
한국예술인복지재단           4.92    NaN        NaN   2.88   2.05       0.83
한국원자력연구원           17.04    NaN        NaN  17.54  12.09       5.45
한국잡월드               5.31    NaN        NaN   5.21   5.43      -0.22
한국장애인고용공단          11.78    NaN        NaN  13.35   9.64       3.71
한국재정정보원             2.00    NaN        NaN   2.07   1.78       0.29
한국전기연구원            18.10    NaN        NaN  19.30   7.90      11.40
한국전력거래소            16.16    NaN        NaN  17.13   9.94       7.19
한국전력국제원자력대학원대학교     5.96    NaN        NaN   6.12   5.45       0.67
한국전자통신연구원          17.86    NaN        NaN  17.83  18.13      -0.30
한국조폐공사             22.17    NaN        NaN  21.62  24.20      -2.58
한국중부발전(주)          16.49    NaN        NaN  17.34   9.85       7.49
한국철도공사             20.26    NaN        NaN  20.83  14.95       5.88
한국철도기술연구원          13.88    NaN        NaN  14.39   8.16       6.23
한전원자력연료주식회사        14.03    NaN        NaN  14.23  10.89       3.34
해양환경공단             12.38    NaN        NaN  12.71  10.21       2.50

[360 rows x 6 columns]

## **#정규직 근속연수**

In [32]:
# year = '2018'
# col_lasting = [(year, '정규직_전체'), (year, '무기_전체'), (year, '무기_근속연수_격차'),
#                (year, '정규직_남성'), (year, '정규직_여성'), (year, '여성_근속연수_격차')]
# df_pay_pivot_lasting.loc[::, col_lasting].sort_values(('2018', '정규직_전체'), ascending=False).head(20)
exp_lasting_regular = df_pay_pivot_lasting.loc[::, [('2018', '정규직_전체')]].sort_values(('2018', '정규직_전체'), ascending=False); exp_lasting_regular
exp_lasting_regular.columns = exp_lasting_regular.columns.droplevel(0); exp_lasting_regular
exp_lasting_regular.rename(columns={'정규직_전체': '평균근속연수'}, inplace=True); exp_lasting_regular
exp_lasting_regular.reset_index(inplace=True); exp_lasting_regular

exp_lasting_regular

항목                 기관명  평균근속연수
0               한국조폐공사   22.17
1             한국세라믹기술원   21.91
2            한국기술교육대학교   21.14
3            학교법인한국폴리텍   21.10
4               한국철도공사   20.26
5             한국국토정보공사   19.86
6          (재)우체국물류지원단   19.54
7              국방기술품질원   19.47
8          (주)한국건설관리공사   19.44
9               한국관광공사   19.35
10          한국방송광고진흥공사   19.07
11           88관광개발(주)   19.00
12             한국농어촌공사   18.70
13            한국철도시설공단   18.17
14              기술보증기금   18.13
15             한국전기연구원   18.10
16               대한체육회   17.94
17            국민건강보험공단   17.92
18           한국전자통신연구원   17.86
19          한국전력기술주식회사   17.83
20            한국토지주택공사   17.80
21         한국체육산업개발(주)   17.43
22              도로교통공단   17.30
23             공무원연금공단   17.15
24            한국원자력연구원   17.04
25           한국표준과학연구원   17.01
26            한전KPS(주)   16.90
27            한국시설안전공단   16.87
28            한국가스안전공사   16.84
29            한국전기안전공사   16.81
..                 ...     ...
331         국립낙동강생물자원관    2.24
332           주식회사 에스알    2.09
333            서민금융진흥원    2.05
334            한국재정정보원    2.00
335              서울요양원    1.91
336     재단법인 한국장기조직기증원    1.72
337          한국산림복지진흥원    1.66
338           한국수목원관리원    1.24
339     재단법인 의료기관평가인증원    0.00
340    서울올림픽기념국민체육진흥공단    0.00
341             대한석탄공사    0.00
342            한국석유관리원    0.00
343           선박안전기술공단    0.00
344          한국공정거래조정원    0.00
345           한국산업인력공단    0.00
346             대한적십자사    0.00
347            한국나노기술원    0.00
348  (재)한국형수치예보모델개발사업단    0.00
349             한국가스공사    0.00
350             예금보험공사    0.00
351           대한법률구조공단    0.00
352         가축위생방역지원본부    0.00
353            국립중앙의료원    0.00
354             한국전력공사    0.00
355              국립암센터    0.00
356              국립생태원    0.00
357          주택관리공단(주)    0.00
358          국립박물관문화재단    0.00
359           한국해양조사협회    0.00
360          한국여성인권진흥원     NaN

[361 rows x 2 columns]

## Export: exp_lasting_regular

In [33]:
# exp_lasting_regular.head(15).to_csv(data_directory+'lasting_regular.tsv', sep='\t', index=False)

## **#여성 근속연수 랭킹**

In [34]:
'''
한국여성인권진흥원: 정규직 보수 데이터가 없음, 근속연수 데이터도 없음 => nan
'''
df_pay_pivot_lasting.loc[idx_remove_nano, col_lasting].sort_values(('2018', '여성_근속연수_격차'), ascending=False)

                     2018
항목                 정규직_전체  무기_전체 무기_근속연수_격차 정규직_남성 정규직_여성 여성_근속연수_격차
기관명
(주)한국건설관리공사         19.44   2.24      17.20  19.84   2.88      16.96
영화진흥위원회             16.11   7.39       8.72  19.32   7.32      12.00
영상물등급위원회            13.47    NaN        NaN  17.85   6.17      11.68
축산물품질평가원            15.79   3.89      11.90  18.49   7.07      11.42
한국전기연구원             18.10    NaN        NaN  19.30   7.90      11.40
기술보증기금              18.13   7.68      10.45  19.83   9.74      10.09
한국농수산식품유통공사         14.55   4.70       9.85  17.79   7.71      10.08
한전KPS(주)            16.90   5.30      11.60  17.30   7.40       9.90
한국주택금융공사            12.50   3.59       8.91  15.80   6.42       9.38
한국기술교육대학교           21.14   7.85      13.29  23.47  14.15       9.32
한국공항공사              16.10   1.43      14.67  17.13   8.26       8.87
국민건강보험공단            17.92   0.17      17.75  21.86  13.18       8.68
한국도로공사              16.26  11.22       5.04  17.00   8.41       8.59
한국마사회               16.41   5.48      10.93  17.73   9.18       8.55
한국장학재단              12.42   4.32       8.10  15.51   7.04       8.47
신용보증기금              16.54  11.64       4.90  18.44  10.12       8.32
한국철도시설공단            18.17   9.83       8.34  19.44  11.13       8.31
(재)우체국물류지원단         19.54   3.77      15.77  19.73  11.73       8.00
한국서부발전(주)           15.04    NaN        NaN  15.97   8.13       7.84
한국예탁결제원             16.54   0.00      16.54  18.62  10.83       7.79
한전KDN               14.79   7.41       7.38  15.74   8.10       7.64
한국중부발전(주)           16.49    NaN        NaN  17.34   9.85       7.49
한국동서발전(주)           16.37    NaN        NaN  17.28   9.82       7.46
한국국토정보공사            19.86   3.38      16.48  20.72  13.31       7.41
한국표준과학연구원           17.01   5.10      11.91  17.79  10.39       7.40
재료연구소               15.75   4.06      11.69  16.30   8.99       7.31
한국남부발전(주)           15.59   0.00      15.59  16.41   9.11       7.30
한국전력거래소             16.16    NaN        NaN  17.13   9.94       7.19
한국체육산업개발(주)         17.43   1.90      15.53  18.07  11.00       7.07
학교법인한국폴리텍           21.10   1.25      19.85  22.38  15.37       7.01
...                   ...    ...        ...    ...    ...        ...
재단법인 한국에너지재단         6.00    NaN        NaN   5.00   5.90      -0.90
한국특허정보원             10.12   4.12       6.00   9.79  10.74      -0.95
분당서울대학교병원            5.10   0.88       4.22   4.45   5.41      -0.96
한국지식재산보호원            6.79   2.05       4.74   6.49   7.46      -0.97
한국항공우주연구원           13.47   3.42      10.05  13.00  14.00      -1.00
국립광주과학관              3.51   2.67       0.84   3.09   4.13      -1.04
재단법인 한국여성과학기술인지원센터   3.67   2.02       1.65   2.76   3.83      -1.07
한국항로표지기술원           10.00   1.00       9.00   9.80  10.90      -1.10
(재)한식진흥원             3.67    NaN        NaN   3.15   4.27      -1.12
재외동포재단              12.00   1.00      11.00   9.80  11.00      -1.20
경북대학교치과병원            7.26    NaN        NaN   6.71   7.94      -1.23
재단법인 국악방송            6.41   0.50       5.91   5.90   7.14      -1.24
한국건강증진개발원            3.40   2.43       0.97   2.43   3.72      -1.29
KDI국제정책대학원          11.96   6.46       5.50  11.59  13.18      -1.59
서울대학교병원             10.39   4.45       5.94   9.23  10.87      -1.64
한국지식재산연구원            7.80   3.52       4.28   7.02   8.71      -1.69
한국개발연구원             12.65   1.00      11.65  11.91  13.63      -1.72
충남대학교병원             11.56   3.81       7.75  10.70  12.42      -1.72
국가수리과학연구소            6.42    NaN        NaN   6.04   7.86      -1.82
전쟁기념사업회             13.20   7.10       6.10  12.60  14.70      -2.10
한국고전번역원             12.05   3.46       8.59  11.49  13.67      -2.18
한국법제연구원              8.66   3.20       5.46   7.69   9.89      -2.20
서울대학교치과병원           10.83   5.11       5.72   9.58  12.09      -2.51
한국조폐공사              22.17    NaN        NaN  21.62  24.20      -2.58
광주과학기술원             11.37   9.30       2.07  10.97  13.62      -2.65
한국세라믹기술원            21.91   2.26      19.65  21.51  25.16      -3.65
한국양성평등교육진흥원          7.47   4.04       3.43   5.18   9.04      -3.86
재단법인 대한건설기계안전관리원    12.81   3.29       9.52  11.77  15.66      -3.89
한국해양수산연수원           12.10   4.10       8.00  12.01  16.04      -4.03
한국여성인권진흥원             NaN   5.64        NaN    NaN    NaN        NaN

[360 rows x 6 columns]

# 인턴

## Load Data: df_rcrt

In [35]:
tmp = get_df_from_file(file_names[4]); tmp.head(30)  # 신입정규직
tmp2 = get_df_from_file(file_names[5]); tmp2.head(20)  # 인턴
df_rcrt = tmp.append(tmp2)

df_rcrt = df_rcrt.append(df_emp.loc[df_emp['항목'] == '임직원수 > 임직원 총계'])
df_rcrt['항목'] = df_rcrt['항목'].apply(str.strip)
df_rcrt['항목'] = df_rcrt['항목'].str.replace('신규채용 및 유연근무 현황 > ', '')
df_rcrt['항목'] = df_rcrt['항목'].str.replace('> ', '')
df_rcrt['항목'] = df_rcrt['항목'].str.replace(' ', '_')

df_rcrt['부설기관여부'] = df_rcrt['부설기관여부'].str.strip()

del tmp, tmp2

pd.set_option('display.max_colwidth', -1)
df_rcrt.loc[df_rcrt['기관명']=='(사)남북교류협력지원협회']

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,4.0,3.0,11.0,4.0,1.0,4.00,명,N
1,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_시간선택제(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
2,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_시간선택제(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
3,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_청년,3.0,1.0,10.0,0.0,0.0,4.00,명,N
4,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_여성,0.0,0.0,9.0,0.0,0.0,2.00,명,N
5,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
6,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,0.0,2.0,2.0,0.0,0.00,명,N
7,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_이전지역_지역인재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
8,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_고졸_인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
9,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_무기계약직_무기계약직_신규채용,0.0,0.0,0.0,0.0,0.0,0.00,명,N
0,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,1.0,2.0,1.0,1.0,2.0,2.00,명,N
1,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_여성,0.0,1.0,1.0,1.0,2.0,2.00,명,N
2,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
3,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_비수도권_지역인재,1.0,0.0,1.0,1.0,0.0,1.00,명,N
4,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_이전지역지역이재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
5,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_고졸인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
6,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.00,명,N
7,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_여성,0.0,0.0,0.0,0.0,0.0,0.00,명,N
8,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
9,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_비수도권_지역인재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
10,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_이전지역지역이재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
11,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_고졸인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
12,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_채용(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
13,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_채용(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
14,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_전환(인원수),0.0,0.0,0.0,0.0,1.0,1.00,명,N
15,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_전환(전일제_환산),0.0,0.0,0.0,0.0,0.5,0.75,명,N
16,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_채용(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
17,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_채용(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
18,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_전환(인원수),0.0,0.0,0.0,0.0,1.0,1.00,명,N
19,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_전환(전일제_환산),0.0,0.0,0.0,0.0,0.5,0.75,명,N
20,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_시차_출퇴근형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
21,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_근무시간_선택형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
22,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_집약_근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
23,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_재량_근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
24,(사)남북교류협력지원협회,기타공공기관,유연근무현황_원격근무제(전체)_재택근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
25,(사)남북교류협력지원협회,기타공공기관,유연근무현황_원격근무제(전체)_스마트워크근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
33,(사)남북교류협력지원협회,기타공공기관,임직원수_임직원_총계,26.0,26.0,26.0,26.0,29.0,29.00,명,N

In [36]:
'''
임직원수_임직원_총계

청년인턴_채용현황_체험형_총인턴채용
청년인턴_채용현황_채용형_총인턴채용

신규채용_현황_정규직_정규직_총_신규채용
신규채용_현황_정규직_여성
신규채용_현황_정규직_비수도권_지역인재
'''
df_rcrt.sort_values(['기관명', '항목']).head(40)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
9,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_무기계약직_무기계약직_신규채용,0.0,0.0,0.0,0.0,0.0,0.00,명,N
8,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_고졸_인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
6,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,0.0,2.0,2.0,0.0,0.00,명,N
1,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_시간선택제(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
2,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_시간선택제(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
4,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_여성,0.0,0.0,9.0,0.0,0.0,2.00,명,N
7,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_이전지역_지역인재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
5,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
0,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,4.0,3.0,11.0,4.0,1.0,4.00,명,N
3,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_청년,3.0,1.0,10.0,0.0,0.0,4.00,명,N
14,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_전환(인원수),0.0,0.0,0.0,0.0,1.0,1.00,명,N
15,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_전환(전일제_환산),0.0,0.0,0.0,0.0,0.5,0.75,명,N
12,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_채용(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
13,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직+비정규직_채용(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
18,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_전환(인원수),0.0,0.0,0.0,0.0,1.0,1.00,명,N
19,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_전환(전일제_환산),0.0,0.0,0.0,0.0,0.5,0.75,명,N
16,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_채용(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
17,(사)남북교류협력지원협회,기타공공기관,유연근무현황_시간선택제_정규직+무기계약직_채용(전일제_환산),0.0,0.0,0.0,0.0,0.0,0.00,명,N
25,(사)남북교류협력지원협회,기타공공기관,유연근무현황_원격근무제(전체)_스마트워크근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
24,(사)남북교류협력지원협회,기타공공기관,유연근무현황_원격근무제(전체)_재택근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
21,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_근무시간_선택형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
20,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_시차_출퇴근형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
23,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_재량_근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
22,(사)남북교류협력지원협회,기타공공기관,유연근무현황_탄력근무제(전체)_집약_근무형(인원수),0.0,0.0,0.0,0.0,0.0,0.00,명,N
33,(사)남북교류협력지원협회,기타공공기관,임직원수_임직원_총계,26.0,26.0,26.0,26.0,29.0,29.00,명,N
11,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_고졸인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
9,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_비수도권_지역인재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
7,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_여성,0.0,0.0,0.0,0.0,0.0,0.00,명,N
10,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_이전지역지역이재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
8,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
6,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.00,명,N
5,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_고졸인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
3,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_비수도권_지역인재,1.0,0.0,1.0,1.0,0.0,1.00,명,N
1,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_여성,0.0,1.0,1.0,1.0,2.0,2.00,명,N
4,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_이전지역지역이재,0.0,0.0,0.0,0.0,0.0,0.00,명,N
2,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_장애인,0.0,0.0,0.0,0.0,0.0,0.00,명,N
0,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,1.0,2.0,1.0,1.0,2.0,2.00,명,N
19,(재)APEC기후센터,기타공공기관,신규채용_현황_무기계약직_무기계약직_신규채용,0.0,0.0,0.0,0.0,0.0,0.00,명,N
18,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_고졸_인력,0.0,0.0,0.0,0.0,0.0,0.00,명,N
16,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,7.0,5.0,6.0,3.0,3.0,2.00,명,N

## Index, Columns

In [37]:
idx_rcrt_all = df_rcrt['항목'] == '임직원수_임직원_총계'
idx_intern_good = df_rcrt['항목'] == '청년인턴_채용현황_채용형_총인턴채용'
idx_intern_bad = df_rcrt['항목'] == '청년인턴_채용현황_체험형_총인턴채용'

idx_rcrt_total = df_rcrt['항목'] == '신규채용_현황_정규직_정규직_총_신규채용'
idx_rcrt_woman = df_rcrt['항목'] == '신규채용_현황_정규직_여성'
idx_rcrt_region = df_rcrt['항목'] == '신규채용_현황_정규직_비수도권_지역인재'

idx_rcrt = idx_rcrt_all | idx_intern_good | idx_intern_bad | idx_rcrt_total | idx_rcrt_woman | idx_rcrt_region

In [38]:
df_rcrt.loc[idx_intern_good | idx_intern_bad]

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,1.0,2.0,1.0,1.0,2.0,2.0,명,N
6,(사)남북교류협력지원협회,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
26,(재)APEC기후센터,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
32,(재)APEC기후센터,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
52,(재)국제원산지정보원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,3.0,6.0,0.0,0.0,0.0,0.0,명,N
58,(재)국제원산지정보원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
78,(재)예술경영지원센터,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,3.0,0.0,0.0,3.0,8.0,9.0,명,N
84,(재)예술경영지원센터,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
104,(재)우체국금융개발원,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,8.0,10.0,15.0,27.0,26.0,15.0,명,N
110,(재)우체국금융개발원,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,3.0,0.0,명,N
130,(재)우체국물류지원단,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,4.0,6.0,7.0,9.0,12.0,6.0,명,N
136,(재)우체국물류지원단,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
156,(재)우체국시설관리단,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,1.0,4.0,3.0,3.0,2.0,3.0,명,N
162,(재)우체국시설관리단,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,1.0,0.0,명,N
182,(재)일제강제동원피해자지원재단,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
188,(재)일제강제동원피해자지원재단,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
208,(재)정동극장,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,4.0,3.0,3.0,6.0,3.0,0.0,명,N
214,(재)정동극장,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
234,(재)중소기업연구원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,12.0,13.0,9.0,9.0,12.0,5.0,명,N
240,(재)중소기업연구원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
260,(재)한국스마트그리드사업단,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
266,(재)한국스마트그리드사업단,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,7.0,0.0,0.0,명,N
286,(재)한국우편사업진흥원,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,7.0,8.0,4.0,5.0,5.0,0.0,명,N
292,(재)한국우편사업진흥원,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,3.0,3.0,6.0,0.0,명,N
312,(재)한국형수치예보모델개발사업단,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
318,(재)한국형수치예보모델개발사업단,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
338,(재)한식진흥원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,2.0,1.0,0.0,0.0,1.0,2.0,명,N
344,(재)한식진흥원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
364,(주)강원랜드,공기업(시장형),청년인턴_채용현황_체험형_총인턴채용,0.0,29.0,0.0,0.0,0.0,0.0,명,N
370,(주)강원랜드,공기업(시장형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,30.0,57.0,224.0,명,N
...,...,...,...,...,...,...,...,...,...,...,...
8944,한국해양조사협회,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,3.0,5.0,2.0,명,N
8950,한국해양조사협회,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
8970,한국행정연구원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,17.0,18.0,16.0,10.0,17.0,5.0,명,N
8976,한국행정연구원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
8996,한국형사정책연구원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,16.0,18.0,22.0,25.0,12.0,6.0,명,N
9002,한국형사정책연구원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9022,한국화학연구원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,17.0,20.0,24.0,37.0,124.0,144.0,명,N
9028,한국화학연구원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9048,한국환경공단,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,92.0,108.0,41.0,44.0,31.0,34.0,명,N
9054,한국환경공단,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,102.0,103.0,88.0,95.0,명,N
9074,한국환경산업기술원,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,30.0,20.0,23.0,20.0,39.0,46.0,명,N
9080,한국환경산업기술원,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9100,한국환경정책평가연구원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,15.0,24.0,31.0,18.0,13.0,13.0,명,N
9106,한국환경정책평가연구원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9126,한약진흥재단,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9132,한약진흥재단,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9152,한전KDN,공기업(준시장형),청년인턴_채용현황_체험형_총인턴채용,91.0,102.0,133.0,11.0,32.0,42.0,명,N
9158,한전KDN,공기업(준시장형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,85.0,150.0,148.0,명,N
9178,한전KPS(주),공기업(준시장형),청년인턴_채용현황_체험형_총인턴채용,344.0,377.0,470.0,168.0,257.0,258.0,명,N
9184,한전KPS(주),공기업(준시장형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,63.0,79.0,61.0,명,N
9204,한전원자력연료주식회사,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,78.0,63.0,3.0,5.0,18.0,15.0,명,N
9210,한전원자력연료주식회사,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,80.0,68.0,29.0,0.0,명,N
9230,항공안전기술원,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,5.0,3.0,0.0,0.0,0.0,4.0,명,N
9236,항공안전기술원,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9256,해양수산과학기술진흥원,준정부기관(위탁집행형),청년인턴_채용현황_체험형_총인턴채용,3.0,3.0,3.0,3.0,5.0,4.0,명,N
9262,해양수산과학기술진흥원,준정부기관(위탁집행형),청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9282,해양환경공단,공기업(준시장형),청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,19.0,9.0,26.0,25.0,명,N
9288,해양환경공단,공기업(준시장형),청년인턴_채용현황_채용형_총인턴채용,28.0,22.0,15.0,18.0,10.0,2.0,명,N
9308,환경보전협회,기타공공기관,청년인턴_채용현황_체험형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9314,환경보전협회,기타공공기관,청년인턴_채용현황_채용형_총인턴채용,0.0,0.0,0.0,0.0,0.0,0.0,명,N

In [39]:
df_rcrt.loc[idx_rcrt_total | idx_rcrt_woman | idx_rcrt_region].sort_values(['기관명', '항목'])

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
6,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,0.00,2.00,2.00,0.0,0.0,명,N
4,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_여성,0.0,0.00,9.00,0.00,0.0,2.0,명,N
0,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,4.0,3.00,11.00,4.00,1.0,4.0,명,N
16,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,7.0,5.00,6.00,3.00,3.0,2.0,명,N
14,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_여성,7.0,6.00,11.00,1.00,3.0,3.0,명,N
10,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,15.0,16.00,16.00,9.00,6.0,3.0,명,N
26,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,5.00,0.00,5.0,0.0,명,N
24,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_여성,1.0,3.00,3.00,2.00,5.0,1.0,명,N
20,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,2.0,5.00,10.00,3.00,14.0,3.0,명,N
36,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,3.00,0.00,0.00,0.0,1.0,명,N
34,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_여성,3.0,14.00,0.00,4.00,4.0,1.0,명,N
30,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,3.0,17.00,0.00,7.00,5.0,1.0,명,N
46,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,2.0,9.00,6.00,24.50,11.0,5.0,명,N
44,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_여성,4.0,5.00,11.00,15.50,21.0,7.0,명,N
40,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,9.0,12.00,26.00,49.50,34.0,12.0,명,N
56,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,2.00,12.00,11.0,10.0,명,N
54,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_여성,3.0,0.75,2.75,0.75,1.5,0.0,명,N
50,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,8.0,4.75,4.75,21.75,23.5,16.0,명,N
66,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,4.00,0.00,0.00,3.0,2.0,명,N
64,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_여성,1.0,3.00,3.00,0.00,0.0,0.0,명,N
60,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,1.0,10.00,4.00,1.00,4.0,3.0,명,N
76,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,2.00,5.00,2.00,4.0,3.0,명,N
74,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_여성,0.0,1.00,2.00,1.00,5.0,3.0,명,N
70,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,0.0,6.00,6.00,2.00,9.0,4.0,명,N
86,(재)정동극장,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,0.00,0.00,0.0,0.0,명,N
84,(재)정동극장,기타공공기관,신규채용_현황_정규직_여성,7.0,0.00,2.00,3.00,0.0,0.0,명,N
80,(재)정동극장,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,8.0,5.00,2.00,7.00,0.0,0.0,명,N
96,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,2.0,1.00,2.00,1.00,0.0,0.0,명,N
94,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_여성,1.0,2.00,1.00,4.00,0.0,6.0,명,N
90,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,8.0,6.00,9.00,9.00,0.0,11.0,명,N
...,...,...,...,...,...,...,...,...,...,...,...
3496,한국환경산업기술원,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,13.0,9.00,6.00,14.00,11.0,4.0,명,N
3494,한국환경산업기술원,준정부기관(위탁집행형),신규채용_현황_정규직_여성,13.0,6.50,5.50,16.00,21.0,9.0,명,N
3490,한국환경산업기술원,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,28.0,17.50,18.50,40.00,44.0,16.0,명,N
3506,한국환경정책평가연구원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,0.00,0.00,0.00,0.0,0.0,명,N
3504,한국환경정책평가연구원,기타공공기관,신규채용_현황_정규직_여성,9.0,2.00,10.00,10.00,2.0,1.0,명,N
3500,한국환경정책평가연구원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,19.0,12.00,13.00,24.00,11.0,3.0,명,N
3516,한약진흥재단,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,0.00,0.00,1.00,1.0,3.0,명,N
3514,한약진흥재단,기타공공기관,신규채용_현황_정규직_여성,0.0,0.00,0.00,2.00,5.0,2.0,명,N
3510,한약진흥재단,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,0.0,0.00,0.00,7.00,13.0,7.0,명,N
3526,한전KDN,공기업(준시장형),신규채용_현황_정규직_비수도권_지역인재,13.0,18.50,40.50,39.00,58.0,85.5,명,N
3524,한전KDN,공기업(준시장형),신규채용_현황_정규직_여성,8.0,15.50,18.00,24.00,23.0,42.5,명,N
3520,한전KDN,공기업(준시장형),신규채용_현황_정규직_정규직_총_신규채용,34.0,44.50,77.00,82.00,104.0,132.5,명,N
3536,한전KPS(주),공기업(준시장형),신규채용_현황_정규직_비수도권_지역인재,294.0,187.00,347.00,156.00,183.0,284.0,명,N
3534,한전KPS(주),공기업(준시장형),신규채용_현황_정규직_여성,34.0,21.00,61.00,11.00,25.0,61.0,명,N
3530,한전KPS(주),공기업(준시장형),신규채용_현황_정규직_정규직_총_신규채용,425.0,275.00,557.00,210.00,284.0,374.0,명,N
3546,한전원자력연료주식회사,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,50.0,27.00,42.00,69.00,18.0,1.0,명,N
3544,한전원자력연료주식회사,기타공공기관,신규채용_현황_정규직_여성,8.0,9.00,3.00,7.00,2.0,0.0,명,N
3540,한전원자력연료주식회사,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,88.0,65.00,63.00,110.00,38.0,3.0,명,N
3556,항공안전기술원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,4.0,1.00,2.00,0.00,5.0,1.0,명,N
3554,항공안전기술원,기타공공기관,신규채용_현황_정규직_여성,2.0,1.00,4.00,0.00,6.0,0.0,명,N
3550,항공안전기술원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,14.0,7.00,12.00,4.00,13.0,3.0,명,N
3566,해양수산과학기술진흥원,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,5.0,3.00,3.00,3.00,1.0,2.0,명,N
3564,해양수산과학기술진흥원,준정부기관(위탁집행형),신규채용_현황_정규직_여성,7.0,5.00,3.75,1.00,0.0,2.0,명,N
3560,해양수산과학기술진흥원,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,16.0,11.00,11.75,4.00,3.0,7.0,명,N
3576,해양환경공단,공기업(준시장형),신규채용_현황_정규직_비수도권_지역인재,57.0,27.00,17.50,17.00,32.0,14.0,명,N
3574,해양환경공단,공기업(준시장형),신규채용_현황_정규직_여성,13.0,7.88,6.50,1.00,9.0,4.0,명,N
3570,해양환경공단,공기업(준시장형),신규채용_현황_정규직_정규직_총_신규채용,84.0,38.88,30.50,28.00,50.0,17.0,명,N
3586,환경보전협회,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,4.0,0.00,1.00,1.00,1.0,2.0,명,N
3584,환경보전협회,기타공공기관,신규채용_현황_정규직_여성,2.0,0.00,0.00,0.00,1.0,2.0,명,N
3580,환경보전협회,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,6.0,0.00,2.00,2.00,6.0,5.0,명,N

In [40]:
df_rcrt.loc[idx_rcrt]

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,4.0,3.00,11.00,4.00,1.0,4.0,명,N
4,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_여성,0.0,0.00,9.00,0.00,0.0,2.0,명,N
6,(사)남북교류협력지원협회,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,0.00,2.00,2.00,0.0,0.0,명,N
10,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,15.0,16.00,16.00,9.00,6.0,3.0,명,N
14,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_여성,7.0,6.00,11.00,1.00,3.0,3.0,명,N
16,(재)APEC기후센터,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,7.0,5.00,6.00,3.00,3.0,2.0,명,N
20,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,2.0,5.00,10.00,3.00,14.0,3.0,명,N
24,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_여성,1.0,3.00,3.00,2.00,5.0,1.0,명,N
26,(재)국제원산지정보원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,5.00,0.00,5.0,0.0,명,N
30,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,3.0,17.00,0.00,7.00,5.0,1.0,명,N
34,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_여성,3.0,14.00,0.00,4.00,4.0,1.0,명,N
36,(재)예술경영지원센터,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,3.00,0.00,0.00,0.0,1.0,명,N
40,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,9.0,12.00,26.00,49.50,34.0,12.0,명,N
44,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_여성,4.0,5.00,11.00,15.50,21.0,7.0,명,N
46,(재)우체국금융개발원,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,2.0,9.00,6.00,24.50,11.0,5.0,명,N
50,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_정규직_총_신규채용,8.0,4.75,4.75,21.75,23.5,16.0,명,N
54,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_여성,3.0,0.75,2.75,0.75,1.5,0.0,명,N
56,(재)우체국물류지원단,준정부기관(위탁집행형),신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,2.00,12.00,11.0,10.0,명,N
60,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,1.0,10.00,4.00,1.00,4.0,3.0,명,N
64,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_여성,1.0,3.00,3.00,0.00,0.0,0.0,명,N
66,(재)우체국시설관리단,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,4.00,0.00,0.00,3.0,2.0,명,N
70,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,0.0,6.00,6.00,2.00,9.0,4.0,명,N
74,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_여성,0.0,1.00,2.00,1.00,5.0,3.0,명,N
76,(재)일제강제동원피해자지원재단,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,0.0,2.00,5.00,2.00,4.0,3.0,명,N
80,(재)정동극장,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,8.0,5.00,2.00,7.00,0.0,0.0,명,N
84,(재)정동극장,기타공공기관,신규채용_현황_정규직_여성,7.0,0.00,2.00,3.00,0.0,0.0,명,N
86,(재)정동극장,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,1.0,1.00,0.00,0.00,0.0,0.0,명,N
90,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_정규직_총_신규채용,8.0,6.00,9.00,9.00,0.0,11.0,명,N
94,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_여성,1.0,2.00,1.00,4.00,0.0,6.0,명,N
96,(재)중소기업연구원,기타공공기관,신규채용_현황_정규직_비수도권_지역인재,2.0,1.00,2.00,1.00,0.0,0.0,명,N
...,...,...,...,...,...,...,...,...,...,...,...
12903,한국체육산업개발(주),기타공공기관,임직원수_임직원_총계,821.0,826.00,826.00,477.00,1167.0,1455.0,명,N
12942,한국출판문화산업진흥원,기타공공기관,임직원수_임직원_총계,55.0,62.00,65.00,68.00,92.0,92.0,명,N
12981,한국콘텐츠진흥원,준정부기관(위탁집행형),임직원수_임직원_총계,198.0,186.00,226.00,268.00,317.0,314.0,명,N
13020,한국토지주택공사,공기업(준시장형),임직원수_임직원_총계,6100.0,6418.00,6418.00,6589.00,8251.0,8539.0,명,N
13059,한국투자공사,기타공공기관,임직원수_임직원_총계,146.0,177.00,231.00,243.00,267.0,285.0,명,N
13098,한국특허전략개발원,준정부기관(위탁집행형),임직원수_임직원_총계,81.0,81.00,161.00,161.00,224.0,224.0,명,N
13137,한국특허정보원,기타공공기관,임직원수_임직원_총계,688.0,340.00,368.00,378.00,382.0,382.0,명,N
13176,한국표준과학연구원,기타공공기관,임직원수_임직원_총계,421.0,430.00,436.00,444.00,461.0,464.0,명,N
13215,한국학중앙연구원,기타공공기관,임직원수_임직원_총계,220.0,227.00,227.00,237.00,248.0,271.0,명,N
13254,한국한의학연구원,기타공공기관,임직원수_임직원_총계,152.0,167.00,182.00,185.00,195.0,203.0,명,N
13293,한국항공우주연구원,기타공공기관,임직원수_임직원_총계,754.0,790.00,821.00,855.00,888.0,967.0,명,N
13332,한국항로표지기술원,기타공공기관,임직원수_임직원_총계,48.0,48.00,48.00,48.00,44.0,51.0,명,N
13371,한국해양과학기술원,기타공공기관,임직원수_임직원_총계,505.0,389.00,400.00,442.00,442.0,518.0,명,N
13410,한국해양수산개발원,기타공공기관,임직원수_임직원_총계,136.0,148.00,155.00,155.00,165.0,218.0,명,N
13449,한국해양수산연수원,준정부기관(위탁집행형),임직원수_임직원_총계,149.0,152.00,152.00,162.00,177.0,191.0,명,N
13488,한국해양조사협회,기타공공기관,임직원수_임직원_총계,43.0,45.00,45.00,46.00,46.0,53.0,명,N
13527,한국행정연구원,기타공공기관,임직원수_임직원_총계,60.0,66.00,80.00,84.00,84.0,126.0,명,N
13566,한국형사정책연구원,기타공공기관,임직원수_임직원_총계,58.0,64.00,70.00,72.00,73.0,92.0,명,N
13605,한국화학연구원,기타공공기관,임직원수_임직원_총계,384.0,397.00,419.00,431.00,440.0,583.0,명,N
13644,한국환경공단,준정부기관(위탁집행형),임직원수_임직원_총계,2127.0,2159.00,2219.00,2353.00,2390.0,2749.0,명,N
13683,한국환경산업기술원,준정부기관(위탁집행형),임직원수_임직원_총계,188.0,308.00,321.00,344.00,478.0,514.0,명,N
13722,한국환경정책평가연구원,기타공공기관,임직원수_임직원_총계,147.0,149.00,157.00,176.00,176.0,180.0,명,N
13761,한약진흥재단,기타공공기관,임직원수_임직원_총계,0.0,0.00,0.00,56.00,66.0,139.0,명,N
13800,한전KDN,공기업(준시장형),임직원수_임직원_총계,1846.0,1846.00,2267.00,2392.00,2502.0,2554.0,명,N
13839,한전KPS(주),공기업(준시장형),임직원수_임직원_총계,4877.0,5167.00,5464.00,5718.00,6300.0,6236.0,명,N
13878,한전원자력연료주식회사,기타공공기관,임직원수_임직원_총계,998.0,1070.00,1111.00,1166.00,1178.0,1186.0,명,N
13917,항공안전기술원,기타공공기관,임직원수_임직원_총계,50.0,50.00,36.00,36.00,90.0,92.0,명,N
13956,해양수산과학기술진흥원,준정부기관(위탁집행형),임직원수_임직원_총계,62.0,74.00,74.00,75.00,75.0,80.0,명,N
13995,해양환경공단,공기업(준시장형),임직원수_임직원_총계,570.0,579.00,579.00,594.00,618.0,666.0,명,N
14034,환경보전협회,기타공공기관,임직원수_임직원_총계,251.0,251.00,251.00,251.00,251.0,251.0,명,N

## Pivot

In [41]:
df_rcrt_pivot = df_rcrt.loc[idx_rcrt].pivot(index='기관명', columns='항목', values=col_year)
df_rcrt_pivot.columns.set_levels(['신입_지역인재', '신입_여성', '신입_전체', '직원_전체', '인턴_채용형', '인턴_체험형'], level=1, inplace=True)
df_rcrt_pivot

                     2013                                        2014          \
항목                신입_지역인재  신입_여성  신입_전체   직원_전체 인턴_채용형 인턴_체험형 신입_지역인재   신입_여성
기관명
(사)남북교류협력지원협회      1.0     0.0    4.0    26.0    0.0    1.0    0.0     0.00
(재)APEC기후센터        7.0     7.0    15.0   70.0    0.0    0.0    5.0     6.00
(재)국제원산지정보원        1.0     1.0    2.0    50.0    0.0    3.0    1.0     3.00
(재)예술경영지원센터        0.0     3.0    3.0    25.0    0.0    3.0    3.0     14.00
(재)우체국금융개발원        2.0     4.0    9.0    189.0   0.0    8.0    9.0     5.00
(재)우체국물류지원단        1.0     3.0    8.0    944.0   0.0    4.0    1.0     0.75
(재)우체국시설관리단        0.0     1.0    1.0    1989.0  0.0    1.0    4.0     3.00
(재)일제강제동원피해자지원재단   0.0     0.0    0.0    0.0     0.0    0.0    2.0     1.00
(재)정동극장            1.0     7.0    8.0    63.0    0.0    4.0    1.0     0.00
(재)중소기업연구원         2.0     1.0    8.0    48.0    0.0    12.0   1.0     2.00
(재)한국스마트그리드사업단     0.0     0.0    0.0    28.0    0.0    0.0    2.0     1.00
(재)한국우편사업진흥원       0.0     2.0    6.0    116.0   0.0    7.0    5.0     2.75
(재)한국형수치예보모델개발사업단  5.0     9.0    13.0   58.0    0.0    0.0    2.0     2.00
(재)한식진흥원           0.0     0.0    5.0    9.0     0.0    2.0    1.0     3.00
(주)강원랜드            96.0    43.0   109.0  2906.0  0.0    0.0    116.0   46.00
(주)워터웨이플러스         1.0     3.0    1.0    65.0    0.0    0.0    0.0     0.00
(주)한국가스기술공사        69.0    4.0    106.0  1173.0  0.0    32.0   110.0   13.00
(주)한국건설관리공사        0.0     0.0    0.0    416.0   0.0    0.0    0.0     0.00
88관광개발(주)          0.0     0.0    1.0    48.0    0.0    0.0    0.0     0.00
IOM이민정책연구원         0.0     1.0    2.0    17.0    0.0    0.0    0.0     0.00
KDI국제정책대학원         0.0     1.0    3.0    55.0    0.0    22.0   0.0     2.00
가축위생방역지원본부         2.0     0.0    3.0    462.0   0.0    0.0    4.0     0.00
강릉원주대학교치과병원        18.0    10.0   21.0   190.0   0.0    0.0    18.0    1.00
강원대학교병원            147.0   115.0  162.0  786.0   0.0    16.0   90.0    82.00
건강보험심사평가원          103.0   195.0  222.0  1917.0  0.0    143.0  156.0   254.00
건설근로자공제회           4.0     4.0    8.0    92.0    0.0    0.0    1.0     1.00
건축도시공간연구소          0.0     1.0    2.0    35.0    0.0    26.0   0.0     0.00
게임물관리위원회           0.0     0.0    0.0    75.0    0.0    0.0    1.0     0.00
경북대학교병원            243.0   156.0  250.0  2843.0  0.0    8.0    275.0   179.00
경북대학교치과병원          0.0     0.0    0.0    0.0     0.0    0.0    0.0     0.00
...                ...     ...    ...     ...    ...    ...    ...      ...
한국체육산업개발(주)        0.0     0.0    0.0    821.0   0.0    0.0    2.0     1.00
한국출판문화산업진흥원        3.0     7.0    13.0   55.0    0.0    4.0    1.0     4.00
한국콘텐츠진흥원           2.0     6.0    12.0   198.0   0.0    22.0   5.5     8.50
한국토지주택공사           8.0     13.0   17.0   6100.0  0.0    546.0  2.0     1.00
한국투자공사             2.0     8.0    25.0   146.0   0.0    15.0   2.0     10.00
한국특허전략개발원          0.0     1.0    1.0    81.0    0.0    0.0    0.0     1.00
한국특허정보원            9.0     3.0    15.0   688.0   0.0    5.0    9.0     4.00
한국표준과학연구원          0.0     10.0   34.0   421.0   0.0    11.0   0.0     5.00
한국학중앙연구원           3.0     1.0    8.0    220.0   0.0    16.0   1.0     4.00
한국한의학연구원           0.0     4.0    11.0   152.0   0.0    14.0   0.0     7.00
한국항공우주연구원          0.0     4.0    32.0   754.0   0.0    31.0   0.0     2.00
한국항로표지기술원          3.0     0.0    4.0    48.0    0.0    2.0    2.0     1.00
한국해양과학기술원          7.0     2.0    15.0   505.0   0.0    30.0   2.0     1.00
한국해양수산개발원          0.0     0.0    5.0    136.0   0.0    7.0    0.0     6.00
한국해양수산연수원          8.0     2.0    8.0    149.0   0.0    9.0    15.0    1.00
한국해양조사협회           2.0     1.0    6.0    43.0    0.0    0.0    3.0     0.00
한국행정연구원            0.0     3.0    5.0    60.0    0.0    17.0   0.0     2.00
한국형사정책연구원          0.0     2.0    3.0    58.0    0.0    16.0   0.0     4.00
한국화학연구원            0.0     5.0    28.0   384.0   0.0    17.0   0.0     3.00
한국환경공단             41.0    35.0   89.0   2127.0  0.0    92.0   51.0    40.50
한국환경산업기술원          13.0    13.0   28.0   188.0   0.0    30.0   9.0     6.50
한국환경정책평가연구원        0.0     9.0    19.0   147.0   0.0    15.0   0.0     2.00
한약진흥재단             0.0     0.0    0.0    0.0     0.0    0.0    0.0     0.00
한전KDN              13.0    8.0    34.0   1846.0  0.0    91.0   18.5    15.50
한전KPS(주)           294.0   34.0   425.0  4877.0  0.0    344.0  187.0   21.00
한전원자력연료주식회사        50.0    8.0    88.0   998.0   0.0    78.0   27.0    9.00
항공안전기술원            4.0     2.0    14.0   50.0    0.0    5.0    1.0     1.00
해양수산과학기술진흥원        5.0     7.0    16.0   62.0    0.0    3.0    3.0     5.00
해양환경공단             57.0    13.0   84.0   570.0   28.0   0.0    27.0    7.88
환경보전협회             4.0     2.0    6.0    251.0   0.0    0.0    0.0     0.00

                                   ...      2017                        \
항목                  신입_전체   직원_전체  ...     신입_전체   직원_전체 인턴_채용형 인턴_체험형
기관명                                ...
(사)남북교류협력지원협회      3.00    26.0    ...    1.00    29.0    0.0    2.0
(재)APEC기후센터        16.00   90.0    ...    6.00    90.0    0.0    0.0
(재)국제원산지정보원        5.00    50.0    ...    14.00   50.0    0.0    0.0
(재)예술경영지원센터        17.00   35.0    ...    5.00    53.0    0.0    8.0
(재)우체국금융개발원        12.00   688.0   ...    34.00   723.0   3.0    26.0
(재)우체국물류지원단        4.75    1400.0  ...    23.50   1535.0  0.0    12.0
(재)우체국시설관리단        10.00   2709.0  ...    4.00    2709.0  1.0    2.0
(재)일제강제동원피해자지원재단   6.00    52.0    ...    9.00    37.0    0.0    0.0
(재)정동극장            5.00    66.0    ...    0.00    62.0    0.0    3.0
(재)중소기업연구원         6.00    50.0    ...    0.00    59.0    0.0    12.0
(재)한국스마트그리드사업단     6.00    28.0    ...    4.00    40.0    0.0    0.0
(재)한국우편사업진흥원       9.75    305.0   ...    19.00   279.0   6.0    5.0
(재)한국형수치예보모델개발사업단  8.00    58.0    ...    8.00    60.0    0.0    0.0
(재)한식진흥원           6.00    21.0    ...    11.00   25.0    0.0    1.0
(주)강원랜드            133.00  3243.0  ...    143.00  3680.0  57.0   0.0
(주)워터웨이플러스         0.00    65.0    ...    7.00    70.0    0.0    0.0
(주)한국가스기술공사        147.00  1289.0  ...    84.00   1478.0  95.0   0.0
(주)한국건설관리공사        3.00    416.0   ...    10.00   381.0   0.0    0.0
88관광개발(주)          2.00    48.0    ...    2.00    43.0    0.0    0.0
IOM이민정책연구원         1.00    17.0    ...    4.00    17.0    0.0    0.0
KDI국제정책대학원         9.00    99.0    ...    4.00    101.0   0.0    12.0
가축위생방역지원본부         6.00    504.0   ...    4.00    786.0   0.0    0.0
강릉원주대학교치과병원        18.00   190.0   ...    18.00   193.0   0.0    0.0
강원대학교병원            123.00  967.0   ...    178.00  1123.0  0.0    8.0
건강보험심사평가원          294.00  2117.0  ...    359.00  2790.0  34.0   137.0
건설근로자공제회           5.00    97.0    ...    25.00   150.5   10.0   0.0
건축도시공간연구소          3.00    49.0    ...    2.00    62.0    0.0    7.0
게임물관리위원회           3.00    78.0    ...    3.00    86.0    0.0    3.0
경북대학교병원            283.00  2929.0  ...    362.00  3141.0  0.0    0.0
경북대학교치과병원          0.00    0.0     ...    44.00   168.0   0.0    0.0
...                 ...     ...    ...     ...     ...    ...    ...
한국체육산업개발(주)        7.00    826.0   ...    8.00    1167.0  0.0    0.0
한국출판문화산업진흥원        8.00    62.0    ...    5.75    92.0    0.0    0.0
한국콘텐츠진흥원           20.50   186.0   ...    24.00   317.0   8.0    3.0
한국토지주택공사           5.00    6418.0  ...    531.00  8251.0  201.0  497.0
한국투자공사             34.00   177.0   ...    28.00   267.0   0.0    0.0
한국특허전략개발원          1.00    81.0    ...    4.50    224.0   1.0    6.0
한국특허정보원            24.00   340.0   ...    23.00   382.0   10.0   20.0
한국표준과학연구원          18.00   430.0   ...    13.00   461.0   0.0    0.0
한국학중앙연구원           5.00    227.0   ...    5.00    248.0   0.0    35.0
한국한의학연구원           14.00   167.0   ...    9.00    195.0   0.0    21.0
한국항공우주연구원          51.00   790.0   ...    36.00   888.0   0.0    2.0
한국항로표지기술원          3.00    48.0    ...    1.00    44.0    0.0    0.0
한국해양과학기술원          6.00    389.0   ...    12.00   442.0   0.0    61.0
한국해양수산개발원          18.00   148.0   ...    13.00   165.0   0.0    11.0
한국해양수산연수원          15.00   152.0   ...    9.00    177.0   0.0    9.0
한국해양조사협회           7.00    45.0    ...    3.00    46.0    0.0    5.0
한국행정연구원            7.00    66.0    ...    3.00    84.0    0.0    17.0
한국형사정책연구원          8.00    64.0    ...    2.00    73.0    0.0    12.0
한국화학연구원            29.00   397.0   ...    20.00   440.0   0.0    124.0
한국환경공단             93.00   2159.0  ...    89.00   2390.0  88.0   31.0
한국환경산업기술원          17.50   308.0   ...    44.00   478.0   0.0    39.0
한국환경정책평가연구원        12.00   149.0   ...    11.00   176.0   0.0    13.0
한약진흥재단             0.00    0.0     ...    13.00   66.0    0.0    0.0
한전KDN              44.50   1846.0  ...    104.00  2502.0  150.0  32.0
한전KPS(주)           275.00  5167.0  ...    284.00  6300.0  79.0   257.0
한전원자력연료주식회사        65.00   1070.0  ...    38.00   1178.0  29.0   18.0
항공안전기술원            7.00    50.0    ...    13.00   90.0    0.0    0.0
해양수산과학기술진흥원        11.00   74.0    ...    3.00    75.0    0.0    5.0
해양환경공단             38.88   579.0   ...    50.00   618.0   10.0   26.0
환경보전협회             0.00    251.0   ...    6.00    251.0   0.0    0.0

                     2018
항목                신입_지역인재  신입_여성  신입_전체   직원_전체 인턴_채용형 인턴_체험형
기관명
(사)남북교류협력지원협회      0.0     2.0    4.0    29.0    0.0    2.0
(재)APEC기후센터        2.0     3.0    3.0    90.0    0.0    0.0
(재)국제원산지정보원        0.0     1.0    3.0    50.0    0.0    0.0
(재)예술경영지원센터        1.0     1.0    1.0    69.0    0.0    9.0
(재)우체국금융개발원        5.0     7.0    12.0   748.0   0.0    15.0
(재)우체국물류지원단        10.0    0.0    16.0   1601.5  0.0    6.0
(재)우체국시설관리단        2.0     0.0    3.0    2709.0  0.0    3.0
(재)일제강제동원피해자지원재단   3.0     3.0    4.0    37.0    0.0    0.0
(재)정동극장            0.0     0.0    0.0    61.0    0.0    0.0
(재)중소기업연구원         0.0     6.0    11.0   95.0    0.0    5.0
(재)한국스마트그리드사업단     0.0     0.0    0.0    40.0    0.0    0.0
(재)한국우편사업진흥원       1.0     5.0    10.0   443.0   0.0    0.0
(재)한국형수치예보모델개발사업단  1.0     1.0    3.0    60.0    0.0    0.0
(재)한식진흥원           4.0     11.0   20.0   42.0    0.0    2.0
(주)강원랜드            238.0   85.0   273.0  3701.0  224.0  0.0
(주)워터웨이플러스         2.0     3.0    5.0    95.0    0.0    0.0
(주)한국가스기술공사        33.0    3.0    51.0   1564.0  44.0   55.0
(주)한국건설관리공사        0.0     0.0    4.0    380.0   0.0    0.0
88관광개발(주)          0.0     0.0    0.0    43.0    0.0    0.0
IOM이민정책연구원         0.0     3.0    5.0    21.0    0.0    0.0
KDI국제정책대학원         0.0     0.0    0.0    101.0   0.0    6.0
가축위생방역지원본부         1.0     0.0    2.0    1061.0  0.0    0.0
강릉원주대학교치과병원        16.0    11.0   18.0   198.0   0.0    0.0
강원대학교병원            447.0   344.0  477.0  1542.0  0.0    0.0
건강보험심사평가원          111.0   188.0  241.0  3222.0  16.0   147.0
건설근로자공제회           8.0     7.0    25.0   156.5   0.0    5.0
건축도시공간연구소          0.0     3.0    3.0    62.0    0.0    4.0
게임물관리위원회           5.0     0.0    7.0    93.0    0.0    5.0
경북대학교병원            757.0   601.0  769.0  3862.0  0.0    0.0
경북대학교치과병원          23.0    17.0   32.0   176.0   0.0    0.0
...                ...     ...    ...     ...    ...    ...
한국체육산업개발(주)        1.0     0.0    2.0    1455.0  0.0    0.0
한국출판문화산업진흥원        0.0     0.0    0.0    92.0    0.0    0.0
한국콘텐츠진흥원           5.0     13.0   16.0   314.0   0.0    3.0
한국토지주택공사           116.0   116.0  269.0  8539.0  253.0  533.0
한국투자공사             2.0     3.0    13.0   285.0   0.0    0.0
한국특허전략개발원          0.0     0.5    0.5    224.0   1.0    6.0
한국특허정보원            6.0     5.0    14.0   382.0   12.0   18.0
한국표준과학연구원          0.0     3.0    17.0   464.0   0.0    0.0
한국학중앙연구원           1.0     2.0    6.0    271.0   0.0    22.0
한국한의학연구원           0.0     3.0    10.0   203.0   0.0    26.0
한국항공우주연구원          0.0     21.0   87.0   967.0   0.0    0.0
한국항로표지기술원          0.0     0.0    0.0    51.0    0.0    0.0
한국해양과학기술원          0.0     0.0    1.0    518.0   0.0    0.0
한국해양수산개발원          21.0    22.0   33.0   218.0   0.0    8.0
한국해양수산연수원          7.0     1.0    7.0    191.0   0.0    3.0
한국해양조사협회           7.0     3.0    11.0   53.0    0.0    2.0
한국행정연구원            0.0     24.0   34.0   126.0   0.0    5.0
한국형사정책연구원          0.0     0.0    1.0    92.0    0.0    6.0
한국화학연구원            0.0     2.0    4.0    583.0   0.0    144.0
한국환경공단             46.0    37.0   98.0   2749.0  95.0   34.0
한국환경산업기술원          4.0     9.0    16.0   514.0   0.0    46.0
한국환경정책평가연구원        0.0     1.0    3.0    180.0   0.0    13.0
한약진흥재단             3.0     2.0    7.0    139.0   0.0    0.0
한전KDN              85.5    42.5   132.5  2554.0  148.0  42.0
한전KPS(주)           284.0   61.0   374.0  6236.0  61.0   258.0
한전원자력연료주식회사        1.0     0.0    3.0    1186.0  0.0    15.0
항공안전기술원            1.0     0.0    3.0    92.0    0.0    4.0
해양수산과학기술진흥원        2.0     2.0    7.0    80.0    0.0    4.0
해양환경공단             14.0    4.0    17.0   666.0   2.0    25.0
환경보전협회             2.0     2.0    5.0    251.0   0.0    0.0

[360 rows x 36 columns]

In [42]:
df_rcrt_pivot.loc[~df_rcrt_pivot.index.str.contains('병원'), [('2018', '신입_여성')]].sort_values(('2018', '신입_여성'), ascending=False).head(20)

             2018
항목          신입_여성
기관명
근로복지공단      807.0
국민건강보험공단    546.5
한국보훈복지의료공단  486.0
국민연금공단      220.0
한국철도공사      192.0
건강보험심사평가원   188.0
대한적십자사      169.0
한국전력공사      140.0
국립중앙의료원     128.0
국립암센터       118.0
한국토지주택공사    116.0
한국산업인력공단    96.0
한국수력원자력(주)  88.0
(주)강원랜드     85.0
한국도로공사      80.0
한국수자원공사     69.5
한국개발연구원     68.0
한전KPS(주)    61.0
한국전자통신연구원   57.0
한국원자력의학원    56.0

In [43]:
'''
체험인턴 / 직원전체
채용인턴 / 직원전체
신입전체 / 직원전체
여성 / 신입전체
지역인재 / 신입전체
'''

for y in col_year:
    df_rcrt_pivot[(y, '체험인턴/직원전체')] = df_rcrt_pivot[(y, '인턴_체험형')] / df_rcrt_pivot[(y, '직원_전체')] * 100
    df_rcrt_pivot[(y, '채용인턴/직원전체')] = df_rcrt_pivot[(y, '인턴_채용형')] / df_rcrt_pivot[(y, '직원_전체')] * 100
    df_rcrt_pivot[(y, '신입전체/직원전체')] = df_rcrt_pivot[(y, '신입_전체')] / df_rcrt_pivot[(y, '직원_전체')] * 100
    df_rcrt_pivot[(y, '여성/신입전체')] = df_rcrt_pivot[(y, '신입_여성')] / df_rcrt_pivot[(y, '신입_전체')] * 100
    df_rcrt_pivot[(y, '지역인재/신입전체')] = df_rcrt_pivot[(y, '신입_지역인재')] / df_rcrt_pivot[(y, '신입_전체')] * 100

df_rcrt_pivot.head()
# df_pay_pivot_woman.sort_values(('2018', '여성 비율'), ascending=True)

                 2013                                     2014              \
항목            신입_지역인재 신입_여성 신입_전체  직원_전체 인턴_채용형 인턴_체험형 신입_지역인재 신입_여성 신입_전체
기관명
(사)남북교류협력지원협회  1.0     0.0   4.0   26.0   0.0    1.0    0.0     0.0   3.0
(재)APEC기후센터    7.0     7.0   15.0  70.0   0.0    0.0    5.0     6.0   16.0
(재)국제원산지정보원    1.0     1.0   2.0   50.0   0.0    3.0    1.0     3.0   5.0
(재)예술경영지원센터    0.0     3.0   3.0   25.0   0.0    3.0    3.0     14.0  17.0
(재)우체국금융개발원    2.0     4.0   9.0   189.0  0.0    8.0    9.0     5.0   12.0

                         ...           2017                                  \
항목             직원_전체     ...      체험인턴/직원전체 채용인턴/직원전체  신입전체/직원전체    여성/신입전체
기관명                      ...
(사)남북교류협력지원협회  26.0      ...      6.896552   0.000000  3.448276   0.000000
(재)APEC기후센터    90.0      ...      0.000000   0.000000  6.666667   50.000000
(재)국제원산지정보원    50.0      ...      0.000000   0.000000  28.000000  35.714286
(재)예술경영지원센터    35.0      ...      15.094340  0.000000  9.433962   80.000000
(재)우체국금융개발원    688.0     ...      3.596127   0.414938  4.702628   61.764706

                               2018                                   \
항목             지역인재/신입전체  체험인턴/직원전체 채용인턴/직원전체  신입전체/직원전체     여성/신입전체
기관명
(사)남북교류협력지원협회  0.000000   6.896552   0.0       13.793103  50.000000
(재)APEC기후센터    50.000000  0.000000   0.0       3.333333   100.000000
(재)국제원산지정보원    35.714286  0.000000   0.0       6.000000   33.333333
(재)예술경영지원센터    0.000000   13.043478  0.0       1.449275   100.000000
(재)우체국금융개발원    32.352941  2.005348   0.0       1.604278   58.333333


항목              지역인재/신입전체
기관명
(사)남북교류협력지원협회  0.000000
(재)APEC기후센터    66.666667
(재)국제원산지정보원    0.000000
(재)예술경영지원센터    100.000000
(재)우체국금융개발원    41.666667

[5 rows x 66 columns]

## **#체험인턴/직원전체 랭킹**

In [44]:
year = '2018'
col_rcrt = [(y, '직원_전체'),
            (y, '인턴_체험형'), (y, '체험인턴/직원전체'), 
            (y, '인턴_채용형'), (y, '채용인턴/직원전체'),
            (y, '신입_전체'), (y, '신입전체/직원전체'),
            (y, '신입_여성'), (y, '여성/신입전체'),]
df_rcrt_pivot.loc[::, col_rcrt].sort_values(('2018', '체험인턴/직원전체'), ascending=False)

                       2018                                              \
항목                    직원_전체  인턴_체험형  체험인턴/직원전체 인턴_채용형 채용인턴/직원전체   신입_전체
기관명
한국기초과학지원연구원         275.00   97.00   35.272727  0.0    0.000000  2.00
한국국제협력단             512.00   145.00  28.320312  0.0    0.000000  2.00
한국예술인복지재단           35.00    9.00    25.714286  0.0    0.000000  13.00
한국화학연구원             583.00   144.00  24.699828  0.0    0.000000  4.00
한국과학기술연구원           908.00   224.00  24.669604  0.0    0.000000  57.00
극지연구소               212.00   46.00   21.698113  0.0    0.000000  7.00
한국연구재단              357.00   76.00   21.288515  22.0   6.162465  18.00
한국고용정보원             367.00   71.00   19.346049  0.0    0.000000  36.00
한국언론진흥재단            182.00   34.00   18.681319  0.0    0.000000  6.00
산업연구원               173.00   32.00   18.497110  0.0    0.000000  11.00
한국주택금융공사            865.00   157.00  18.150289  35.0   4.046243  42.00
한국세라믹기술원            209.00   37.00   17.703349  0.0    0.000000  4.00
한국저작권위원회            148.00   25.00   16.891892  0.0    0.000000  11.00
제주국제자유도시개발센터        341.00   55.25   16.202346  0.0    0.000000  46.25
한국교통안전공단            1667.30  256.00  15.354165  69.0   4.138427  103.50
그랜드코리아레저(주)         1875.00  275.00  14.666667  0.0    0.000000  11.00
한국데이터진흥원            58.00    8.00    13.793103  0.0    0.000000  3.00
한국뇌연구원              68.00    9.00    13.235294  0.0    0.000000  7.00
(재)예술경영지원센터         69.00    9.00    13.043478  0.0    0.000000  1.00
신용보증재단중앙회           54.00    7.00    12.962963  0.0    0.000000  0.00
한국한의학연구원            203.00   26.00   12.807882  0.0    0.000000  10.00
한국수출입은행             1124.54  132.00  11.738133  0.0    0.000000  21.00
신용보증기금              2620.50  301.00  11.486358  0.0    0.000000  3.00
한국생명공학연구원           588.00   66.00   11.224490  0.0    0.000000  3.00
한국청소년상담복지개발원        204.50   22.00   10.757946  0.0    0.000000  2.00
대한무역투자진흥공사          1236.00  132.00  10.679612  0.0    0.000000  2.00
한국전자통신연구원           2335.00  244.00  10.449679  0.0    0.000000  247.00
한국원자력안전기술원          557.00   55.00   9.874327   0.0    0.000000  35.00
대외경제정책연구원           204.00   20.00   9.803922   0.0    0.000000  5.00
재단법인 한국여성과학기술인지원센터  41.00    4.00    9.756098   0.0    0.000000  14.00
...                    ...     ...        ...   ...         ...    ...
코레일로지스(주)           132.00   0.00    0.000000   0.0    0.000000  16.00
코레일네트웍스(주)          1635.80  0.00    0.000000   20.0   1.222643  26.00
코레일관광개발(주)          1065.00  0.00    0.000000   0.0    0.000000  58.00
재단법인 한국장기조직기증원      100.00   0.00    0.000000   0.0    0.000000  9.00
아시아문화원              247.00   0.00    0.000000   3.0    1.214575  5.00
예술의전당               381.00   0.00    0.000000   0.0    0.000000  9.00
오송첨단의료산업진흥재단        411.00   0.00    0.000000   0.0    0.000000  35.00
울산과학기술원             635.00   0.00    0.000000   0.0    0.000000  26.00
의료법인 한전의료재단 한일병원    751.00   0.00    0.000000   0.0    0.000000  177.00
인천국제공항공사            1538.00  0.00    0.000000   0.0    0.000000  63.00
재단법인 국악방송           62.00    0.00    0.000000   0.0    0.000000  3.75
재단법인 대한건설기계안전관리원    198.00   0.00    0.000000   0.0    0.000000  2.00
재단법인 의료기관평가인증원      80.00    0.00    0.000000   0.0    0.000000  0.00
재단법인 장애인기업종합지원센터    38.00    0.00    0.000000   0.0    0.000000  2.00
재단법인 한국에너지재단        46.00    0.00    0.000000   0.0    0.000000  8.00
재외동포재단              71.00    0.00    0.000000   0.0    0.000000  12.50
충북대학교병원             1762.00  0.00    0.000000   0.0    0.000000  519.00
전략물자관리원             53.00    0.00    0.000000   0.0    0.000000  3.00
전쟁기념사업회             104.00   0.00    0.000000   0.0    0.000000  5.00
정보통신기술진흥센터          258.13   0.00    0.000000   0.0    0.000000  5.00
정부법무공단              124.00   0.00    0.000000   0.0    0.000000  4.00
제주대학교병원             1583.00  0.00    0.000000   0.0    0.000000  209.00
주식회사 공영홈쇼핑          339.00   0.00    0.000000   0.0    0.000000  0.00
주식회사 부산항보안공사        485.00   0.00    0.000000   0.0    0.000000  124.00
주식회사 인천항보안공사        340.00   0.00    0.000000   0.0    0.000000  3.00
주택관리공단(주)           2275.00  0.00    0.000000   0.0    0.000000  181.00
중소기업유통센터            214.00   0.00    0.000000   0.0    0.000000  18.00
창업진흥원               170.00   0.00    0.000000   0.0    0.000000  23.00
환경보전협회              251.00   0.00    0.000000   0.0    0.000000  5.00
한국농어촌공사             6738.00 NaN     NaN        NaN    NaN       NaN


항목                  신입전체/직원전체   신입_여성     여성/신입전체
기관명
한국기초과학지원연구원         0.727273   0.00    0.000000
한국국제협력단             0.390625   1.00    50.000000
한국예술인복지재단           37.142857  11.00   84.615385
한국화학연구원             0.686106   2.00    50.000000
한국과학기술연구원           6.277533   10.00   17.543860
극지연구소               3.301887   2.00    28.571429
한국연구재단              5.042017   7.00    38.888889
한국고용정보원             9.809264   19.00   52.777778
한국언론진흥재단            3.296703   1.00    16.666667
산업연구원               6.358382   3.00    27.272727
한국주택금융공사            4.855491   12.00   28.571429
한국세라믹기술원            1.913876   1.00    25.000000
한국저작권위원회            7.432432   5.00    45.454545
제주국제자유도시개발센터        13.563050  15.00   32.432432
한국교통안전공단            6.207641   15.50   14.975845
그랜드코리아레저(주)         0.586667   3.00    27.272727
한국데이터진흥원            5.172414   2.00    66.666667
한국뇌연구원              10.294118  4.00    57.142857
(재)예술경영지원센터         1.449275   1.00    100.000000
신용보증재단중앙회           0.000000   0.00   NaN
한국한의학연구원            4.926108   3.00    30.000000
한국수출입은행             1.867430   9.00    42.857143
신용보증기금              0.114482   0.00    0.000000
한국생명공학연구원           0.510204   2.00    66.666667
한국청소년상담복지개발원        0.977995   2.00    100.000000
대한무역투자진흥공사          0.161812   1.00    50.000000
한국전자통신연구원           10.578158  57.00   23.076923
한국원자력안전기술원          6.283662   8.00    22.857143
대외경제정책연구원           2.450980   0.00    0.000000
재단법인 한국여성과학기술인지원센터  34.146341  12.00   85.714286
...                      ...    ...          ...
코레일로지스(주)           12.121212  4.00    25.000000
코레일네트웍스(주)          1.589436   14.00   53.846154
코레일관광개발(주)          5.446009   15.00   25.862069
재단법인 한국장기조직기증원      9.000000   7.00    77.777778
아시아문화원              2.024291   4.00    80.000000
예술의전당               2.362205   4.00    44.444444
오송첨단의료산업진흥재단        8.515815   14.00   40.000000
울산과학기술원             4.094488   3.00    11.538462
의료법인 한전의료재단 한일병원    23.568575  128.00  72.316384
인천국제공항공사            4.096229   23.00   36.507937
재단법인 국악방송           6.048387   1.75    46.666667
재단법인 대한건설기계안전관리원    1.010101   1.00    50.000000
재단법인 의료기관평가인증원      0.000000   0.00   NaN
재단법인 장애인기업종합지원센터    5.263158   1.00    50.000000
재단법인 한국에너지재단        17.391304  2.00    25.000000
재외동포재단              17.605634  7.00    56.000000
충북대학교병원             29.455165  350.00  67.437380
전략물자관리원             5.660377   2.00    66.666667
전쟁기념사업회             4.807692   2.00    40.000000
정보통신기술진흥센터          1.937008   2.00    40.000000
정부법무공단              3.225806   3.00    75.000000
제주대학교병원             13.202780  150.00  71.770335
주식회사 공영홈쇼핑          0.000000   0.00   NaN
주식회사 부산항보안공사        25.567010  12.00   9.677419
주식회사 인천항보안공사        0.882353   0.00    0.000000
주택관리공단(주)           7.956044   50.00   27.624309
중소기업유통센터            8.411215   8.00    44.444444
창업진흥원               13.529412  8.00    34.782609
환경보전협회              1.992032   2.00    40.000000
한국농어촌공사            NaN        NaN     NaN

[360 rows x 9 columns]

## **#채용인턴/직원전체 랭킹**

In [45]:
df_rcrt_pivot.loc[::, col_rcrt].sort_values(('2018', '채용인턴/직원전체'), ascending=False).head(10)

                 2018                                                         \
항목              직원_전체 인턴_체험형 체험인턴/직원전체 인턴_채용형  채용인턴/직원전체    신입_전체  신입전체/직원전체
기관명
한국문화예술교육진흥원  120.000   0.0    0.000000  22.0   18.333333  4.00     3.333333
한국사회적기업진흥원   98.000    0.0    0.000000  15.0   15.306122  19.00    19.387755
한국노인인력개발원    149.000   3.0    2.013423  19.0   12.751678  21.00    14.093960
한국산림복지진흥원    310.000   3.0    0.967742  34.0   10.967742  77.00    24.838710
한국식품안전관리인증원  228.000   20.0   8.771930  25.0   10.964912  27.00    11.842105
한국전기안전공사     3063.000  0.0    0.000000  308.0  10.055501  316.00   10.316683
근로복지공단       8866.125  0.0    0.000000  842.0  9.496821   1259.75  14.208575
한국보건복지인력개발원  233.000   0.0    0.000000  21.0   9.012876   5.00     2.145923
한국산업인력공단     1770.200  0.0    0.000000  150.0  8.473619   201.00   11.354649
한국방송통신전파진흥원  502.500   13.0   2.587065  42.0   8.358209   8.00     1.592040


항목           신입_여성     여성/신입전체
기관명
한국문화예술교육진흥원  4.0    100.000000
한국사회적기업진흥원   10.0   52.631579
한국노인인력개발원    12.0   57.142857
한국산림복지진흥원    34.0   44.155844
한국식품안전관리인증원  17.0   62.962963
한국전기안전공사     30.0   9.493671
근로복지공단       807.0  64.060329
한국보건복지인력개발원  3.0    60.000000
한국산업인력공단     96.0   47.761194
한국방송통신전파진흥원  4.0    50.000000

## **#신입전체/직원전체 랭킹**

In [46]:
df_rcrt_pivot.loc[::, col_rcrt].sort_values(('2018', '신입전체/직원전체'), ascending=False).head(20)

                      2018                                              \
항목                   직원_전체 인턴_체험형  체험인턴/직원전체 인턴_채용형  채용인턴/직원전체   신입_전체
기관명
(재)한식진흥원            42.0    2.0    4.761905   0.0    0.000000   20.0
한국건강증진개발원           128.0   8.0    6.250000   0.0    0.000000   57.0
국가과학기술인력개발원         114.0   0.0    0.000000   0.0    0.000000   44.0
한국예술인복지재단           35.0    9.0    25.714286  0.0    0.000000   13.0
재단법인 한국여성과학기술인지원센터  41.0    4.0    9.756098   0.0    0.000000   14.0
강원대학교병원             1542.0  0.0    0.000000   0.0    0.000000   477.0
한국어촌어항공단            172.0   5.0    2.906977   0.0    0.000000   53.0
충북대학교병원             1762.0  0.0    0.000000   0.0    0.000000   519.0
한국사학진흥재단            96.0    0.0    0.000000   0.0    0.000000   28.0
국가수리과학연구소           53.0    1.0    1.886792   0.0    0.000000   15.0
한국조세재정연구원           298.0   11.0   3.691275   0.0    0.000000   84.0
부산대학교병원             5943.0  0.0    0.000000   0.0    0.000000   1652.0
서울요양원               118.0   0.0    0.000000   0.0    0.000000   32.0
한국행정연구원             126.0   5.0    3.968254   0.0    0.000000   34.0
주식회사 부산항보안공사        485.0   0.0    0.000000   0.0    0.000000   124.0
녹색기술센터              55.0    1.0    1.818182   0.0    0.000000   14.0
한국개발연구원             446.0   24.0   5.381166   0.0    0.000000   112.0
한국산림복지진흥원           310.0   3.0    0.967742   34.0   10.967742  77.0
IOM이민정책연구원          21.0    0.0    0.000000   0.0    0.000000   5.0
과학기술일자리진흥원          42.0    0.0    0.000000   0.0    0.000000   10.0


항목                  신입전체/직원전체   신입_여성    여성/신입전체
기관명
(재)한식진흥원            47.619048  11.0    55.000000
한국건강증진개발원           44.531250  38.0    66.666667
국가과학기술인력개발원         38.596491  24.0    54.545455
한국예술인복지재단           37.142857  11.0    84.615385
재단법인 한국여성과학기술인지원센터  34.146341  12.0    85.714286
강원대학교병원             30.933852  344.0   72.117400
한국어촌어항공단            30.813953  10.0    18.867925
충북대학교병원             29.455165  350.0   67.437380
한국사학진흥재단            29.166667  11.0    39.285714
국가수리과학연구소           28.301887  1.0     6.666667
한국조세재정연구원           28.187919  53.0    63.095238
부산대학교병원             27.797409  1249.0  75.605327
서울요양원               27.118644  29.0    90.625000
한국행정연구원             26.984127  24.0    70.588235
주식회사 부산항보안공사        25.567010  12.0    9.677419
녹색기술센터              25.454545  8.0     57.142857
한국개발연구원             25.112108  68.0    60.714286
한국산림복지진흥원           24.838710  34.0    44.155844
IOM이민정책연구원          23.809524  3.0     60.000000
과학기술일자리진흥원          23.809524  5.0     50.000000

In [47]:
# df_rcrt_pivot.loc[df_rcrt_pivot[('2018', '신입_전체')] >= 5, col_rcrt].sort_values(('2018', '여성/신입전체'), ascending=True).head(20)
df_rcrt_pivot.loc[::, col_rcrt].sort_values(('2018', '여성/신입전체'), ascending=True).head(20)

                   2018                                                    \
항목                직원_전체 인턴_체험형 체험인턴/직원전체 인턴_채용형 채용인턴/직원전체 신입_전체 신입전체/직원전체
기관명
한국체육산업개발(주)      1455.0  0.0    0.000000  0.0    0.000000  2.0   0.137457
특허정보진흥센터         665.0   0.0    0.000000  2.0    0.300752  2.0   0.300752
통일연구원            97.0    4.0    4.123711  0.0    0.000000  3.0   3.092784
국립낙동강생물자원관       201.0   0.0    0.000000  3.0    1.492537  8.0   3.980100
사단법인 한국산학연협회     40.0    0.0    0.000000  0.0    0.000000  1.0   2.500000
한국석유공사           1422.0  30.0   2.109705  0.0    0.000000  2.0   0.140647
국립해양생물자원관        220.0   0.0    0.000000  0.0    0.000000  1.0   0.454545
주식회사 인천항보안공사     340.0   0.0    0.000000  0.0    0.000000  3.0   0.882353
한국천문연구원          214.0   0.0    0.000000  0.0    0.000000  3.0   1.401869
국방기술품질원          891.0   0.0    0.000000  0.0    0.000000  1.0   0.112233
한국지식재산연구원        81.0    2.0    2.469136  0.0    0.000000  1.0   1.234568
재료연구소            350.0   7.0    2.000000  0.0    0.000000  2.0   0.571429
기술보증기금           1393.0  65.0   4.666188  0.0    0.000000  2.0   0.143575
나노종합기술원          85.0    0.0    0.000000  0.0    0.000000  4.0   4.705882
울산항만공사           110.0   5.0    4.545455  2.0    1.818182  5.0   4.545455
한국전력국제원자력대학원대학교  54.0    0.0    0.000000  0.0    0.000000  2.0   3.703704
농업기술실용화재단        293.0   0.0    0.000000  0.0    0.000000  1.0   0.341297
대구경북과학기술원        313.0   14.0   4.472843  0.0    0.000000  6.0   1.916933
대외경제정책연구원        204.0   20.0   9.803922  0.0    0.000000  5.0   2.450980
한국에너지기술연구원       545.0   7.0    1.284404  0.0    0.000000  5.0   0.917431


항목              신입_여성 여성/신입전체
기관명
한국체육산업개발(주)      0.0   0.0
특허정보진흥센터         0.0   0.0
통일연구원            0.0   0.0
국립낙동강생물자원관       0.0   0.0
사단법인 한국산학연협회     0.0   0.0
한국석유공사           0.0   0.0
국립해양생물자원관        0.0   0.0
주식회사 인천항보안공사     0.0   0.0
한국천문연구원          0.0   0.0
국방기술품질원          0.0   0.0
한국지식재산연구원        0.0   0.0
재료연구소            0.0   0.0
기술보증기금           0.0   0.0
나노종합기술원          0.0   0.0
울산항만공사           0.0   0.0
한국전력국제원자력대학원대학교  0.0   0.0
농업기술실용화재단        0.0   0.0
대구경북과학기술원        0.0   0.0
대외경제정책연구원        0.0   0.0
한국에너지기술연구원       0.0   0.0

## **#신입추이**

In [48]:
col_tmp = '신입_전체'
col_new_change = [(c, col_tmp) for c in col_year]
df_rcrt_new = df_rcrt_pivot.loc[::, col_new_change].sort_values(('2018', col_tmp), ascending=False); df_rcrt_new.head()

mean_rcrt_new = df_rcrt_new.mean(axis=1).to_frame(name=('평균', '')); mean_rcrt_new.head()

exp_rcrt_new = df_rcrt_new.merge(mean_rcrt_new, left_index=True, right_index=True, how='inner').sort_values(('평균', ''), ascending=False)
exp_rcrt_new.columns = exp_rcrt_new.columns.droplevel(1)
exp_rcrt_new.reset_index(inplace=True)

exp_rcrt_new.head(10)

          기관명   2013    2014     2015     2016    2017     2018           평균
0  한국전력공사      819.0  738.50  1019.00  1412.50  1574.0  872.00   1072.500000
1  부산대학교병원     582.0  559.00  727.00   559.00   514.0   1652.00  765.500000
2  한국수력원자력(주)  627.0  677.50  1369.00  821.50   602.5   346.00   740.583333
3  국민건강보험공단    349.0  546.00  512.50   873.00   1075.0  820.00   695.916667
4  서울대학교병원     562.0  616.00  616.00   574.00   923.0   674.00   660.833333
5  한국철도공사      166.0  505.00  319.00   604.00   1060.0  1126.00  630.000000
6  근로복지공단      471.5  348.75  318.75   296.75   853.0   1259.75  591.416667
7  분당서울대학교병원   662.0  541.00  380.00   293.00   430.0   612.45   486.408333
8  경북대학교병원     250.0  283.00  320.00   465.00   362.0   769.00   408.166667
9  경상대학교병원     133.0  141.00  175.00   865.00   470.0   664.00   408.000000

## Export: exp_rcrt_new

In [49]:
# exp_rcrt_new.to_csv(data_directory+'rcrt_new.tsv', sep='\t', index=False)

## **#채용인턴 추이**

In [50]:
col_tmp = '인턴_채용형'
col_new_change = [(c, col_tmp) for c in col_year]
df_rcrt_new = df_rcrt_pivot.loc[::, col_new_change].sort_values(('2018', col_tmp), ascending=False); df_rcrt_new.head()

mean_rcrt_new = df_rcrt_new.mean(axis=1).to_frame(name=('평균', '')); mean_rcrt_new.head()

exp_rcrt_intern = df_rcrt_new.merge(mean_rcrt_new, left_index=True, right_index=True, how='inner').sort_values(('평균', ''), ascending=False)
exp_rcrt_intern.columns = exp_rcrt_intern.columns.droplevel(1)
exp_rcrt_intern.reset_index(inplace=True)

exp_rcrt_intern.head(20)

           기관명   2013   2014    2015    2016     2017    2018          평균
0   한국철도공사      228.0  680.0  381.00  823.00  1083.00  320.00  585.833333
1   한국수력원자력(주)  685.0  926.5  483.00  472.00  361.00   314.00  540.250000
2   한국전력공사      0.0    420.0  345.00  552.00  356.00   237.00  318.333333
3   한국도로공사      190.0  205.0  256.75  213.25  260.25   372.25  249.583333
4   근로복지공단      0.0    16.0   18.00   20.00   301.12   842.00  199.520000
5   한국전기안전공사    0.0    228.0  150.00  255.00  186.00   308.00  187.833333
6   한국수자원공사     0.0    20.0   151.00  254.00  277.00   234.00  156.000000
7   한국남동발전(주)   210.0  160.0  100.00  81.00   75.00    23.00   108.166667
8   한국토지주택공사    0.0    0.0    0.00    123.00  201.00   253.00  96.166667
9   한국국토정보공사    0.0    0.0    0.00    172.00  171.00   219.00  93.666667
10  한국중부발전(주)   71.0   129.0  125.00  151.00  39.00    30.00   90.833333
11  한국산업인력공단    0.0    33.0   106.00  142.00  88.00    150.00  86.500000
12  주택관리공단(주)   68.0   103.0  139.00  121.00  64.00    0.00    82.500000
13  한국서부발전(주)   82.0   109.0  83.00   98.00   54.00    0.00    71.000000
14  한국남부발전(주)   150.0  46.5   66.50   81.00   56.00    0.00    66.666667
15  한국환경공단      0.0    0.0    102.00  103.00  88.00    95.00   64.666667
16  한전KDN       0.0    0.0    0.00    85.00   150.00   148.00  63.833333
17  한국지역난방공사    0.0    0.0    101.00  154.00  66.00    57.00   63.000000
18  한국가스공사      16.0   10.0   0.00    170.00  134.00   48.00   63.000000
19  한국공항공사      0.0    0.0    83.00   100.00  186.00   0.00    61.500000

## Export: exp_rcrt_intern

In [51]:
# exp_rcrt_intern.to_csv(data_directory+'rcrt_intern.tsv', sep='\t', index=False)

# 기관

In [52]:


org_emp = set(df_emp['기관명'].drop_duplicates())
org_pay = set(df_pay['기관명'].drop_duplicates())
org_rcrt = set(df_rcrt['기관명'].drop_duplicates())
org_board = set(df_board['기관명'].drop_duplicates())

print('org_emp:', len(org_emp))
print('org_pay:', len(org_pay))
print('org_rcrt:', len(org_rcrt))
print('org_board:', len(org_board))

# org_pay = org_rcrt = 360
# org_pay - org_emp = '사단법인 한국기술자격검정원'
intersection = org_emp & org_pay & org_rcrt & org_board
print('intersection: ', len(intersection))

print(org_emp - org_board)

NameError: name 'df_board' is not defined

## 부설기관여부

In [53]:
sub_org_emp = set(df_emp.loc[df_emp['부설기관여부']=='Y']['기관명'].drop_duplicates())
sub_org_pay = set(df_pay.loc[df_pay['부설기관여부']=='Y']['기관명'].drop_duplicates())
sub_org_rcrt = set(df_rcrt.loc[df_rcrt['부설기관여부']=='Y']['기관명'].drop_duplicates())
sub_org_board = set(df_board.loc[df_board['부설기관여부']=='Y']['기관명'].drop_duplicates())


print('sub_org_emp:', len(sub_org_emp))
print('sub_org_pay:', len(sub_org_pay))
print('sub_org_rcrt:', len(sub_org_rcrt))
print('sub_org_board:', len(sub_org_board))

intersection_sub_org = sub_org_emp & sub_org_pay & sub_org_rcrt # & sub_org_board
print('sub org intersection: ', len(intersection_sub_org))
sub_org_emp - sub_org_board

NameError: name 'df_board' is not defined

# 복리후생

## Load Data: df_welf

In [54]:
# 6~11
df_welf = pd.DataFrame()

for i in range(6, 11):
    df_welf = df_welf.append(get_df_from_file(file_names[i]))

df_welf['항목'] = df_welf['항목'].str.strip()
df_welf['부설기관여부'] = df_welf['부설기관여부'].str.strip()
df_welf['신분_list'] = df_welf['항목'].str.split('>')
df_welf['신분'] = df_welf['신분_list'].apply(lambda x: x[-1].strip())

df_welf.head(1)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부,신분_list,신분
0,(사)남북교류협력지원협회,기타공공기관,복리후생비 > 예산상 복리후생비 > 비급여성 > 선택적복지제도 > 임원,0.0,0.0,0.0,0.0,0.0,-,천원,N,"[복리후생비 , 예산상 복리후생비 , 비급여성 , 선택적복지제도 , 임원]",임원

In [55]:
# df_welf.loc[(df_welf['기관명']=='(사)남북교류협력지원협회')]
df_welf.loc[(df_welf['기관명']=='한국전력공사'), ['기관명', '항목', '신분', '2017']]

,기관명,항목,신분,2017
4484,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 선택적복지제도 > 정규직,정규직,0.0
4485,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기념품비 > 정규직,정규직,137250.0
4486,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 정규직,정규직,4791921.0
4487,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 정규직,정규직,0.0
4488,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 선택적복지제도 > 무기계약직,무기계약직,0.0
4489,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기념품비 > 무기계약직,무기계약직,0.0
4490,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 무기계약직,무기계약직,0.0
4491,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 무기계약직,무기계약직,0.0
4492,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 선택적복지제도 > 비정규직,비정규직,405388.0
4493,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기념품비 > 비정규직,비정규직,1000.0
4494,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 비정규직,비정규직,125916.0
4495,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 비정규직,비정규직,0.0
6726,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기념품비 > 정규직,정규직,451500.0
6727,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 정규직,정규직,0.0
6728,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 경로효친비 > 정규직,정규직,0.0
6729,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 문화여가비 > 정규직,정규직,0.0
6730,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 재해보상 및 재해부조 > 정규직,정규직,0.0
6731,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기타 > 정규직,정규직,19890888.0
6732,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기념품비 > 무기계약직,무기계약직,0.0
6733,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 무기계약직,무기계약직,0.0
6734,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 경로효친비 > 무기계약직,무기계약직,0.0
6735,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 문화여가비 > 무기계약직,무기계약직,0.0
6736,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 재해보상 및 재해부조 > 무기계약직,무기계약직,0.0
6737,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기타 > 무기계약직,무기계약직,0.0
6738,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기념품비 > 비정규직,비정규직,0.0
6739,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 비정규직,비정규직,0.0
6740,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 경로효친비 > 비정규직,비정규직,0.0
6741,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 문화여가비 > 비정규직,비정규직,0.0
6742,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 재해보상 및 재해부조 > 비정규직,비정규직,0.0
6743,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 기타 > 비정규직,비정규직,642500.0
...,...,...,...,...
7865,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 생활안정자금 > 비정규직,비정규직,0.0
7866,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 경조비 및 유족위로금 > 비정규직,비정규직,0.0
7867,한국전력공사,복리후생비 > 예산상 복리후생비 > 급여성 > 선택적복지제도 > 비정규직,비정규직,0.0
3363,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 문화여가비 > 정규직,정규직,4890265.0
3364,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 재해보상 및 재해부조 > 정규직,정규직,163137.0
3365,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 정규직,정규직,16120799.0
3366,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 문화여가비 > 무기계약직,무기계약직,0.0
3367,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 재해보상 및 재해부조 > 무기계약직,무기계약직,0.0
3368,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 무기계약직,무기계약직,0.0
3369,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 문화여가비 > 비정규직,비정규직,0.0
3370,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 재해보상 및 재해부조 > 비정규직,비정규직,0.0
3371,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 비정규직,비정규직,68152.0
6726,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 정규직,정규직,594744.0
6727,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 정규직,정규직,0.0
6728,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 주택자금 > 정규직,정규직,0.0
6729,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 정규직,정규직,3487509.0
6730,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 정규직,정규직,0.0
6731,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경조비 및 유족위로금 > 정규직,정규직,0.0
6732,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 무기계약직,무기계약직,0.0
6733,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 무기계약직,무기계약직,0.0
6734,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 주택자금 > 무기계약직,무기계약직,0.0
6735,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 무기계약직,무기계약직,0.0
6736,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 무기계약직,무기계약직,0.0
6737,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경조비 및 유족위로금 > 무기계약직,무기계약직,0.0
6738,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 비정규직,비정규직,0.0
6739,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 비정규직,비정규직,0.0
6740,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 주택자금 > 비정규직,비정규직,0.0
6741,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 비정규직,비정규직,24021.0
6742,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 비정규직,비정규직,0.0
6743,한국전력공사,복리후생비 > 예산상 복리후생비 > 비급여성 > 경조비 및 유족위로금 > 비정규직,비정규직,64150.0

## Group

In [56]:
df_welf_group = df_welf.groupby(['기관명', '신분']).agg({'2017': 'sum'}).unstack(); df_welf_group.head()

                   2017
신분                무기계약직     비정규직      임원        정규직
기관명
(사)남북교류협력지원협회 NaN        2887.0   347.0   36121.0
(재)국제원산지정보원   NaN        12433.0  2506.0  121307.0
(재)예술경영지원센터    13816.0   17678.0 NaN      38399.0
(재)우체국금융개발원    305350.0  17167.0 NaN      241733.0
(재)우체국물류지원단    230833.0  87160.0 NaN      1820179.0

In [57]:
df_welf_group.sort_values(('2017', '정규직'), ascending=False)

                         2017
신분                      무기계약직       비정규직       임원         정규직
기관명
한국전력공사              0.0        1336557.0 NaN       55651588.0
한국철도공사             NaN         72252.0    2586.0   39161524.0
국민건강보험공단            0.0        8350.0     2400.0   25007853.0
중소기업은행              6653180.0  631385.0   11130.0  17851978.0
한국수력원자력(주)          46213.0    130629.0  NaN       15943178.0
(주)강원랜드             59256.0    344813.0   4501.0   15577882.0
한국토지주택공사            689663.0   1506342.0  4828.0   14872179.0
한전KPS(주)            9924.0     269936.0   1013.0   12773245.0
국민연금공단              352664.0   474237.0   2442.0   10248988.0
한국국토정보공사            248336.0   489232.0   3467.0   9622827.0
서울대학교병원             387248.0   632123.0   3998.0   9305580.0
근로복지공단              360473.0   402462.0   213.0    8149614.0
한국수자원공사             478153.0   287495.0   1820.0   7849413.0
국방과학연구소             385949.0   1823945.0  3488.0   7576098.0
한국농어촌공사             1153464.0  238221.0   4230.0   7213741.0
한국보훈복지의료공단          912320.0   504145.0   980.0    7029318.0
한국도로공사              1249583.0  363720.0  NaN       6820657.0
대한적십자사              13407.0    311224.0  NaN       6755867.0
한국산업은행              199222.0   194038.0   2963.0   6512978.0
한국가스공사             NaN        NaN         3509.0   6226338.0
신용보증기금              284605.0   3800.0     2100.0   6169977.0
부산대학교병원             203271.0   564287.0   3441.0   5886826.0
한국전자통신연구원          NaN         1175280.0  5281.0   5801601.0
전남대학교병원             355634.0   347448.0   3272.0   5633395.0
분당서울대학교병원           52148.0    551320.0  NaN       5483327.0
한국전기안전공사            24870.0    17963.0    2745.0   5333928.0
대한무역투자진흥공사          272920.0   58103.0    3418.0   5188605.0
그랜드코리아레저(주)         12760.0    262227.0   11318.0  5006434.0
한국원자력연구원           NaN         1037375.0  7000.0   4965877.0
한국석유공사              116616.0   40362.0    2300.0   4908880.0
...                     ...         ...       ...        ...
민주화운동기념사업회          671.0      0.0        190.0    32177.0
한국문학번역원             4318.0     7393.0     607.0    32146.0
재단법인 한국에너지재단       NaN         2385.0     1500.0   31342.0
한국해양조사협회           NaN         2567.0     0.0      31300.0
국립해양박물관            NaN         9752.0     416.0    30319.0
세종학당재단              11888.0    9339.0     300.0    29219.0
코레일네트웍스(주)          226827.0   127291.0   663.0    28661.0
한국에너지정보문화재단         0.0        1340.0     1096.0   27646.0
(재)한식진흥원           NaN         18192.0   NaN       27442.0
한국문화정보원             19231.0    4662.0     1105.0   27311.0
한국항로표지기술원           1574.0     0.0        0.0      24450.0
별정우체국연금관리단          4890.0     622.0      557.0    24180.0
국방전직교육원            NaN         8500.0     238.0    23405.0
코레일테크(주)           NaN         347646.0   1513.0   21361.0
재단법인 장애인기업종합지원센터   NaN         638.0      656.0    20388.0
(재)일제강제동원피해자지원재단    3765.0     845.0      100.0    17223.0
한국예술인복지재단          NaN         0.0        683.0    16479.0
한국보육진흥원             40.0       3275.0     240.0    16205.0
한국건강증진개발원           8969.0     26790.0    0.0      15991.0
(주)워터웨이플러스          3873.0     9439.0     893.0    15052.0
코레일로지스(주)           8404.0     4423.0     963.0    15032.0
한국지식재산연구원           702.0      6760.0    NaN       13097.0
소프트웨어정책연구소         NaN         1985.0    NaN       11710.0
사단법인 한국산학연협회        0.0        3652.0     522.0    10111.0
재단법인 한국장기조직기증원     NaN        NaN        NaN       9862.0
한국장애인개발원            19432.0    40740.0   NaN       7488.0
서울요양원               641.0      8691.0    NaN       2751.0
재단법인 한국여성과학기술인지원센터 NaN         1713.0     132.0    2672.0
(재)한국스마트그리드사업단      0.0        14.0       14.0     302.0
한국여성인권진흥원           32558.0    22754.0    589.0   NaN

[359 rows x 4 columns]

In [58]:
'''

'''
# df_pay.loc[df_pay['기관명']=='한국전력공사']
df_pay.loc[df_pay['기관명']=='한국철도공사']

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
4860,한국철도공사,공기업(준시장형),정규직_1인당_평균_보수액,61300.00,62338.00,68149.0,67766.00,67292.00,66168.00,천원,N
4861,한국철도공사,공기업(준시장형),정규직_기본급,35953.00,36733.00,38160.0,37141.00,39615.00,40645.00,천원,N
4862,한국철도공사,공기업(준시장형),정규직_고정수당,11104.00,11376.00,12325.0,11800.00,12475.00,12799.00,천원,N
4863,한국철도공사,공기업(준시장형),정규직_실적수당,8341.00,8014.00,7479.0,9041.00,6389.00,6556.00,천원,N
4864,한국철도공사,공기업(준시장형),정규직_급여성_복리후생비,981.00,993.00,997.0,997.00,994.00,1020.00,천원,N
4865,한국철도공사,공기업(준시장형),정규직_경영평가_성과급,0.00,0.00,4177.0,3541.00,2801.00,0.00,천원,N
4866,한국철도공사,공기업(준시장형),정규직_기타성과_상여금,4921.00,5222.00,5011.0,5246.00,5018.00,5148.00,천원,N
4867,한국철도공사,공기업(준시장형),정규직_상시종업원수,28652.00,27609.00,27019.0,26770.00,27061.00,28106.00,명,N
4868,한국철도공사,공기업(준시장형),정규직_평균근속연수,18.58,19.09,19.5,19.84,20.26,20.26,명,N
4869,한국철도공사,공기업(준시장형),정규직_1인당_평균_보수액_(남성),0.00,0.00,0.0,0.00,68315.00,67174.00,명,N
4870,한국철도공사,공기업(준시장형),정규직_1인당_평균_보수액_(여성),0.00,0.00,0.0,0.00,57492.00,56532.00,명,N
4871,한국철도공사,공기업(준시장형),정규직_상시종업원수_(남성),0.00,0.00,0.0,0.00,24503.00,25448.00,명,N
4872,한국철도공사,공기업(준시장형),정규직_상시종업원수_(여성),0.00,0.00,0.0,0.00,2558.00,2658.00,명,N
4873,한국철도공사,공기업(준시장형),정규직_평균근속연수_(남성),0.00,0.00,0.0,0.00,20.83,20.83,명,N
4874,한국철도공사,공기업(준시장형),정규직_평균근속연수_(여성),0.00,0.00,0.0,0.00,14.95,14.95,명,N

In [59]:
55651588.0 / 21019.23

2647.6511270869582

In [60]:
15855737 / 21019.23

754.3443313575236

In [61]:
# 기금 사용액, 정규직&비정규직 구분?
36068816 / 21019.23

1715.9913089109355

In [62]:
pd.set_option('display.max_rows', 50)
df_welf.groupby('항목').agg({'2017': 'sum'}).sort_values('2017', ascending=False)

                                                       2017
항목
복리후생비 > 예산상 복리후생비 > 급여성 > 선택적복지제도 > 정규직         154371144.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 정규직             80849597.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 정규직    62194126.0
복리후생비 > 예산상 복리후생비 > 급여성 > 학자금 > 정규직             61598298.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 정규직            42668639.0
복리후생비 > 예산상 복리후생비 > 급여성 > 기타 > 정규직              41517801.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 문화여가비 > 정규직          27742632.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 정규직          26591631.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 재해보상 및 재해부조 > 정규직    16756510.0
복리후생비 > 예산상 복리후생비 > 급여성 > 선택적복지제도 > 비정규직        16307489.0
복리후생비 > 예산상 복리후생비 > 급여성 > 기념품비 > 정규직            10979055.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 기념품비 > 정규직           9827649.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 선택적복지제도 > 정규직        9350421.0
복리후생비 > 예산상 복리후생비 > 급여성 > 선택적복지제도 > 무기계약직       8921921.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 정규직            5230799.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 비정규직   4852096.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 비정규직            4231225.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 의료비 및 건강검진비 > 무기계약직  3971935.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 무기계약직        3819451.0
복리후생비 > 예산상 복리후생비 > 급여성 > 의료비 및 건강검진비 > 정규직     2979568.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 기타 > 무기계약직           2569526.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 경조비 및 유족위로금 > 정규직    2410996.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 무기계약직          2191557.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 주택자금 > 정규직           2152000.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 행사지원비 > 비정규직         2019032.0
...                                                   ...
복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 무기계약직         4361.0
복리후생비 > 예산상 복리후생비 > 급여성 > 학자금 > 임원              4132.0
복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 비정규직          2747.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 비정규직           2484.0
복리후생비 > 예산상 복리후생비 > 급여성 > 문화여가비 > 임원            1132.0
복리후생비 > 예산상 복리후생비 > 급여성 > 경조비 및 유족위로금 > 임원      450.0
복리후생비 > 예산상 복리후생비 > 급여성 > 재해보상 및 재해부조 > 임원      359.0
복리후생비 > 예산상 복리후생비 > 급여성 > 주택자금 > 임원             353.0
복리후생비 > 예산상 복리후생비 > 급여성 > 행사지원비 > 임원            318.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 임원          0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 경로효친비 > 임원            0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 임원           0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 비정규직         0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 학자금 > 임원             0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 생활안정자금 > 무기계약직        0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 보육비 > 임원              0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 정규직         0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 보육비 > 임원             0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 생활안정자금 > 비정규직         0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 생활안정자금 > 임원           0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 정규직          0.0
복리후생비 > 예산상 복리후생비 > 급여성 > 주택자금 > 무기계약직          0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 무기계약직       0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 생활안정자금 > 비정규직        0.0
복리후생비 > 예산상 복리후생비 > 비급여성 > 경로효친비 > 무기계약직        0.0

[104 rows x 1 columns]

## Load Data: df_welfare

In [63]:
df_welfare = pd.read_csv(directory+file_names[17], sep='\t'); df_welfare.head()

   1인당 복리후생비   code            기관명    신분
0  347.0      C0847  (사)남북교류협력지원협회  임원
1  1346.0     C0847  (사)남북교류협력지원협회  정규직
2  1119.0     C0847  (사)남북교류협력지원협회  비정규직
3  2506.0     C0916  (재)국제원산지정보원    임원
4  2696.0     C0916  (재)국제원산지정보원    정규직

In [64]:
df_welfare_pivot = df_welfare.pivot(index='기관명', columns='신분', values=['1인당 복리후생비']); df_welfare_pivot.head()

              1인당 복리후생비
신분                무기계약직    비정규직      임원     정규직
기관명
(사)남북교류협력지원협회 NaN        1119.0  347.0   1346.0
(재)국제원산지정보원   NaN        2072.0  2506.0  2696.0
(재)예술경영지원센터    1046.0    845.0  NaN      1271.0
(재)우체국금융개발원    837.0     706.0  NaN      1028.0
(재)우체국물류지원단    717.0     344.0  NaN      2007.0

## **#정규직 복리후생 랭킹**

In [65]:
53340 / 47.42 + 858

1982.8418388865457

In [66]:
df_welfare_pivot.loc[(df_welfare_pivot.index=='국제식물검역인증원'), [('1인당 복리후생비', '정규직')]] = 1983
df_welfare_pivot.sort_values(('1인당 복리후생비', '정규직'), ascending=False)

                   1인당 복리후생비
신분                     무기계약직      비정규직        임원      정규직
기관명
한국법제연구원             2840.00   6559.00   972.00    6577.00
재단법인 대한건설기계안전관리원    3571.00   4450.00   13864.00  6168.00
대한무역투자진흥공사          4093.00   8669.00   488.00    5746.00
그랜드코리아레저(주)         4061.00   1662.00   1886.00   5516.00
한국국제협력단             2173.00   1927.00   1995.00   5489.00
주택도시보증공사            0.00      4256.00   534.00    5037.00
인천국제공항공사           NaN        597.00    382.00    5029.00
중소기업은행              5228.00   4042.00   3710.00   4982.00
한국관광공사              3205.00   1910.00   408.00    4931.00
(주)강원랜드             5015.00   2471.00   2251.00   4763.00
예금보험공사             NaN        1987.00   4063.00   4661.00
한국예탁결제원            NaN        3641.00   2815.00   4549.00
한국석유공사              3556.00   4237.00   434.00    4393.00
한국전력공사              0.00      2354.00  NaN        4370.00
한국국제보건의료재단         NaN        23363.00  60.00     4186.00
한국감정원               2669.00   3267.00  NaN        4155.00
에너지경제연구원            3075.00   337.00    5083.00   4149.00
한국토지주택공사            2913.00   1205.00   690.00    4143.00
한국지역난방공사            3936.00   3202.00   621.00    3933.00
기술보증기금              3345.00   1255.00   313.00    3890.00
부산항만공사              3696.00   2311.00   853.00    3827.00
한국광해관리공단            2409.00   2153.00   401.00    3765.00
한국주택금융공사            3351.00   2741.00   423.00    3661.00
한국무역보험공사            2006.00   1569.00   681.00    3655.00
울산항만공사              2891.00   0.00      868.00    3595.00
...                     ...       ...      ...        ...
도로교통공단              325.17    184.24    66.38     545.86
통일연구원               715.00    604.00    319.00    545.00
한국보건산업진흥원           441.00    327.00    37.00     526.00
코레일테크(주)           NaN        362.00    505.00    524.00
주식회사 인천항보안공사        369.00    249.00    282.00    507.00
한국교육과정평가원           403.00    302.00    347.00    501.00
한국디자인진흥원           NaN        274.00    0.00      486.00
환경보전협회              338.17    96.09    NaN        485.71
사단법인 한국기술자격검정원     NaN        37.00     330.00    481.00
사단법인 한국산학연협회        0.00      431.00    522.00    459.00
(주)워터웨이플러스          645.00    163.00    564.00    395.00
소프트웨어정책연구소         NaN        378.00   NaN        389.00
한국건강증진개발원           470.00    409.00    0.00      360.00
한국청소년활동진흥원          365.00    141.00    104.00    354.00
한국지식재산연구원           351.00    322.00   NaN        340.00
코레일네트웍스(주)          266.00    194.00    255.00    309.00
코레일로지스(주)           221.00    221.00    321.00    265.00
한국보육진흥원             2.00      46.00     240.00    231.00
재단법인 한국여성과학기술인지원센터 NaN        111.00    132.00    142.00
한국장애인개발원            389.00    215.00   NaN        136.00
코레일관광개발(주)          88.00     65.00     129.00    129.00
재단법인 한국장기조직기증원     NaN       NaN       NaN        102.00
서울요양원               70.00     118.00   NaN        91.00
(재)한국스마트그리드사업단      0.00      30.00     14.00     22.00
한국여성인권진흥원           766.00    571.00    786.00   NaN

[351 rows x 4 columns]

## Export: exp_welfare

In [67]:
exp_welfare = df_welfare_pivot.loc[::, [('1인당 복리후생비', '정규직')]]
exp_welfare.columns = exp_welfare.columns.droplevel(1)
exp_welfare.reset_index(inplace=True)

exp_welfare.head()

             기관명  1인당 복리후생비
0  (사)남북교류협력지원협회  1346.0
1  (재)국제원산지정보원    2696.0
2  (재)예술경영지원센터    1271.0
3  (재)우체국금융개발원    1028.0
4  (재)우체국물류지원단    2007.0

In [68]:
exp_welfare.mean()

1인당 복리후생비    1927.0944
dtype: float64

In [69]:
# exp_welfare.sort_values('1인당 복리후생비', ascending=False).head(15).to_csv(data_directory+'welfare.tsv', sep='\t', index=False)

## Merge: df_pay_compare

In [70]:
df_pay_pivot_rate_2018.head()

                          2018
항목            무기계약직_1인당_평균_보수액 정규직_1인당_평균_보수액 정규직_대비_무기계약직_보수_비율
기관명
(사)남북교류협력지원협회  49268.0          53752.0        91.657985
(재)예술경영지원센터    33262.0          44676.0        74.451607
(재)우체국금융개발원    30731.0          58645.0        52.401739
(재)우체국물류지원단    43034.0          51906.0        82.907564
(재)우체국시설관리단    47674.0          57728.0        82.583841

In [71]:
df_pay_pivot.head(1)

                          2013                                              \
항목            무기계약직_1인당_평균_보수액 무기계약직_1인당_평균_보수액_(남성) 무기계약직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회  0.0              0.0                   0.0

                                                                      \
항목            정규직_1인당_평균_보수액 정규직_1인당_평균_보수액_(남성) 정규직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회  46337.0        0.0                 0.0

                          2014                                              \
항목            무기계약직_1인당_평균_보수액 무기계약직_1인당_평균_보수액_(남성) 무기계약직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회  0.0              0.0                   0.0

                                    ...                          2018  \
항목            정규직_1인당_평균_보수액        ...         무기계약직_1인당_평균_보수액_(여성)
기관명                                 ...
(사)남북교류협력지원협회  47237.0              ...          46439.0

                                                                      \
항목            정규직_1인당_평균_보수액 정규직_1인당_평균_보수액_(남성) 정규직_1인당_평균_보수액_(여성)
기관명
(사)남북교류협력지원협회  53752.0        61398.0             35592.0

                            2013               2014               2015  \
항목            정규직_대비_무기계약직_보수_비율 정규직_대비_무기계약직_보수_비율 정규직_대비_무기계약직_보수_비율
기관명
(사)남북교류협력지원협회  0.0                0.0                0.0

                            2016               2017               2018
항목            정규직_대비_무기계약직_보수_비율 정규직_대비_무기계약직_보수_비율 정규직_대비_무기계약직_보수_비율
기관명
(사)남북교류협력지원협회  0.0                0.0                91.657985

[1 rows x 42 columns]

In [72]:
df_welfare_pivot.loc[::, [('1인당 복리후생비', '정규직'), ('1인당 복리후생비', '무기계약직')]].head()

              1인당 복리후생비
신분                  정규직   무기계약직
기관명
(사)남북교류협력지원협회  1346.0   NaN
(재)국제원산지정보원    2696.0   NaN
(재)예술경영지원센터    1271.0    1046.0
(재)우체국금융개발원    1028.0    837.0
(재)우체국물류지원단    2007.0    717.0

In [73]:
for y in col_year:
    df_pay_pivot[(y, '정규직_대비_무기계약직_보수_비율')] = df_pay_pivot[(y, col_pay[2])] / df_pay_pivot[(y, col_pay[5])] * 100

col_pay_rate = '정규직_대비_무기계약직_보수_비율'
idx_pay_pivot_not_zero = df_pay_pivot[('2018', '정규직_대비_무기계약직_보수_비율')] != 0
# df_pay_pivot[('2018', '정규직_대비_무기계약직_보수_비율')]



df_pay_pivot_rate_2018 = df_pay_pivot.loc[idx_pay_pivot_not_zero, [('2018', c) for c in [col_pay[2], col_pay[5], col_pay_rate]]]
df_pay_pivot_rate_2018.sort_values(('2018', col_pay_rate), ascending=True)

                            2018
항목              무기계약직_1인당_평균_보수액 정규직_1인당_평균_보수액 정규직_대비_무기계약직_보수_비율
기관명
전략물자관리원          3026.0           46762.0        6.471066
한국항로표지기술원        20131.0          67396.0        29.869725
예금보험공사           27326.0          84947.0        32.168293
한국마사회            29060.0          86834.0        33.466154
한국자산관리공사         27382.0          79620.0        34.390857
학교법인한국폴리텍        26109.0          73944.0        35.309153
동북아역사재단          24392.0          67860.0        35.944592
한국주택금융공사         31060.0          85653.0        36.262594
한국과학기술원          36381.0          99971.0        36.391554
한국세라믹기술원         33569.0          91399.0        36.727973
한국콘텐츠진흥원         22011.0          59571.0        36.949187
중소기업진흥공단         29272.0          78400.0        37.336735
기술보증기금           32499.0          86305.0        37.655987
국민연금공단           23993.0          63428.0        37.827143
한국남부발전(주)        31628.0          82495.0        38.339293
한국수산자원관리공단       29500.0          76680.0        38.471570
울산과학기술원          39878.0          103374.0       38.576431
서울올림픽기념국민체육진흥공단  26277.0          67506.0        38.925429
국민건강보험공단         23237.0          59392.0        39.124798
독립기념관            25124.0          63439.0        39.603399
한국체육산업개발(주)      23727.0          59743.0        39.715113
한국광물자원공사         29904.0          75117.0        39.809897
국토연구원            35248.0          86570.0        40.716183
한국산업안전보건공단       26608.0          65145.0        40.844270
한국무역보험공사         38432.0          91987.0        41.779817
...                  ...              ...              ...
한국예탁결제원          92143.0          111367.0       82.738154
(재)우체국물류지원단      43034.0          51906.0        82.907564
한국지역난방공사         61271.0          73744.0        83.086082
한국보건산업진흥원        56496.0          67303.0        83.942766
창업진흥원            51930.0          60859.0        85.328382
(주)워터웨이플러스       36947.0          42920.0        86.083411
국립광주과학관          49274.0          56907.0        86.586887
부산항만공사           63939.0          73532.0        86.953979
인천항만공사           64637.0          74279.0        87.019211
한국양성평등교육진흥원      46119.0          52285.0        88.206943
노사발전재단           41330.0          46519.0        88.845418
소상공인시장진흥공단       43386.0          47860.0        90.651901
코레일관광개발(주)       31480.0          34543.0        91.132791
사립학교교직원연금공단      58970.0          64379.0        91.598192
(사)남북교류협력지원협회    49268.0          53752.0        91.657985
한국인터넷진흥원         60520.0          65130.0        92.921849
국제방송교류재단         55537.0          58799.0        94.452287
한국어촌어항공단         46273.0          48898.0        94.631682
한국여성인권진흥원        40242.0          40242.0        100.000000
서울요양원            26094.0          26094.0        100.000000
울산항만공사           64060.0          63148.0        101.444226
여수광양항만공사         77461.0          75517.0        102.574255
한국사학진흥재단         54349.0          51845.0        104.829781
한국보건복지인력개발원      54419.0          46711.0        116.501466
한약진흥재단           270516.0         62816.0        430.648242

[298 rows x 3 columns]

## Merge: df_pay_total

In [74]:
df_pay.loc[df_pay['항목']=='정규직_급여성_복리후생비'].pivot(index='기관명', columns='항목', values=['2018'])

                           2018
항목                정규직_급여성_복리후생비
기관명
(사)남북교류협력지원협회      801.0
(재)APEC기후센터        0.0
(재)국제원산지정보원        0.0
(재)예술경영지원센터        877.0
(재)우체국금융개발원        858.0
(재)우체국물류지원단        1597.0
(재)우체국시설관리단        920.0
(재)일제강제동원피해자지원재단   915.0
(재)정동극장            1284.0
(재)중소기업연구원         1449.0
(재)한국스마트그리드사업단     1587.0
(재)한국우편사업진흥원       870.0
(재)한국형수치예보모델개발사업단  900.0
(재)한식진흥원           1192.0
(주)강원랜드            2895.0
(주)워터웨이플러스         395.0
(주)한국가스기술공사        1916.0
(주)한국건설관리공사        1168.0
88관광개발(주)          214.0
IOM이민정책연구원         2374.0
KDI국제정책대학원         910.0
가축위생방역지원본부         624.0
강릉원주대학교치과병원        53.0
강원대학교병원            451.0
건강보험심사평가원          422.0
...                 ...
한국특허전략개발원          1047.0
한국특허정보원            1499.0
한국표준과학연구원          2023.0
한국학중앙연구원           765.0
한국한의학연구원           1733.0
한국항공우주연구원          2129.0
한국항로표지기술원          879.0
한국해양과학기술원          1742.0
한국해양수산개발원          1200.0
한국해양수산연수원          648.0
한국해양조사협회           700.0
한국행정연구원            1402.0
한국형사정책연구원          1031.0
한국화학연구원            1489.0
한국환경공단             845.0
한국환경산업기술원          800.0
한국환경정책평가연구원        679.0
한약진흥재단             805.0
한전KDN              841.0
한전KPS(주)           1526.0
한전원자력연료주식회사        606.0
항공안전기술원            344.0
해양수산과학기술진흥원        1501.0
해양환경공단             1662.0
환경보전협회             0.0

[360 rows x 1 columns]

In [75]:
df_pay_total = df_pay_pivot.loc[::, [('2018', '정규직_1인당_평균_보수액')]].merge(df_welfare_pivot.loc[::, [('1인당 복리후생비', '정규직')]], left_index=True,
                                                                right_index=True, how='left')

df_pay_total = df_pay_total.merge(df_pay.loc[df_pay['항목']=='정규직_급여성_복리후생비'].pivot(index='기관명', columns='항목', values=['2018']),
                                 left_index=True, right_index=True, how='left')
df_pay_total.fillna(0, inplace=True)
df_pay_total
# .sort_values(('2018', col_pay[5]), ascending=False)

                            2018 1인당 복리후생비          2018
항목                정규직_1인당_평균_보수액       정규직 정규직_급여성_복리후생비
기관명
(사)남북교류협력지원협회      53752.0        1346.00   801.0
(재)APEC기후센터        60502.0        0.00      0.0
(재)국제원산지정보원        45164.0        2696.00   0.0
(재)예술경영지원센터        44676.0        1271.00   877.0
(재)우체국금융개발원        58645.0        1028.00   858.0
(재)우체국물류지원단        51906.0        2007.00   1597.0
(재)우체국시설관리단        57728.0        1430.00   920.0
(재)일제강제동원피해자지원재단   41458.0        783.00    915.0
(재)정동극장            53819.0        1504.00   1284.0
(재)중소기업연구원         72046.0        2248.00   1449.0
(재)한국스마트그리드사업단     58546.0        22.00     1587.0
(재)한국우편사업진흥원       51785.0        1197.00   870.0
(재)한국형수치예보모델개발사업단  79234.0        1352.00   900.0
(재)한식진흥원           63912.0        1306.00   1192.0
(주)강원랜드            72498.0        4763.00   2895.0
(주)워터웨이플러스         42920.0        395.00    395.0
(주)한국가스기술공사        70450.0        3147.15   1916.0
(주)한국건설관리공사        62856.0        1817.00   1168.0
88관광개발(주)          58678.0        0.00      214.0
IOM이민정책연구원         50888.0        0.00      2374.0
KDI국제정책대학원         88471.0        2309.00   910.0
가축위생방역지원본부         59802.0        1023.00   624.0
강릉원주대학교치과병원        42732.0        573.00    53.0
강원대학교병원            57930.0        1236.00   451.0
건강보험심사평가원          63251.0        1843.00   422.0
...                    ...           ...     ...
한국특허전략개발원          59136.0        1420.00   1047.0
한국특허정보원            54168.0        2111.00   1499.0
한국표준과학연구원          81179.0        3281.00   2023.0
한국학중앙연구원           66810.0        794.00    765.0
한국한의학연구원           77844.0        2631.00   1733.0
한국항공우주연구원          96623.0        3011.00   2129.0
한국항로표지기술원          67396.0        670.00    879.0
한국해양과학기술원          87010.0        2013.00   1742.0
한국해양수산개발원          77581.0        2216.00   1200.0
한국해양수산연수원          62714.0        963.00    648.0
한국해양조사협회           54351.0        720.00    700.0
한국행정연구원            70615.0        1752.00   1402.0
한국형사정책연구원          70606.0        2133.00   1031.0
한국화학연구원            81157.0        2710.00   1489.0
한국환경공단             57753.0        1422.00   845.0
한국환경산업기술원          67925.0        1313.78   800.0
한국환경정책평가연구원        70184.0        1276.00   679.0
한약진흥재단             62816.0        964.00    805.0
한전KDN              67662.0        3181.00   841.0
한전KPS(주)           76437.0        3195.00   1526.0
한전원자력연료주식회사        55923.0        3179.00   606.0
항공안전기술원            76392.0        861.00    344.0
해양수산과학기술진흥원        74732.0        1971.00   1501.0
해양환경공단             68845.0        2235.03   1662.0
환경보전협회             52486.0        485.71    0.0

[361 rows x 3 columns]

In [76]:
df_pay_total['종합연봉'] = df_pay_total[('2018', '정규직_1인당_평균_보수액')] + df_pay_total[('1인당 복리후생비', '정규직')] - df_pay_total[('2018', '정규직_급여성_복리후생비')]

print(len(df_pay_total))

print(df_pay_total.mean())
df_pay_total.head(15)

361
           항목
2018       정규직_1인당_평균_보수액    66810.759003
1인당 복리후생비  정규직               1863.910083
2018       정규직_급여성_복리후생비     1026.357341
종합연봉                         67648.311745
dtype: float64

                            2018 1인당 복리후생비          2018     종합연봉
항목                정규직_1인당_평균_보수액       정규직 정규직_급여성_복리후생비
기관명
(사)남북교류협력지원협회      53752.0        1346.0    801.0         54297.0
(재)APEC기후센터        60502.0        0.0       0.0           60502.0
(재)국제원산지정보원        45164.0        2696.0    0.0           47860.0
(재)예술경영지원센터        44676.0        1271.0    877.0         45070.0
(재)우체국금융개발원        58645.0        1028.0    858.0         58815.0
(재)우체국물류지원단        51906.0        2007.0    1597.0        52316.0
(재)우체국시설관리단        57728.0        1430.0    920.0         58238.0
(재)일제강제동원피해자지원재단   41458.0        783.0     915.0         41326.0
(재)정동극장            53819.0        1504.0    1284.0        54039.0
(재)중소기업연구원         72046.0        2248.0    1449.0        72845.0
(재)한국스마트그리드사업단     58546.0        22.0      1587.0        56981.0
(재)한국우편사업진흥원       51785.0        1197.0    870.0         52112.0
(재)한국형수치예보모델개발사업단  79234.0        1352.0    900.0         79686.0
(재)한식진흥원           63912.0        1306.0    1192.0        64026.0
(주)강원랜드            72498.0        4763.0    2895.0        74366.0

## **#종합연봉 랭킹**

In [77]:
exp_pay_total = df_pay_total.loc[::, ['종합연봉']].sort_values('종합연봉', ascending=False).reset_index()
exp_pay_total.columns = exp_pay_total.columns.droplevel(1)
exp_pay_total

                    기관명       종합연봉
0    한국예탁결제원             114836.00
1    한국전기연구원             105928.00
2    울산과학기술원             104039.00
3    한국전력국제원자력대학원대학교     104022.00
4    한국과학기술원             100335.00
5    한국원자력연구원            100084.00
6    광주과학기술원             99930.00
7    한국산업은행              98854.00
8    한국에너지기술연구원          98636.00
9    한국항공우주연구원           97505.00
10   선박해양플랜트연구소          97006.00
11   중소기업은행              97001.00
12   한국지질자원연구원           96020.24
13   국방과학연구소             95606.06
14   한국수출입은행             94826.00
15   한국조폐공사              94544.00
16   한국과학기술연구원           94487.00
17   대구경북과학기술원           93936.00
18   한국철도기술연구원           93533.00
19   한국무역보험공사            93434.00
20   에너지경제연구원            93197.00
21   한국전력거래소             93104.00
22   한국세라믹기술원            92484.00
23   한국건설기술연구원           91287.00
24   신용보증기금              90659.00
..      ...                   ...
336  한국문화정보원             46865.00
337  한국공예디자인문화진흥원        46791.00
338  식품안전정보원             46365.00
339  국제식물검역인증원           46273.00
340  재단법인 한국에너지재단        45846.00
341  한국청소년활동진흥원          45808.00
342  한국사회복지협의회           45704.00
343  태권도진흥재단             45606.00
344  국방전직교육원             45180.00
345  (재)예술경영지원센터         45070.00
346  한국문화예술교육진흥원         44741.00
347  한국기상산업기술원           43378.50
348  강릉원주대학교치과병원         43252.00
349  (주)워터웨이플러스          42920.00
350  한국예술인복지재단           42058.00
351  (재)일제강제동원피해자지원재단    41326.00
352  한국여성인권진흥원           40242.00
353  주택관리공단(주)           39381.00
354  코레일로지스(주)           39159.00
355  재단법인 한국여성과학기술인지원센터  38902.00
356  한국건강가정진흥원           38654.00
357  한국보육진흥원             37326.00
358  코레일관광개발(주)          34629.00
359  서울요양원               26185.00
360  사단법인 한국기술자격검정원      20736.00

[361 rows x 2 columns]

## Export: exp_pay_total

In [78]:
# exp_pay_total.head(15).to_csv(data_directory + 'pay_total.tsv', sep='\t', index=False)

# 손익계산서

## Load Data: df_gain

In [79]:
# 12~16
df_income = pd.DataFrame()
for i in range(18, 21):
    file_name = file_names[i]
    df_income = df_income.append(get_df_from_file(file_name))
    
df_income.head(1)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(주)강원랜드,공기업(시장형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 순매출,1361287.0,1496541.0,1633717.0,1696533.0,1604470.0,-,백만원,N

In [80]:
# df_income.pivot(index='기관명', columns='항목', values=col_year)
df_income['항목2'] = df_income['항목'].apply(lambda x: x.split(' > ')[-1].strip()); df_income.head()

df_income = df_income.drop_duplicates(['기관명', '항목2'], keep='first'); df_income.head()

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부,항목2
0,(주)강원랜드,공기업(시장형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 순매출,1361287.00,1496541.00,1633717.00,1696533.00,1604470.00,-,백만원,N,순매출
1,(주)강원랜드,공기업(시장형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 당기순이익,297596.00,359349.00,441629.00,454534.00,437541.00,-,백만원,N,당기순이익
2,(주)강원랜드,공기업(시장형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 매출액순이익률,21.86,24.01,27.03,26.79,27.27,-,명,N,매출액순이익률
6,국제방송교류재단,준정부기관(위탁집행형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 순매출,44223.00,43283.00,47491.00,48763.00,51577.00,-,백만원,N,순매출
7,국제방송교류재단,준정부기관(위탁집행형),요약손익계산서 > 고유사업 > 요약연결포괄손익계산서 > 당기순이익,-6383.00,-5710.00,-6500.00,-7660.00,-3588.00,-,백만원,N,당기순이익

In [81]:
# df_income.groupby(['기관명', '항목2']).count()
pivot_income = df_income.pivot(index='기관명', columns='항목2', values=col_year); pivot_income.head(1)

               2013                2014                2015                \
항목2           당기순이익 매출액순이익률   순매출 당기순이익 매출액순이익률   순매출 당기순이익 매출액순이익률   순매출
기관명
(사)남북교류협력지원협회 -5    -0.25    1975 -31   -1.58    2025  34    1.35    2523

               2016                2017                2018
항목2           당기순이익 매출액순이익률   순매출 당기순이익 매출액순이익률   순매출 당기순이익 매출액순이익률 순매출
기관명
(사)남북교류협력지원협회  90    3.24    2800 -2    -0.06    2966   -     -       -

In [82]:
# pivot_income.loc[::, [(c, '매출액순이익률') for c in col_year if c!='2018']]
# pivot_income['매출액순이익률_5년평균'] = (pivot_income[('2013', '매출액순이익률')] + pivot_income[('2014', '매출액순이익률')]
#                                +pivot_income[('2015', '매출액순이익률')]+pivot_income[('2016', '매출액순이익률')]
#                                +pivot_income[('2017', '매출액순이익률')])/5

pivot_income.replace(0, np.nan, inplace=True)
pivot_income['매출액순이익률_5년평균'] = pivot_income.loc[::, [(c, '매출액순이익률') for c in col_year if c!='2018']].mean(axis=1)

# pivot_income['매출액순이익률_5년평균'] = df_rcrt_new.mean(axis=1).to_frame(name=('평균', '')); mean_rcrt_new.head()

pivot_income.head()

                2013                    2014                    2015          \
항목2            당기순이익 매출액순이익률      순매출  당기순이익 매출액순이익률      순매출  당기순이익 매출액순이익률
기관명
(사)남북교류협력지원협회 -5.0   -0.25    1975.0  -31.0  -1.58    2025.0   34.0   1.35
(재)APEC기후센터   -372.0 -5.37    6928.0   307.0  3.90    7869.0  -337.0 -4.11
(재)국제원산지정보원    272.0  5.66    4803.0   279.0  6.27    4449.0   196.0  4.60
(재)예술경영지원센터    13.0   0.20    6479.0   10.0   0.10    10407.0  33.0   0.14
(재)우체국금융개발원    490.0  1.40    35113.0  13.0   0.04    36935.0  475.0  1.24

                          2016                     2017                   \
항목2                순매출   당기순이익 매출액순이익률      순매출   당기순이익 매출액순이익률      순매출
기관명
(사)남북교류협력지원협회  2523.0   90.0    3.24    2800.0  -2.0    -0.06    2966.0
(재)APEC기후센터    8191.0   571.0   6.33    9015.0   219.0   2.26    9704.0
(재)국제원산지정보원    4263.0   284.0   6.34    4480.0   499.0   9.55    5223.0
(재)예술경영지원센터    22882.0  20.0    0.09    21624.0  187.0   1.05    17735.0
(재)우체국금융개발원    38159.0  1316.0  3.26    40421.0  1061.0  2.46    43047.0

               2018             매출액순이익률_5년평균
항목2           당기순이익 매출액순이익률 순매출
기관명
(사)남북교류협력지원협회   -     -       -  0.540
(재)APEC기후센터     -     -       -  0.602
(재)국제원산지정보원     -     -       -  6.484
(재)예술경영지원센터     -     -       -  0.316
(재)우체국금융개발원     -     -       -  1.680

## **#매출액순이익률_5년평균**

In [83]:
col_income = [(c, '매출액순이익률') for c in col_year if c!='2018'] + [('매출액순이익률_5년평균', '')]
black_list = []
# black_list = ['한국소비자원', '한국감정원', '국토연구원']

pivot_income.loc[~pivot_income.index.isin(black_list), col_income].sort_values('매출액순이익률_5년평균', ascending=False)

                     2013    2014    2015    2016    2017 매출액순이익률_5년평균
항목2               매출액순이익률 매출액순이익률 매출액순이익률 매출액순이익률 매출액순이익률
기관명
예금보험공사             48.36   21.80   131.94  135.33  107.56  88.998000
한국소비자원             10.71   376.03 -13.36  -11.82  -15.23   69.266000
주택도시보증공사           26.76   52.93   35.01   54.10   69.20   47.600000
한국감정원              160.89  8.40    9.05    9.87    6.07    38.856000
사단법인 한국산학연협회       16.80   59.42   33.52   50.38   31.86   38.396000
인천국제공항공사           28.00   35.25   39.75   43.05   44.69   38.148000
국토연구원             -2.01    7.24    2.97    1.58    168.42  35.640000
한국도박문제관리센터         79.86   41.24   18.70   17.32   20.27   35.478000
울산항만공사             28.21   34.83   40.60   35.00   36.55   35.038000
한국예탁결제원            35.76   37.95   37.36   28.62   35.20   34.978000
재단법인 장애인기업종합지원센터   45.20   28.05   40.37   30.70   21.22   33.108000
부산항만공사             26.14   31.42   27.70   23.22   20.36   25.768000
(주)강원랜드            21.86   24.01   27.03   26.79   27.27   25.392000
한국뇌연구원             12.31   50.79   32.13   18.94   1.20    23.074000
서울요양원             NaN      89.02   4.25    1.12   -4.25    22.535000
한국광해관리공단           18.74   16.00   22.76   30.99   23.09   22.316000
국제식물검역인증원          28.60   22.83   25.42   9.10    23.92   21.974000
한국공항공사             18.84   22.77   23.17   22.91   21.49   21.836000
한국세라믹기술원           0.86    36.29   59.91   0.52    7.88    21.092000
한국소방산업기술원          16.31   20.23   19.51   22.72   22.66   20.286000
그랜드코리아레저(주)        24.51   21.55   18.14   20.86   16.07   20.226000
한국자산관리공사           12.66   18.98   27.02   31.90   10.22   20.156000
국립대구과학관            78.28   6.68    8.19    1.56    3.02    19.546000
건설근로자공제회           6.55    30.85   16.60   18.53   19.32   18.370000
국립부산과학관           NaN     NaN      25.35   11.53   16.91   17.930000
...                  ...    ...     ...     ...     ...          ...
IOM이민정책연구원        NaN     NaN     -26.90   4.20   -0.20   -7.633333
(재)한국형수치예보모델개발사업단 -5.95   -0.05   -10.69  -8.79   -14.06  -7.908000
산업연구원             -14.36  -7.61    0.15   -15.92  -2.24   -7.996000
한국전력국제원자력대학원대학교    60.03   18.54  -24.45  -77.55  -19.97  -8.680000
한국재정정보원           NaN     NaN     NaN     -12.65  -5.09   -8.870000
한약진흥재단            NaN     NaN     NaN     -13.67  -7.43   -10.550000
국제방송교류재단          -14.43  -13.19  -13.69  -15.71  -6.96   -12.796000
예술의전당             -11.32  -11.91  -7.87   -15.18  -24.59  -14.174000
동남권원자력의학원         -35.20  -23.46  -7.92   -6.76   -7.70   -16.208000
주식회사 공영홈쇼핑        NaN     NaN     -56.24  -8.03   -2.51   -22.260000
한국철도공사            -89.00  -6.64    1.57   -3.98   -14.78  -22.566000
한국나노기술원           -25.64  -37.13  -25.61  -19.80  -17.52  -25.140000
한국수자원공사            9.55    8.09   -153.43 -3.23    5.48   -26.708000
대한석탄공사            -38.24  -31.90  -35.87  -53.14  -57.81  -43.392000
주식회사 에스알          NaN     NaN     NaN     -109.12  5.54   -51.790000
한국석유공사            -13.59  -36.97  -131.08 -46.14  -31.73  -51.902000
항공안전기술원            37.96   9.75   -170.33 -83.80  -59.02  -53.088000
한국광물자원공사           5.78   -95.99  -692.65 -298.78 -56.80  -227.688000
신용보증재단중앙회         -457.74 -533.60 -454.03 -50.90   20.27  -295.200000
서민금융진흥원           NaN     NaN     NaN     -973.00 -626.00 -799.500000
가축위생방역지원본부        NaN     NaN     NaN     NaN     NaN     NaN
과학기술일자리진흥원        NaN     NaN     NaN     NaN     NaN     NaN
북한이탈주민지원재단        NaN     NaN     NaN     NaN     NaN     NaN
시청자미디어재단          NaN     NaN     NaN     NaN     NaN     NaN
한국법무보호복지공단        NaN     NaN     NaN     NaN     NaN     NaN

[351 rows x 6 columns]

In [84]:
pivot_income.loc[~pivot_income.index.isin(black_list), col_income].sort_values('매출액순이익률_5년평균', ascending=True).head(20)

                     2013    2014    2015    2016    2017 매출액순이익률_5년평균
항목2               매출액순이익률 매출액순이익률 매출액순이익률 매출액순이익률 매출액순이익률
기관명
서민금융진흥원           NaN     NaN     NaN     -973.00 -626.00 -799.500000
신용보증재단중앙회         -457.74 -533.60 -454.03 -50.90   20.27  -295.200000
한국광물자원공사           5.78   -95.99  -692.65 -298.78 -56.80  -227.688000
항공안전기술원            37.96   9.75   -170.33 -83.80  -59.02  -53.088000
한국석유공사            -13.59  -36.97  -131.08 -46.14  -31.73  -51.902000
주식회사 에스알          NaN     NaN     NaN     -109.12  5.54   -51.790000
대한석탄공사            -38.24  -31.90  -35.87  -53.14  -57.81  -43.392000
한국수자원공사            9.55    8.09   -153.43 -3.23    5.48   -26.708000
한국나노기술원           -25.64  -37.13  -25.61  -19.80  -17.52  -25.140000
한국철도공사            -89.00  -6.64    1.57   -3.98   -14.78  -22.566000
주식회사 공영홈쇼핑        NaN     NaN     -56.24  -8.03   -2.51   -22.260000
동남권원자력의학원         -35.20  -23.46  -7.92   -6.76   -7.70   -16.208000
예술의전당             -11.32  -11.91  -7.87   -15.18  -24.59  -14.174000
국제방송교류재단          -14.43  -13.19  -13.69  -15.71  -6.96   -12.796000
한약진흥재단            NaN     NaN     NaN     -13.67  -7.43   -10.550000
한국재정정보원           NaN     NaN     NaN     -12.65  -5.09   -8.870000
한국전력국제원자력대학원대학교    60.03   18.54  -24.45  -77.55  -19.97  -8.680000
산업연구원             -14.36  -7.61    0.15   -15.92  -2.24   -7.996000
(재)한국형수치예보모델개발사업단 -5.95   -0.05   -10.69  -8.79   -14.06  -7.908000
IOM이민정책연구원        NaN     NaN     -26.90   4.20   -0.20   -7.633333

In [85]:
exp_income_rate = pivot_income.loc[~pivot_income.index.isin(black_list), ['매출액순이익률_5년평균']].sort_values('매출액순이익률_5년평균', ascending=False).head(15); exp_income_rate
exp_income_rate.columns = exp_income_rate.columns.droplevel(0); exp_income_rate
exp_income_rate.rename(columns={'': '최근5년_평균_매출액순이익률'}, inplace=True); exp_income_rate
exp_income_rate.reset_index(inplace=True); exp_income_rate

항목2               기관명  최근5년_평균_매출액순이익률
0    예금보험공사            88.998
1    한국소비자원            69.266
2    주택도시보증공사          47.600
3    한국감정원             38.856
4    사단법인 한국산학연협회      38.396
5    인천국제공항공사          38.148
6    국토연구원             35.640
7    한국도박문제관리센터        35.478
8    울산항만공사            35.038
9    한국예탁결제원           34.978
10   재단법인 장애인기업종합지원센터  33.108
11   부산항만공사            25.768
12   (주)강원랜드           25.392
13   한국뇌연구원            23.074
14   서울요양원             22.535

## Export: exp_income_rate

In [86]:
# exp_income_rate.to_csv(data_directory+'income_rate.tsv', sep='\t', index=False)

In [87]:
df_income.loc[df_income['기관명']=='해양수산과학기술진흥원']

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부,항목2
327,해양수산과학기술진흥원,준정부기관(위탁집행형),요약손익계산서 > 고유사업 > 요약포괄손익계산서 > 순매출,0.0,286949.00,298203.0,269127.0,281698.0,-,백만원,N,순매출
328,해양수산과학기술진흥원,준정부기관(위탁집행형),요약손익계산서 > 고유사업 > 요약포괄손익계산서 > 당기순이익,0.0,43.00,903.0,541.0,268.0,-,백만원,N,당기순이익
329,해양수산과학기술진흥원,준정부기관(위탁집행형),요약손익계산서 > 고유사업 > 요약포괄손익계산서 > 매출액순이익률,0.0,0.02,0.3,0.2,0.1,-,명,N,매출액순이익률

In [88]:
org_income = set(df_income.groupby('기관명').count().index.tolist())

In [89]:
# 정보통신기술진흥센터 => 정보통신기획평가원
print(len(org_pay - org_income))
print(org_income - org_pay)
print(org_pay - org_income)

11
{'정보통신기획평가원'}
{'신용보증기금', '사립학교교직원연금공단', '태권도진흥재단', '기술보증기금', '한국사학진흥재단', '한국국제교류재단', '한국무역보험공사', '정보통신기술진흥센터', '공무원연금공단', '국방과학연구소', '중소기업진흥공단'}

# Test