# Import

In [ ]:
import os

# import unicodedata

import pandas as pd

# Files

In [2]:
directory = '/home/jake/Documents/ALIO/'
data_directory = directory + 'data/'
files = os.listdir(directory)

file_names = [
    '임직원.csv',  # 0

    '평균보수-정직원.csv',  # 1
    '평균보수-신입사원.csv',
    '평균보수-무기계약직.csv',
    
    '채용-신입.csv',  # 4
    '채용-청년인턴_유연근무.csv',
    
    '복리후생-예산-비급여-선택적_경로효친.csv',  # 6
    '복리후생-예산-급여-기념품_기타.csv',
    '복리후생-예산-급여-보육_선택적.csv',
    '복리후생-예산-비급여-문화여가_기타.csv',
    '복리후생-예산-비급여-보육_경조비.csv',
    '그밖의복리후생.csv',
    
    '기관장업무추진비.csv',  # 12
    '임원연봉-기관장_상임감사.csv',
    '임원연봉-상임이사.csv',
    '임원연봉-비상임감사.csv',
    '임원연봉-비상임이사.csv',
    
    'welfare.tsv',  # 17
    
    'loss_gain_connected.csv',  # 18
    'loss_gain_integrated.csv',
    'loss_gain_normal.csv',
]

# print(file_names)

# Functions

In [3]:
def get_raw_from_file(file_name):
    directory = '/home/jake/Documents/ALIO/'
    with open(directory + file_name, encoding='euckr') as f:
        head = f.readline()
        head = head.replace(' ', '')
        head = head.replace('2018단위', '2018,단위')
        body = f.read()
    raw = head + body
    return raw

def get_df_from_raw(raw, sep=','):
    from io import StringIO
    sio = StringIO(raw)
    df = pd.read_csv(sio, sep=sep)
    df['항목'] = df['항목'].apply(str.strip)
    return df

def get_df_from_file(file, sep=','):
    raw = get_raw_from_file(file)
    df = get_df_from_raw(raw, sep=sep)
    return df

# 비정규직

## Load Data: df_emp

In [4]:
df_emp = get_df_from_file(file_names[0]); df_emp.head(2)
df_emp['항목'] = df_emp['항목'].str.strip()
df_emp['부설기관여부'] = df_emp['부설기관여부'].str.strip(); df_emp.head(2)

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 상임 정원,1.0,1.0,1.0,1.0,1.0,1.0,명,N
1,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 비상임,0.0,0.0,0.0,0.0,0.0,0.0,명,N

## Index, Columns

In [5]:
idx_end_계 = (df_emp['항목'].str[-1]=='계')
idx_tmp = df_emp['항목'].isin(['임직원수 > 비정규직 > 비정규직 계', '임직원수 > 무기계약직 > 현원 > 계', '임직원수 > 소속외인력 > 소속외인력 계'])
idx_all = df_emp['항목'] == '임직원수 > 임직원 총계'
idx_woman = df_emp['항목'] == '임직원수 > 여성 현원'

col_year = ['2013', '2014', '2015', '2016', '2017', '2018']
col_general = ['기관명', '기관유형', '부설기관여부',]
cols = ['기관명', '기관유형', '부설기관여부', '2013', '2014', '2015', '2016', '2017', '2018']

In [6]:
# df_emp.loc[(df_emp['기관명']=='(사)남북교류협력지원협회') & (idx_tmp | idx_all)]
# df_emp.loc[(df_emp['기관명']=='전략물자관리원') & (idx_tmp | idx_all)]
# df_emp.loc[(df_emp['기관명']=='전략물자관리원')]
df_emp.loc[idx_woman]

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
34,(사)남북교류협력지원협회,기타공공기관,임직원수 > 여성 현원,4.00,4.000,9.00,8.00,7.500,11.000,명,N
73,(재)APEC기후센터,기타공공기관,임직원수 > 여성 현원,26.00,26.000,33.00,34.00,34.000,33.000,명,N
112,(재)국제원산지정보원,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,0.00,0.000,16.000,명,N
151,(재)예술경영지원센터,기타공공기관,임직원수 > 여성 현원,17.00,23.000,22.00,38.00,32.000,35.000,명,N
190,(재)우체국금융개발원,준정부기관(위탁집행형),임직원수 > 여성 현원,254.13,254.130,294.38,284.25,335.130,362.630,명,N
229,(재)우체국물류지원단,준정부기관(위탁집행형),임직원수 > 여성 현원,17.00,62.000,73.50,51.38,100.280,99.530,명,N
268,(재)우체국시설관리단,기타공공기관,임직원수 > 여성 현원,1153.00,1294.000,1347.00,1309.00,1292.000,1250.000,명,N
307,(재)일제강제동원피해자지원재단,기타공공기관,임직원수 > 여성 현원,0.00,3.000,5.00,5.00,7.000,14.000,명,N
346,(재)정동극장,기타공공기관,임직원수 > 여성 현원,24.00,27.000,13.00,12.00,23.000,21.000,명,N
385,(재)중소기업연구원,기타공공기관,임직원수 > 여성 현원,13.00,14.000,14.00,16.00,16.000,38.000,명,N
424,(재)한국스마트그리드사업단,기타공공기관,임직원수 > 여성 현원,2.00,2.000,4.00,7.00,7.000,5.000,명,N
463,(재)한국우편사업진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,117.50,126.875,132.50,166.25,231.500,256.250,명,N
502,(재)한국형수치예보모델개발사업단,기타공공기관,임직원수 > 여성 현원,35.00,24.000,25.00,25.00,36.000,35.000,명,N
541,(재)한식진흥원,기타공공기관,임직원수 > 여성 현원,7.00,12.000,12.00,15.00,11.000,21.000,명,N
580,(주)강원랜드,공기업(시장형),임직원수 > 여성 현원,875.00,936.000,936.00,935.00,1003.000,957.000,명,N
619,(주)워터웨이플러스,기타공공기관,임직원수 > 여성 현원,7.00,7.000,9.00,9.00,11.000,42.000,명,N
658,(주)한국가스기술공사,공기업(준시장형),임직원수 > 여성 현원,32.00,45.000,44.50,44.50,59.500,76.000,명,N
697,(주)한국건설관리공사,기타공공기관,임직원수 > 여성 현원,8.00,7.000,7.00,10.00,13.000,15.000,명,N
736,88관광개발(주),기타공공기관,임직원수 > 여성 현원,12.00,11.000,11.00,12.00,12.000,11.000,명,N
775,IOM이민정책연구원,기타공공기관,임직원수 > 여성 현원,8.00,8.000,12.00,12.00,15.000,12.000,명,N
814,KDI국제정책대학원,부설기관(한국개발연구원),임직원수 > 여성 현원,11.00,27.000,31.00,29.00,31.625,31.000,명,Y
853,가축위생방역지원본부,기타공공기관,임직원수 > 여성 현원,71.00,74.000,109.00,114.00,159.670,377.000,명,N
892,강릉원주대학교치과병원,기타공공기관,임직원수 > 여성 현원,62.00,57.000,63.00,66.00,72.000,84.000,명,N
931,강원대학교병원,기타공공기관,임직원수 > 여성 현원,456.00,478.000,494.00,617.00,724.000,764.000,명,N
970,건강보험심사평가원,준정부기관(위탁집행형),임직원수 > 여성 현원,1435.75,1621.250,1848.50,1916.75,2127.500,2312.000,명,N
1009,건설근로자공제회,기타공공기관,임직원수 > 여성 현원,17.00,17.000,21.00,23.00,37.500,42.500,명,N
1048,건축도시공간연구소,부설기관(국토연구원),임직원수 > 여성 현원,10.00,11.000,19.00,23.00,23.000,25.000,명,Y
1087,게임물관리위원회,기타공공기관,임직원수 > 여성 현원,5.00,5.000,9.00,11.00,23.000,21.000,명,N
1126,경북대학교병원,기타공공기관,임직원수 > 여성 현원,1572.00,1614.000,1732.00,1855.00,1934.000,2360.000,명,N
1165,경북대학교치과병원,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,64.00,69.000,77.000,명,N
...,...,...,...,...,...,...,...,...,...,...,...
12904,한국체육산업개발(주),기타공공기관,임직원수 > 여성 현원,81.00,81.000,104.00,132.80,132.000,537.260,명,N
12943,한국출판문화산업진흥원,기타공공기관,임직원수 > 여성 현원,19.00,19.000,20.75,24.75,44.750,43.000,명,N
12982,한국콘텐츠진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,60.00,53.500,61.75,96.25,121.250,127.500,명,N
13021,한국토지주택공사,공기업(준시장형),임직원수 > 여성 현원,1151.40,1061.400,1055.75,1214.25,2263.750,2559.125,명,N
13060,한국투자공사,기타공공기관,임직원수 > 여성 현원,40.00,51.000,57.00,66.00,76.500,79.000,명,N
13099,한국특허전략개발원,준정부기관(위탁집행형),임직원수 > 여성 현원,15.00,17.000,24.00,43.50,52.750,66.500,명,N
13138,한국특허정보원,기타공공기관,임직원수 > 여성 현원,76.00,87.000,109.00,144.75,156.000,159.000,명,N
13177,한국표준과학연구원,기타공공기관,임직원수 > 여성 현원,44.00,47.000,50.50,48.50,50.500,59.500,명,N
13216,한국학중앙연구원,기타공공기관,임직원수 > 여성 현원,63.00,66.000,66.00,67.00,79.000,100.500,명,N
13255,한국한의학연구원,기타공공기관,임직원수 > 여성 현원,48.00,56.000,61.00,61.00,59.000,54.750,명,N
13294,한국항공우주연구원,기타공공기관,임직원수 > 여성 현원,67.00,67.000,70.60,70.80,71.100,89.600,명,N
13333,한국항로표지기술원,기타공공기관,임직원수 > 여성 현원,6.00,6.000,6.00,7.00,6.000,10.000,명,N
13372,한국해양과학기술원,기타공공기관,임직원수 > 여성 현원,51.00,48.000,59.00,60.00,60.000,101.000,명,N
13411,한국해양수산개발원,기타공공기관,임직원수 > 여성 현원,32.00,39.000,48.00,52.00,56.000,85.000,명,N
13450,한국해양수산연수원,준정부기관(위탁집행형),임직원수 > 여성 현원,22.00,22.000,22.00,23.00,31.000,36.000,명,N
13489,한국해양조사협회,기타공공기관,임직원수 > 여성 현원,9.00,8.000,8.00,7.00,8.000,9.000,명,N
13528,한국행정연구원,기타공공기관,임직원수 > 여성 현원,16.00,19.000,19.00,25.00,26.000,47.000,명,N
13567,한국형사정책연구원,기타공공기관,임직원수 > 여성 현원,0.00,24.000,26.63,32.00,29.750,34.000,명,N
13606,한국화학연구원,기타공공기관,임직원수 > 여성 현원,61.00,63.000,64.00,69.00,77.000,78.000,명,N
13645,한국환경공단,준정부기관(위탁집행형),임직원수 > 여성 현원,337.00,413.500,459.38,526.00,525.180,664.000,명,N
13684,한국환경산업기술원,준정부기관(위탁집행형),임직원수 > 여성 현원,78.00,88.500,116.00,124.50,185.300,194.325,명,N
13723,한국환경정책평가연구원,기타공공기관,임직원수 > 여성 현원,42.00,45.000,54.00,65.00,63.000,64.000,명,N
13762,한약진흥재단,기타공공기관,임직원수 > 여성 현원,0.00,0.000,0.00,22.00,23.000,49.000,명,N
13801,한전KDN,공기업(준시장형),임직원수 > 여성 현원,124.50,127.500,157.50,169.50,186.500,210.000,명,N
13840,한전KPS(주),공기업(준시장형),임직원수 > 여성 현원,130.00,157.000,209.00,214.75,231.000,281.500,명,N
13879,한전원자력연료주식회사,기타공공기관,임직원수 > 여성 현원,60.00,69.000,71.00,67.00,68.000,72.625,명,N
13918,항공안전기술원,기타공공기관,임직원수 > 여성 현원,2.00,3.000,7.00,7.00,13.000,25.000,명,N
13957,해양수산과학기술진흥원,준정부기관(위탁집행형),임직원수 > 여성 현원,18.00,19.000,21.75,21.75,26.000,28.000,명,N
13996,해양환경공단,공기업(준시장형),임직원수 > 여성 현원,58.63,61.250,65.88,67.75,75.250,94.630,명,N
14035,환경보전협회,기타공공기관,임직원수 > 여성 현원,24.00,27.000,42.00,49.00,46.000,43.000,명,N

# 기관장 업무추진비

## Load Data: df_board, Index

In [51]:
# 12~16
df_board = pd.DataFrame()
for i in range(12, 17):
    df_board = df_board.append(get_df_from_file(file_names[i]))
    
df_board.head()

df_rcrt['항목'] = df_rcrt['항목'].apply(str.strip)
# df_rcrt['항목'] = df_rcrt['항목'].str.replace(' ', '_')

idx_board_sum = df_board['항목'].str.contains('합계')
idx_board_chief = df_board['항목'].str.contains('기관장업무추진비')

df_board.loc[idx_board_chief, '항목'] = df_board.loc[idx_board_chief]['항목'].str.replace(' > 집행내역', '')
df_board.loc[idx_board_chief].head()

df_board.loc[idx_board_sum, '항목'] = df_board.loc[idx_board_sum]['항목'].str.replace('임원연봉 > 비상임감사 > 합계 > ', '')
df_board.loc[idx_board_sum, '항목'] = df_board.loc[idx_board_sum]['항목'].str.replace('임원연봉 > 비상임이사 > 합계 > ', '')
df_board.loc[idx_board_sum, '항목'] = df_board.loc[idx_board_sum]['항목'].str.replace('임원연봉 > 상임감사 > 합계 > ', '')
df_board.loc[idx_board_sum, '항목'] = df_board.loc[idx_board_sum]['항목'].str.replace('임원연봉 > 상임기관장 > 합계 > ', '')
df_board.loc[idx_board_sum, '항목'] = df_board.loc[idx_board_sum]['항목'].str.replace('임원연봉 > 상임이사 > 합계 > ', '')

df_board.loc[idx_board_sum, '부설기관여부'] = df_board.loc[idx_board_sum]['부설기관여부'].str.strip()

df_board.loc[idx_board_sum].head()

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
6,(사)남북교류협력지원협회,기타공공기관,상임기관장,112553.0,110780.0,114917.0,123641.0,126193.0,118671,천원,N
13,(재)APEC기후센터,기타공공기관,상임기관장,158924.0,181120.0,181912.0,161250.0,174987.0,178537,천원,N
20,(재)국제원산지정보원,기타공공기관,상임기관장,117728.0,121436.0,127668.0,128041.0,131910.0,125306,천원,N
27,(재)예술경영지원센터,기타공공기관,상임기관장,73980.0,73980.0,85800.0,87945.0,87945.0,90847,천원,N
34,(재)우체국금융개발원,준정부기관(위탁집행형),상임기관장,148933.0,149748.0,127683.0,176788.0,181843.0,137889,천원,N

## Pivot

In [52]:
col_board = ['비상임감사', '비상임이사', '상임감사', '상임기관장', '상임이사']
df_pivot_board = df_board.loc[idx_board_sum | idx_board_chief].pivot(index='기관명', columns='항목', values=col_year)

In [53]:
col_board_year = [('2017', '기관장업무추진비'), ] + [('2018', c) for c in col_board]
df_pivot_board.loc[::, col_board_year]

                      2017   2018
항목                기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
(사)남북교류협력지원협회      7656     400    400    NaN     118671  NaN
(재)APEC기후센터        8547     800    1200   NaN     178537  NaN
(재)국제원산지정보원        4560     800    900    NaN     125306  NaN
(재)예술경영지원센터        3327     300    300    NaN     90847   NaN
(재)우체국금융개발원        0        2500   6700   NaN     137889  NaN
(재)우체국물류지원단        4197     2400   8400   NaN     135131  NaN
(재)우체국시설관리단        27097    1800   1800   NaN     137899  NaN
(재)일제강제동원피해자지원재단   2976     800    800    NaN     NaN     NaN
(재)정동극장            4079     600    600    NaN     96908   NaN
(재)중소기업연구원         9166     10000  1500   NaN     201200  NaN
(재)한국스마트그리드사업단     2802     900    900    NaN     130000  NaN
(재)한국우편사업진흥원       5665     0      0      NaN     138644  NaN
(재)한국형수치예보모델개발사업단  19631    13800  6600   NaN     253248  NaN
(재)한식진흥원           1635     NaN    31500  NaN     NaN     NaN
(주)강원랜드            5307     NaN    29210  NaN     137899  110319
(주)워터웨이플러스         7446     NaN    NaN    NaN     86448   69158
(주)한국가스기술공사        600      NaN    30000  90352   112940  90352
(주)한국건설관리공사        0        NaN    NaN    92871   103897  89661
88관광개발(주)          2124     NaN    0      123197  153996  123197
IOM이민정책연구원         4315     300    2700   NaN     120000  NaN
KDI국제정책대학원         5517     NaN    NaN    NaN     NaN     NaN
가축위생방역지원본부         17901    600    1200   NaN     64800   100485
강릉원주대학교치과병원        8199     NaN    280    82793   85004   NaN
강원대학교병원            2338     NaN    250    108604  162131  NaN
건강보험심사평가원          34685    NaN    5800   110319  137899  110319
건설근로자공제회           15609    NaN    2400   130942  137833  130942
건축도시공간연구소          28655    NaN    NaN    NaN     143893  NaN
게임물관리위원회           11527    NaN    16250  94649   119416  NaN
경북대학교병원            17082    NaN    1200   120479  122126  NaN
경북대학교치과병원          10000    NaN    400    94220   116322  NaN
...                  ...    ...      ...    ...      ...  ...
한국체육산업개발(주)        5961     NaN    2000   NaN     107752  NaN
한국출판문화산업진흥원        12708    3100   2100   NaN     123865  NaN
한국콘텐츠진흥원           18518    4500   4500   NaN     138644  110915
한국토지주택공사           510      NaN    30000  98424   123030  98424
한국투자공사             12172    NaN    NaN    165207  206509  165207
한국특허전략개발원          21608    2000   2000   NaN     137899  NaN
한국특허정보원            28051    1500   1500   NaN     137899  110319
한국표준과학연구원          10562    24000  NaN    NaN     162852  NaN
한국학중앙연구원           4582     3000   10500  NaN     152708  NaN
한국한의학연구원           12873    25300  NaN    NaN     158960  NaN
한국항공우주연구원          3052     NaN    NaN    151409  184827  NaN
한국항로표지기술원          5637     1200   1200   NaN     189002  151201
한국해양과학기술원          6278     NaN    1865   156910  168632  NaN
한국해양수산개발원          22727    13000  NaN    NaN     153271  NaN
한국해양수산연수원          9081     0      2000   NaN     134414  NaN
한국해양조사협회           1527     1200   1222   NaN     120314  0
한국행정연구원            33968    12600  NaN    NaN     112606  NaN
한국형사정책연구원          9570     12000  NaN    NaN     159203  NaN
한국화학연구원            10181    24000  NaN    NaN     160400  NaN
한국환경공단             39953    NaN    14040  104476  130594  104476
한국환경산업기술원          14643    12600  12336  NaN     137899  110319
한국환경정책평가연구원        7050     14000  NaN    NaN     147772  NaN
한약진흥재단             9934     500    12533  NaN     141588  NaN
한전KDN              4382     NaN    30000  107803  134753  107803
한전KPS(주)           2251     NaN    30000  107802  134753  107802
한전원자력연료주식회사        4598     NaN    30963  107800  134750  107800
항공안전기술원            13707    5500   5500   NaN     134157  NaN
해양수산과학기술진흥원        5699     3000   5400   NaN     137773  NaN
해양환경공단             161      30000  30000  NaN     137833  110266
환경보전협회             3589     1500   3750   NaN     NaN     125902

[357 rows x 6 columns]

## **#기관장업무추진비 랭킹**

In [54]:
'''
기관이 357개? 3개는 어딨지
'''
df_pivot_board.loc[::, col_board_year].sort_values(('2017', '기관장업무추진비'), ascending=False)

                     2017   2018
항목               기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
주식회사 공영홈쇼핑        51965    NaN    27600  136000  170000  119000
중소기업은행            43797    NaN    32000  164013  205017  155437
도로교통공단            41991    29640  26850  NaN     135131  108104
한국환경공단            39953    NaN    14040  104476  130594  104476
예술의전당             37087    21600  3071   NaN     125313  NaN
한국산업은행            35899    NaN    30000  154132  192664  146075
한국교육학술정보원         35547    2400   3600   NaN     137899  NaN
한국벤처투자            35521    NaN    NaN    128283  168429  NaN
한국과학기술원           35289    NaN    14085  164236  287600  NaN
건강보험심사평가원         34685    NaN    5800   110319  137899  110319
정보통신산업진흥원         34410    2100   4000   NaN     138644  NaN
한국정보화진흥원          34199    0      11442  NaN     137899  110319
한국행정연구원           33968    12600  NaN    NaN     112606  NaN
한국국방연구원           32671    14000  1200   NaN     177379  NaN
공무원연금공단           31046    NaN    8610   110244  137796  110244
국민건강보험공단          30965    NaN    2880   110319  137899  110319
한국고전번역원           30758    1500   1500   NaN     142630  NaN
한국건강가정진흥원         30651    1200   1200   NaN     111395  99475
사회보장정보원           29941    7200   12000  NaN     137899  110319
한국장애인개발원          29887    750    750    NaN     130620  NaN
근로복지공단            29677    NaN    6466   110319  137899  110319
국민연금공단            29382    NaN    7350   110319  137899  158189
한국문화진흥주식회사        29330    12400  NaN    0       169103  134700
국방기술품질원           29298    24900  900    NaN     171697  NaN
나노종합기술원           29258    NaN    NaN    NaN     179680  NaN
한국산업기술진흥원         29257    21000  16700  NaN     138584  NaN
건축도시공간연구소         28655    NaN    NaN    NaN     143893  NaN
사립학교교직원연금공단       28569    NaN    6000   110319  137899  109930
국립생태원             28463    12000  12000  NaN     131522  105218
국방과학연구소           28440    NaN    1600   125307  196219  NaN
...                 ...    ...     ...      ...     ...     ...
한국철도기술연구원         3136     24000  NaN    NaN     132807  NaN
신용보증기금            3126     NaN    30000  165477  206848  153121
재단법인 장애인기업종합지원센터  3076     0      1350   NaN     NaN     103272
한국항공우주연구원         3052     NaN    NaN    151409  184827  NaN
(재)일제강제동원피해자지원재단  2976     800    800    NaN     NaN     NaN
(재)한국스마트그리드사업단    2802     900    900    NaN     130000  NaN
한국전력기술주식회사        2674     NaN    30000  107800  134750  107800
한국저작권위원회          2642     4200   9600   NaN     128507  NaN
서울대학교치과병원         2566     NaN    2320   132123  143656  NaN
대한석탄공사            2431     NaN    30000  90386   112983  90386
강원대학교병원           2338     NaN    250    108604  162131  NaN
한전KPS(주)          2251     NaN    30000  107802  134753  107802
88관광개발(주)         2124     NaN    0      123197  153996  123197
국가수리과학연구소         1917     NaN    NaN    NaN     169845  NaN
국립암센터             1895     800    850    NaN     241690  NaN
한국보훈복지의료공단        1684     NaN    6333   106235  132771  112235
(재)한식진흥원          1635     NaN    31500  NaN     NaN     NaN
한국해양조사협회          1527     1200   1222   NaN     120314  0
한국디자인진흥원          1243     3000   2483   NaN     137899  NaN
재외동포재단            913      12000  0      NaN     126633  98426
한국조폐공사            669      NaN    30000  99913   124892  99240
(주)한국가스기술공사       600      NaN    30000  90352   112940  90352
한국토지주택공사          510      NaN    30000  98424   123030  98424
해양환경공단            161      30000  30000  NaN     137833  110266
(재)우체국금융개발원       0        2500   6700   NaN     137889  NaN
(주)한국건설관리공사       0        NaN    NaN    92871   103897  89661
대한장애인체육회          0        1000   900    NaN     NaN     114816
대한체육회             0        600    600    NaN     NaN     121691
한국상하수도협회          NaN      400    400    NaN     NaN     120600
한국수목원관리원          NaN      6000   6000   NaN     126835  NaN

[357 rows x 6 columns]

In [55]:
df_pivot_board.loc[::, col_board_year].sort_values(('2018', '상임기관장'), ascending=False)

                      2017   2018
항목                기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
기초과학연구원            13516    NaN    1091   174527  313007  NaN
한국과학기술원            35289    NaN    14085  164236  287600  NaN
(재)한국형수치예보모델개발사업단  19631    13800  6600   NaN     253248  NaN
국립중앙의료원            4398     900    1500   NaN     242519  NaN
국립암센터              1895     800    850    NaN     241690  NaN
울산과학기술원            23982    0      3000   139962  231483  NaN
국가과학기술연구회          13863    18000  5650   NaN     223300  NaN
기술보증기금             14191    NaN    30000  165478  206848  153114
신용보증기금             3126     NaN    30000  165477  206848  153121
중소기업진흥공단           24045    NaN    30000  165478  206848  144793
한국무역보험공사           13301    NaN    29852  165328  206660  144662
한국투자공사             12172    NaN    NaN    165207  206509  165207
한국자산관리공사           6194     NaN    30000  164825  206032  147738
한국주택금융공사           4700     NaN    30000  164660  205830  148210
예금보험공사             25835    NaN    30000  164018  205023  147699
중소기업은행             43797    NaN    32000  164013  205017  155437
한국장학재단             7340     NaN    7250   163779  204724  163779
농업정책보험금융원          22943    7000   2000   NaN     201445  NaN
(재)중소기업연구원         9166     10000  1500   NaN     201200  NaN
한국예탁결제원            18986    NaN    15000  159575  199468  159575
서울대학교병원            16580    NaN    4800   152749  197504  NaN
경제인문사회연구회          19356    12000  11963  NaN     196769  NaN
국방과학연구소            28440    NaN    1600   125307  196219  NaN
정부법무공단             12259    NaN    1200   NaN     193170  NaN
대구경북과학기술원          14047    0      1000   NaN     193143  NaN
광주과학기술원            14009    24000  900    NaN     193143  NaN
한국산업은행             35899    NaN    30000  154132  192664  146075
한국과학영재학교           11631    NaN    NaN    NaN     192604  NaN
한국수출입은행            15774    NaN    30000  153230  191538  142551
대구경북첨단의료산업진흥재단     17271    14400  600    NaN     190387  NaN
...                  ...    ...    ...    ...        ...  ...
한국공예디자인문화진흥원       7991     300    900    NaN     96804   NaN
재단법인 국악방송          8499     600    600    NaN     94648   NaN
한국여성인권진흥원          3500     600    600    NaN     91102   NaN
(재)예술경영지원센터        3327     300    300    NaN     90847   NaN
주택관리공단(주)          4403     NaN    NaN    72277   90347   72277
코레일로지스(주)          5513     28000  28000  NaN     90284   72227
코레일네트웍스(주)         13353    14800  14800  NaN     90284   72227
코레일유통(주)           7584     17400  17400  NaN     90284   72227
코레일테크(주)           4223     13600  13000  NaN     89756   71805
코레일관광개발(주)         3871     13200  13200  NaN     89751   71801
(주)워터웨이플러스         7446     NaN    NaN    NaN     86448   69158
강릉원주대학교치과병원        8199     NaN    280    82793   85004   NaN
한국문화정보원            3810     NaN    NaN    NaN     84240   NaN
가축위생방역지원본부         17901    600    1200   NaN     64800   100485
한국사회복지협의회          16375    400    592    NaN     36000   0
(재)일제강제동원피해자지원재단   2976     800    800    NaN     NaN     NaN
(재)한식진흥원           1635     NaN    31500  NaN     NaN     NaN
KDI국제정책대학원         5517     NaN    NaN    NaN     NaN     NaN
대한장애인체육회           0        1000   900    NaN     NaN     114816
대한체육회              0        600    600    NaN     NaN     121691
사단법인 한국산학연협회       16080    2720   17280  NaN     NaN     148837
소프트웨어정책연구소         15047    NaN    NaN    NaN     NaN     NaN
재단법인 장애인기업종합지원센터   3076     0      1350   NaN     NaN     103272
재단법인 한국에너지재단       8189     NaN    NaN    NaN     NaN     136171
정보통신기술진흥센터         12235    NaN    NaN    NaN     NaN     NaN
태권도진흥재단            6134     300    300    NaN     NaN     115719
한국국제보건의료재단         9621     1200   1200   NaN     NaN     128307
한국발명진흥회            19902    1000   1000   NaN     NaN     124109
한국상하수도협회           NaN      400    400    NaN     NaN     120600
환경보전협회             3589     1500   3750   NaN     NaN     125902

[357 rows x 6 columns]

## **#상임이사 연봉 랭킹**

In [56]:
df_pivot_board.loc[::, col_board_year].sort_values(('2018', '상임이사'), ascending=False)

                    2017   2018
항목              기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
한국투자공사           12172    NaN    NaN    165207  206509  165207
한국장학재단           7340     NaN    7250   163779  204724  163779
한국예탁결제원          18986    NaN    15000  159575  199468  159575
국민연금공단           29382    NaN    7350   110319  137899  158189
중소기업은행           43797    NaN    32000  164013  205017  155437
신용보증기금           3126     NaN    30000  165477  206848  153121
기술보증기금           14191    NaN    30000  165478  206848  153114
동북아역사재단          25760    600    200    NaN     160853  151264
한국항로표지기술원        5637     1200   1200   NaN     189002  151201
국립해양생물자원관        17996    3500   3125   NaN     187543  150034
사단법인 한국산학연협회     16080    2720   17280  NaN     NaN     148837
한국주택금융공사         4700     NaN    30000  164660  205830  148210
한국자산관리공사         6194     NaN    30000  164825  206032  147738
예금보험공사           25835    NaN    30000  164018  205023  147699
한국산업은행           35899    NaN    30000  154132  192664  146075
중소기업진흥공단         24045    NaN    30000  165478  206848  144793
한국무역보험공사         13301    NaN    29852  165328  206660  144662
한국수출입은행          15774    NaN    30000  153230  191538  142551
재단법인 한국에너지재단     8189     NaN    NaN    NaN     NaN     136171
대한법률구조공단         25513    1900   1900   NaN     142730  135435
한국문화진흥주식회사       29330    12400  NaN    0       169103  134700
국립해양박물관          9094     3000   12000  NaN     165916  132873
건설근로자공제회         15609    NaN    2400   130942  137833  130942
한국국제보건의료재단       9621     1200   1200   NaN     NaN     128307
한국문화재재단          16772    1800   1800   NaN     166002  128150
환경보전협회           3589     1500   3750   NaN     NaN     125902
한국발명진흥회          19902    1000   1000   NaN     NaN     124109
88관광개발(주)        2124     NaN    0      123197  153996  123197
대한체육회            0        600    600    NaN     NaN     121691
한국전력공사           7574     NaN    30000  122006  152508  120976
...               ...     ...   ..         ...     ...     ...
한국저작권보호원         5596     1800   667    NaN     126325  NaN
한국저작권위원회         2642     4200   9600   NaN     128507  NaN
한국전기연구원          9243     24000  NaN    NaN     165830  NaN
한국전력국제원자력대학원대학교  4669     10000  10000  NaN     137652  NaN
한국전자통신연구원        6334     NaN    NaN    156790  185408  NaN
한국조세재정연구원        11969    12000  NaN    NaN     148693  NaN
한국지식재산연구원        17693    600    600    NaN     137899  NaN
한국지질자원연구원        17277    25850  NaN    NaN     162702  NaN
한국직업능력개발원        20686    12000  NaN    NaN     146056  NaN
한국천문연구원          11815    24360  NaN    NaN     155780  NaN
한국철도기술연구원        3136     24000  NaN    NaN     132807  NaN
한국청소년상담복지개발원     18599    900    900    NaN     110563  NaN
한국청소년정책연구원       12623    12000  NaN    NaN     110126  NaN
한국체육산업개발(주)      5961     NaN    2000   NaN     107752  NaN
한국출판문화산업진흥원      12708    3100   2100   NaN     123865  NaN
한국특허전략개발원        21608    2000   2000   NaN     137899  NaN
한국표준과학연구원        10562    24000  NaN    NaN     162852  NaN
한국학중앙연구원         4582     3000   10500  NaN     152708  NaN
한국한의학연구원         12873    25300  NaN    NaN     158960  NaN
한국항공우주연구원        3052     NaN    NaN    151409  184827  NaN
한국해양과학기술원        6278     NaN    1865   156910  168632  NaN
한국해양수산개발원        22727    13000  NaN    NaN     153271  NaN
한국해양수산연수원        9081     0      2000   NaN     134414  NaN
한국행정연구원          33968    12600  NaN    NaN     112606  NaN
한국형사정책연구원        9570     12000  NaN    NaN     159203  NaN
한국화학연구원          10181    24000  NaN    NaN     160400  NaN
한국환경정책평가연구원      7050     14000  NaN    NaN     147772  NaN
한약진흥재단           9934     500    12533  NaN     141588  NaN
항공안전기술원          13707    5500   5500   NaN     134157  NaN
해양수산과학기술진흥원      5699     3000   5400   NaN     137773  NaN

[357 rows x 6 columns]

## **#비상임이사**

In [57]:
df_pivot_board.loc[::, col_board_year].sort_values(('2018', '비상임이사'), ascending=False)

                2017   2018
항목          기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
중소기업은행       43797    NaN    32000  164013  205017  155437
(재)한식진흥원     1635     NaN    31500  NaN     NaN     NaN
한전원자력연료주식회사  4598     NaN    30963  107800  134750  107800
한국광해관리공단     12933    30000  30000  NaN     133141  106512
한국남부발전(주)    11252    30000  30000  109942  137428  109942
한국조폐공사       669      NaN    30000  99913   124892  99240
대한석탄공사       2431     NaN    30000  90386   112983  90386
한국주택금융공사     4700     NaN    30000  164660  205830  148210
한국가스공사       21385    NaN    30000  110319  137899  110319
한국중부발전(주)    4887     NaN    30000  109299  136624  109299
한국마사회        19523    NaN    30000  102483  127990  102483
한국동서발전(주)    4324     30000  30000  109942  137428  109942
한국도로공사       7023     NaN    30000  96952   121191  96952
한국시설안전공단     24679    30000  30000  NaN     129374  103499
한국농어촌공사      28322    NaN    30000  95829   119786  95829
한국토지주택공사     510      NaN    30000  98424   123030  98424
한국수자원공사      3956     NaN    30000  96990   121242  96990
한국남동발전(주)    9961     30000  30000  109942  137428  109942
한국국토정보공사     23194    NaN    30000  110915  138644  110915
그랜드코리아레저(주)  23264    NaN    30000  110319  137899  110319
한국교통안전공단     6435     30000  30000  NaN     137899  110319
기술보증기금       14191    NaN    30000  165478  206848  153114
한국광물자원공사     16650    NaN    30000  91829   114787  91829
한국지역난방공사     12057    NaN    30000  104520  130650  104520
한국공항공사       14091    NaN    30000  103902  129878  101447
한국철도공사       5407     NaN    30000  95090   118863  95090
한국철도시설공단     16525    NaN    30000  104664  130824  102571
한국전력기술주식회사   2674     NaN    30000  107800  134750  107800
한국수출입은행      15774    NaN    30000  153230  191538  142551
서민금융진흥원      12380    NaN    30000  114050  143050  114050
...           ...     ...      ...     ...     ...     ...
한국문화정보원      3810     NaN    NaN    NaN     84240   NaN
한국문화진흥주식회사   29330    12400  NaN    0       169103  134700
한국법무보호복지공단   14132    NaN    NaN    NaN     150394  NaN
한국법제연구원      8992     12000  NaN    NaN     136324  NaN
한국벤처투자       35521    NaN    NaN    128283  168429  NaN
한국보건사회연구원    23361    12000  NaN    NaN     137086  NaN
한국생명공학연구원    20420    25731  NaN    NaN     166178  NaN
한국생산기술연구원    10937    24000  NaN    NaN     157912  NaN
한국식품연구원      18255    24000  NaN    NaN     164540  NaN
한국에너지기술연구원   10768    25990  NaN    NaN     162842  NaN
한국에너지기술평가원   20204    NaN    NaN    NaN     137899  NaN
한국여성정책연구원    13473    12000  NaN    NaN     134901  NaN
한국원자력연구원     18877    NaN    NaN    152582  186375  NaN
한국전기연구원      9243     24000  NaN    NaN     165830  NaN
한국전자통신연구원    6334     NaN    NaN    156790  185408  NaN
한국조세재정연구원    11969    12000  NaN    NaN     148693  NaN
한국지질자원연구원    17277    25850  NaN    NaN     162702  NaN
한국직업능력개발원    20686    12000  NaN    NaN     146056  NaN
한국천문연구원      11815    24360  NaN    NaN     155780  NaN
한국철도기술연구원    3136     24000  NaN    NaN     132807  NaN
한국청소년정책연구원   12623    12000  NaN    NaN     110126  NaN
한국투자공사       12172    NaN    NaN    165207  206509  165207
한국표준과학연구원    10562    24000  NaN    NaN     162852  NaN
한국한의학연구원     12873    25300  NaN    NaN     158960  NaN
한국항공우주연구원    3052     NaN    NaN    151409  184827  NaN
한국해양수산개발원    22727    13000  NaN    NaN     153271  NaN
한국행정연구원      33968    12600  NaN    NaN     112606  NaN
한국형사정책연구원    9570     12000  NaN    NaN     159203  NaN
한국화학연구원      10181    24000  NaN    NaN     160400  NaN
한국환경정책평가연구원  7050     14000  NaN    NaN     147772  NaN

[357 rows x 6 columns]

## **#상임감사**

In [58]:
df_pivot_board.loc[::, col_board_year].sort_values(('2018', '상임감사'), ascending=False)

                 2017   2018
항목           기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
기초과학연구원       13516    NaN    1091   174527  313007  NaN
기술보증기금        14191    NaN    30000  165478  206848  153114
중소기업진흥공단      24045    NaN    30000  165478  206848  144793
신용보증기금        3126     NaN    30000  165477  206848  153121
한국무역보험공사      13301    NaN    29852  165328  206660  144662
한국투자공사        12172    NaN    NaN    165207  206509  165207
한국자산관리공사      6194     NaN    30000  164825  206032  147738
한국주택금융공사      4700     NaN    30000  164660  205830  148210
한국과학기술원       35289    NaN    14085  164236  287600  NaN
예금보험공사        25835    NaN    30000  164018  205023  147699
중소기업은행        43797    NaN    32000  164013  205017  155437
한국장학재단        7340     NaN    7250   163779  204724  163779
한국예탁결제원       18986    NaN    15000  159575  199468  159575
한국해양과학기술원     6278     NaN    1865   156910  168632  NaN
한국전자통신연구원     6334     NaN    NaN    156790  185408  NaN
한국산업은행        35899    NaN    30000  154132  192664  146075
한국수출입은행       15774    NaN    30000  153230  191538  142551
서울대학교병원       16580    NaN    4800   152749  197504  NaN
한국원자력연구원      18877    NaN    NaN    152582  186375  NaN
한국항공우주연구원     3052     NaN    NaN    151409  184827  NaN
한국과학기술연구원     17674    NaN    NaN    147776  171808  NaN
울산과학기술원       23982    0      3000   139962  231483  NaN
주식회사 공영홈쇼핑    51965    NaN    27600  136000  170000  119000
서울대학교치과병원     2566     NaN    2320   132123  143656  NaN
건설근로자공제회      15609    NaN    2400   130942  137833  130942
한국벤처투자        35521    NaN    NaN    128283  168429  NaN
국방과학연구소       28440    NaN    1600   125307  196219  NaN
충남대학교병원       10486    NaN    658    124636  135414  NaN
부산대학교병원       11792    NaN    0      124276  137556  NaN
88관광개발(주)     2124     NaN    0      123197  153996  123197
...             ...    ...    ...       ...     ...  ...
한국지식재산연구원     17693    600    600    NaN     137899  NaN
한국지질자원연구원     17277    25850  NaN    NaN     162702  NaN
한국직업능력개발원     20686    12000  NaN    NaN     146056  NaN
한국천문연구원       11815    24360  NaN    NaN     155780  NaN
한국철도기술연구원     3136     24000  NaN    NaN     132807  NaN
한국청소년상담복지개발원  18599    900    900    NaN     110563  NaN
한국청소년정책연구원    12623    12000  NaN    NaN     110126  NaN
한국청소년활동진흥원    15544    550    1500   NaN     112676  90141
한국체육산업개발(주)   5961     NaN    2000   NaN     107752  NaN
한국출판문화산업진흥원   12708    3100   2100   NaN     123865  NaN
한국콘텐츠진흥원      18518    4500   4500   NaN     138644  110915
한국특허전략개발원     21608    2000   2000   NaN     137899  NaN
한국특허정보원       28051    1500   1500   NaN     137899  110319
한국표준과학연구원     10562    24000  NaN    NaN     162852  NaN
한국학중앙연구원      4582     3000   10500  NaN     152708  NaN
한국한의학연구원      12873    25300  NaN    NaN     158960  NaN
한국항로표지기술원     5637     1200   1200   NaN     189002  151201
한국해양수산개발원     22727    13000  NaN    NaN     153271  NaN
한국해양수산연수원     9081     0      2000   NaN     134414  NaN
한국해양조사협회      1527     1200   1222   NaN     120314  0
한국행정연구원       33968    12600  NaN    NaN     112606  NaN
한국형사정책연구원     9570     12000  NaN    NaN     159203  NaN
한국화학연구원       10181    24000  NaN    NaN     160400  NaN
한국환경산업기술원     14643    12600  12336  NaN     137899  110319
한국환경정책평가연구원   7050     14000  NaN    NaN     147772  NaN
한약진흥재단        9934     500    12533  NaN     141588  NaN
항공안전기술원       13707    5500   5500   NaN     134157  NaN
해양수산과학기술진흥원   5699     3000   5400   NaN     137773  NaN
해양환경공단        161      30000  30000  NaN     137833  110266
환경보전협회        3589     1500   3750   NaN     NaN     125902

[357 rows x 6 columns]

## **#비상임감사**

In [59]:
df_pivot_board.loc[::, col_board_year].sort_values(('2018', '비상임감사'), ascending=False)

                2017   2018
항목          기관장업무추진비  비상임감사  비상임이사    상임감사   상임기관장    상임이사
기관명
한국소방산업기술원    7794     32500  14500  NaN     121039  96831
한국국제협력단      10664    30000  0      NaN     137914  108422
한국광해관리공단     12933    30000  30000  NaN     133141  106512
한국시설안전공단     24679    30000  30000  NaN     129374  103499
한국남동발전(주)    9961     30000  30000  109942  137428  109942
한국남부발전(주)    11252    30000  30000  109942  137428  109942
한국동서발전(주)    4324     30000  30000  109942  137428  109942
한국원자력안전기술원   21238    30000  3803   NaN     137899  NaN
한국교통안전공단     6435     30000  30000  NaN     137899  110319
한국세라믹기술원     15777    30000  9000   NaN     137899  NaN
한국원자력통제기술원   20951    30000  1800   NaN     165823  NaN
한국원자력환경공단    21337    30000  17800  NaN     122170  97736
한국산업단지공단     23680    30000  24000  NaN     137899  110319
해양환경공단       161      30000  30000  NaN     137833  110266
도로교통공단       41991    29640  26850  NaN     135131  108104
코레일로지스(주)    5513     28000  28000  NaN     90284   72227
한국재정정보원      23859    27600  27600  NaN     137899  110319
한국과학기술기획평가원  8127     26250  1975   NaN     176144  NaN
한국에너지기술연구원   10768    25990  NaN    NaN     162842  NaN
한국지질자원연구원    17277    25850  NaN    NaN     162702  NaN
한국과학창의재단     6000     25800  1800   NaN     138644  NaN
한국생명공학연구원    20420    25731  NaN    NaN     166178  NaN
한국과학기술정보연구원  13674    25450  NaN    NaN     156302  NaN
한국한의학연구원     12873    25300  NaN    NaN     158960  NaN
한국기초과학지원연구원  8036     25000  NaN    NaN     156572  NaN
한국산업기술시험원    7666     24900  12900  NaN     137899  NaN
독립기념관        9756     24900  1500   NaN     117100  NaN
국방기술품질원      29298    24900  900    NaN     171697  NaN
한국원자력안전재단    12693    24400  400    NaN     136559  NaN
한국천문연구원      11815    24360  NaN    NaN     155780  NaN
...            ...      ...  ...    ...        ...  ...
한국수력원자력(주)   9380     NaN    30000  NaN     138060  110574
한국수자원공사      3956     NaN    30000  96990   121242  96990
한국수출입은행      15774    NaN    30000  153230  191538  142551
한국에너지공단      23875    NaN    24960  110319  137899  107009
한국에너지기술평가원   20204    NaN    NaN    NaN     137899  NaN
한국연구재단       23116    NaN    6569   110217  137772  NaN
한국예탁결제원      18986    NaN    15000  159575  199468  159575
한국원자력연구원     18877    NaN    NaN    152582  186375  NaN
한국원자력의학원     14702    NaN    1429   122479  169404  NaN
한국자산관리공사     6194     NaN    30000  164825  206032  147738
한국장학재단       7340     NaN    7250   163779  204724  163779
한국전기안전공사     14412    NaN    27600  110916  138644  108412
한국전력공사       7574     NaN    30000  122006  152508  120976
한국전력기술주식회사   2674     NaN    30000  107800  134750  107800
한국전자통신연구원    6334     NaN    NaN    156790  185408  NaN
한국조폐공사       669      NaN    30000  99913   124892  99240
한국주택금융공사     4700     NaN    30000  164660  205830  148210
한국중부발전(주)    4887     NaN    30000  109299  136624  109299
한국지역난방공사     12057    NaN    30000  104520  130650  104520
한국철도공사       5407     NaN    30000  95090   118863  95090
한국철도시설공단     16525    NaN    30000  104664  130824  102571
한국체육산업개발(주)  5961     NaN    2000   NaN     107752  NaN
한국토지주택공사     510      NaN    30000  98424   123030  98424
한국투자공사       12172    NaN    NaN    165207  206509  165207
한국항공우주연구원    3052     NaN    NaN    151409  184827  NaN
한국해양과학기술원    6278     NaN    1865   156910  168632  NaN
한국환경공단       39953    NaN    14040  104476  130594  104476
한전KDN        4382     NaN    30000  107803  134753  107803
한전KPS(주)     2251     NaN    30000  107802  134753  107802
한전원자력연료주식회사  4598     NaN    30963  107800  134750  107800

[357 rows x 6 columns]

# 임원 수

In [62]:

print('---1. 비상임기관장')
tmp_chief = set(df_emp.loc[(df_emp['항목'].str.contains('기관장 > 비상임')) & (df_emp['2018']!= 0.0)]['기관명'].tolist())
print(len(tmp_chief))
print(tmp_chief)  # 비상임기관장

print()
print('---2. 상임 기관장 == 1')
perm_chief = set(df_emp.loc[(df_emp['항목'].str.contains('기관장 > 상임 현원')) & (df_emp['2018']== 1.0)]['기관명'].tolist())
print(len(perm_chief))

print()
print('---2. 상임 기관장 == 0')
perm_chief_zero = set(df_emp.loc[(df_emp['항목'].str.contains('기관장 > 상임 현원')) & (df_emp['2018']== 0.0)]['기관명'].tolist())
print(len(perm_chief_zero))


print()
print('---3. 기관장 정원 == 0')
perm_chief_empty_position = set(df_emp.loc[(df_emp['항목'].str.contains('기관장 > 상임 정원')) & (df_emp['2018']==0.0)]['기관명'].tolist())
print(len(perm_chief_empty_position))
print(perm_chief_empty_position)

print()
print('---4. 정원0 - 부속')
print(len(perm_chief_empty_position - sub_org_emp))
print(perm_chief_empty_position - sub_org_emp)
# sub_org_board - set(perm_chief_empty_position)

df_emp.head(40)

---1. 비상임기관장
16
{'사단법인 한국산학연협회', '가축위생방역지원본부', '민주화운동기념사업회', '(재)일제강제동원피해자지원재단', '환경보전협회', '(재)한식진흥원', '한국발명진흥회', '태권도진흥재단', '재단법인 한국에너지재단', '한국국제보건의료재단', '한국사회복지협의회', '대한장애인체육회', '한국상하수도협회', '대한적십자사', '대한체육회', '재단법인 장애인기업종합지원센터'}

---2. 상임 기관장 == 1
310

---2. 상임 기관장 == 0
50

---3. 기관장 정원 == 0
24
{'가축위생방역지원본부', '민주화운동기념사업회', '(재)한식진흥원', '한국국제보건의료재단', '대한장애인체육회', '사단법인 한국산학연협회', '분당서울대학교병원', '재단법인 한국에너지재단', '한국상하수도협회', '대한적십자사', '국민건강보험공단 일산병원', '환경보전협회', '(재)일제강제동원피해자지원재단', '서울요양원', '정보통신기술진흥센터', '한국발명진흥회', '한국사회복지협의회', '주식회사 인천항보안공사', '대한체육회', '동남권원자력의학원', '태권도진흥재단', 'KDI국제정책대학원', '소프트웨어정책연구소', '재단법인 장애인기업종합지원센터'}

---4. 정원0 - 부속
17
{'사단법인 한국산학연협회', '가축위생방역지원본부', '민주화운동기념사업회', '환경보전협회', '(재)일제강제동원피해자지원재단', '(재)한식진흥원', '한국발명진흥회', '태권도진흥재단', '재단법인 한국에너지재단', '한국국제보건의료재단', '한국사회복지협의회', '대한장애인체육회', '한국상하수도협회', '대한적십자사', '주식회사 인천항보안공사', '대한체육회', '재단법인 장애인기업종합지원센터'}

,기관명,기관유형,항목,2013,2014,2015,2016,2017,2018,단위,부설기관여부
0,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 상임 정원,1.0,1.0,1.0,1.0,1.0,1.0,명,N
1,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 비상임,0.0,0.0,0.0,0.0,0.0,0.0,명,N
2,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기관장 > 상임 현원,1.0,1.0,1.0,1.0,1.0,1.0,명,N
3,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 이사 > 상임 정원,1.0,1.0,1.0,1.0,1.0,1.0,명,N
4,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 이사 > 비상임,9.0,7.0,7.0,6.0,6.0,9.0,명,N
5,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 이사 > 상임 현원,0.0,0.0,0.0,0.0,0.0,0.0,명,N
6,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 감사 > 상임 정원,0.0,0.0,0.0,0.0,0.0,0.0,명,N
7,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 감사 > 비상임,1.0,1.0,1.0,1.0,1.0,1.0,명,N
8,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 감사 > 상임 현원,0.0,0.0,0.0,0.0,0.0,0.0,명,N
9,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 기타,0.0,0.0,0.0,0.0,0.0,0.0,명,N
10,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임원 > 상임임원 합계,2.0,2.0,2.0,2.0,2.0,2.0,명,N
11,(사)남북교류협력지원협회,기타공공기관,임직원수 > 정규직 > 정원,24.0,24.0,24.0,24.0,24.0,24.0,명,N
12,(사)남북교류협력지원협회,기타공공기관,임직원수 > 정규직 > 현원 > 계,22.0,24.0,30.0,30.0,26.5,28.0,명,N
13,(사)남북교류협력지원협회,기타공공기관,임직원수 > 정규직 > 현원 > 전일제,22.0,24.0,30.0,30.0,26.0,28.0,명,N
14,(사)남북교류협력지원협회,기타공공기관,임직원수 > 정규직 > 현원 > 단시간,0.0,0.0,0.0,0.0,0.5,0.0,명,N
15,(사)남북교류협력지원협회,기타공공기관,임직원수 > 무기계약직 > 정원,0.0,0.0,0.0,0.0,3.0,3.0,명,N
16,(사)남북교류협력지원협회,기타공공기관,임직원수 > 무기계약직 > 현원 > 계,0.0,0.0,0.0,0.0,0.0,3.0,명,N
17,(사)남북교류협력지원협회,기타공공기관,임직원수 > 무기계약직 > 현원 > 전일제,0.0,0.0,0.0,0.0,0.0,3.0,명,N
18,(사)남북교류협력지원협회,기타공공기관,임직원수 > 무기계약직 > 현원 > 단시간,0.0,0.0,0.0,0.0,0.0,0.0,명,N
19,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 기간제 > 전일제,0.0,0.0,0.0,0.0,3.0,1.0,명,N
20,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 기간제 > 단시간,0.0,0.0,0.0,0.0,0.0,0.0,명,N
21,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 기타,0.0,0.0,0.0,0.0,0.0,0.0,명,N
22,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 비정규직 계,0.0,0.0,0.0,0.0,3.0,1.0,명,N
23,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 비정규직전환 > 전환계획,0.0,0.0,0.0,0.0,3.0,0.0,명,N
24,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 비정규직전환 > 전환실적,0.0,0.0,0.0,0.0,0.0,3.0,명,N
25,(사)남북교류협력지원협회,기타공공기관,임직원수 > 비정규직 > 비정규직전환 > 전환비율,0.0,0.0,0.0,0.0,0.0,0.0,명,N
26,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 파견,0.0,0.0,0.0,0.0,0.0,0.0,명,N
27,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 용역,0.0,0.0,0.0,0.0,0.0,0.0,명,N
28,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 사내하도급,0.0,0.0,0.0,0.0,0.0,0.0,명,N
29,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 소속외인력 계,0.0,0.0,0.0,0.0,0.0,0.0,명,N
30,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 정규직전환 > 전환계획,0.0,0.0,0.0,0.0,0.0,0.0,명,N
31,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 정규직전환 > 전환실적,0.0,0.0,0.0,0.0,0.0,0.0,명,N
32,(사)남북교류협력지원협회,기타공공기관,임직원수 > 소속외인력 > 정규직전환 > 전환비율,0.0,0.0,0.0,0.0,0.0,0.0,명,N
33,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임직원 총계,26.0,26.0,26.0,26.0,29.0,29.0,명,N
34,(사)남북교류협력지원협회,기타공공기관,임직원수 > 여성 현원,4.0,4.0,9.0,8.0,7.5,11.0,명,N
35,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임금피크제 별도 정원 > 정규직,0.0,0.0,0.0,0.0,0.0,1.0,명,N
36,(사)남북교류협력지원협회,기타공공기관,임직원수 > 임금피크제 별도 정원 > 무기계약직,0.0,0.0,0.0,0.0,0.0,0.0,명,N
37,(사)남북교류협력지원협회,기타공공기관,임직원수 > 탄력정원 > 정규직,0.0,0.0,0.0,0.0,0.0,0.0,명,N
38,(사)남북교류협력지원협회,기타공공기관,임직원수 > 탄력정원 > 무기계약직,0.0,0.0,0.0,0.0,0.0,0.0,명,N
39,(재)APEC기후센터,기타공공기관,임직원수 > 임원 > 기관장 > 상임 정원,1.0,1.0,1.0,1.0,1.0,1.0,명,N