# Import

In [2]:
import os
import re
import sys
from collections import defaultdict

import pandas as pd

# Declare Path

In [3]:
root_dir = '/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/University/'
dirs = [x for x in os.listdir(root_dir) if x != '.DS_Store']
files = {}

# for d in dirs:
d = 'e1_foreign'
dir_path = os.path.join(root_dir, d)
files[d] = [os.path.join(root_dir, d, x) for x in os.listdir(dir_path) if x != '.DS_Store' and x.endswith('.tsv')]

files

{'e1_foreign': ['/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/University/e1_foreign/2018_foreign.tsv',
  '/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/University/e1_foreign/2017_foreign.tsv',
  '/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/University/e1_foreign/2016_foreign.tsv']}

# Load Files

In [4]:
pd.set_option('display.max_row', 50)
df = defaultdict(dict)
for dir_name, file_list in files.items():
    key = dir_name.split('_')[-1]
    for file in file_list:
        file_name = re.search(r'(\d{4})', file.split('/')[-1]).group(1)
        df[file_name] = pd.read_csv(file, sep='\t')

df

defaultdict(dict,
            {'2018':        연도       학교종류 설립구분  지역  상태                학교 계 (D=A+B+C) 학위과정-소계(A)  \
             0    2018        대학교   사립  경남  기존     가야대학교(김해) _본교          54         46
             1    2018        대학교   사립  경기  기존         가천대학교 _본교         919        593
             2    2018        대학교   사립  강원  기존      가톨릭관동대학교 _본교         253         74
             3    2018        대학교   사립  경기  기존        가톨릭대학교 _본교         353        225
             4    2018        대학교   사립  서울  기존     가톨릭대학교 _제2캠퍼스           1          1
             5    2018        대학교   사립  서울  기존     가톨릭대학교 _제3캠퍼스          15         15
             6    2018        대학교   사립  서울  기존      감리교신학대학교 _본교           2          2
             7    2018        대학교   사립  경기  기존         강남대학교 _본교         451        135
             8    2018        대학교   국립  강원  기존       강릉원주대학교 _본교         188         97
             9    2018        대학교   국립  강원  기존         강원대학교 _본교         685        215
             10   2018        대학교   국립  강원  기존      강원대학교 _제2캠퍼스          93         34
             11   2018        대학교   사립  서울  기존         건국대학교 _본교       1,846      1,272
             12   2018        대학교   사립  충북  기존    건국대학교(글로컬) _분교       1,032        424
             13   2018        대학교   사립  충남  기존         건양대학교 _본교         221         82
             14   2018        대학교   사립  대전  기존      건양대학교 _제2캠퍼스          53         53
             15   2018  사이버대학(대학)   사립  대전  기존      건양사이버대학교 _본교          14         14
             16   2018        대학교   사립  경기  기존         경기대학교 _본교         670        359
             17   2018        대학교   사립  서울  기존      경기대학교 _제2캠퍼스         314        279
             18   2018        대학교   국립  경남  기존     경남과학기술대학교 _본교           2          2
             19   2018        대학교   사립  경남  기존         경남대학교 _본교         211        126
             20   2018        대학교   사립  강원  기존         경동대학교 _본교         422        398
             21   2018        대학교   사립  경기  기존      경동대학교 _제4캠퍼스          27         27
             22   2018        대학교   국립  대구  기존         경북대학교 _본교       1,062        590
             23   2018        대학교   국립  경남  기존         경상대학교 _본교         615        150
             24   2018        대학교   사립  부산  기존         경성대학교 _본교       1,450        594
             ..    ...        ...  ...  ..  ..               ...         ...        ...
             210  2018        대학교   국립  서울  기존       한국체육대학교 _본교           9          7
             211  2018        대학교   사립  경기  기존       한국항공대학교 _본교         125         52
             212  2018        대학교   국립  부산  기존       한국해양대학교 _본교         112         51
             213  2018        대학교   사립  대전  기존         한남대학교 _본교         497        259
             214  2018        대학교   사립  경북  기존         한동대학교 _본교         127         72
             215  2018        대학교   사립  강원  기존         한라대학교 _본교          22          0
             216  2018        대학교   사립  강원  기존         한림대학교 _본교         861        233
             217  2018        대학교   국립  대전  기존         한밭대학교 _본교         146        106
             218  2018       산업대학   국립  대전  폐교    한밭대학교(산업대) _본교           0          0
             219  2018        대학교   사립  경기  폐교         한북대학교 _본교           1          1
             220  2018        대학교   사립  충남  기존         한서대학교 _본교         504        269
             221  2018        대학교   사립  서울  기존         한성대학교 _본교         219         76
             222  2018        대학교   사립  경기  기존         한세대학교 _본교          64         40
             223  2018        대학교   사립  경기  기존         한신대학교 _본교         137         51
             224  2018        대학교   사립  서울  기존         한양대학교 _본교       2,464      1,608
             225  2018        대학교   사립  경기  기존  한양대학교(ERICA) _분교         416        249
             226  2018  사이버대학(대학)   사립  서울  기존      한양사이버대학교 _본교          50         50
             227  2018        대학교   사립  전북  기존       한일장신대학교 _본교           1          1
             228  2018        대학교   사립  경기  기존         협성대학교 _본교         262        140
             229  2018        대학교   사립  광주  기존         호남대학교 _본교         982        514
             230  2018        대학교   사립  광주  기존       호남신학대학교 _본교           2          2
             231  2018        대학교   사립  충남  기존         호서대학교 _본교         542        329
             232  2018       산업대학   사립  전북  기존         호원대학교 _본교         109         41
             233  2018        대학교   사립  서울  기존         홍익대학교 _본교       1,154        638
             234  2018        대학교   사립  세종  기존      홍익대학교 _제2캠퍼스          53         53

                 학위과정-인문사회계열  학위과정-자연과학계열   ...    연수과정-교환학생  연수과정-방문학생  연수과정-기타 연수생  \
             0            37            9   ...            0          0            0
             1           470           20   ...            0          0            0
             2            48            3   ...           13          0            0
             3           166           38   ...           56          0            0
             4             0            0   ...            0          0            0
             5            15            0   ...            0          0            0
             6             2            0   ...            0          0            0
             7           123            0   ...           19          0           11
             8            73           18   ...           33          0            0
             9           147           12   ...          168          0            8
             10           14            2   ...           11          0            0
             11          978           19   ...          109         16            0
             12          278           11   ...           39          0            0
             13           72            4   ...            9          0           27
             14            0            5   ...            0          0            0
             15           12            0   ...            0          0            0
             16          314            7   ...           59          0            0
             17          252            0   ...            0          0            0
             18            0            1   ...            0          0            0
             19          116            3   ...           34          0            0
             20          378            0   ...            0          0            0
             21            0            0   ...            0          0            0
             22          301          126   ...          170          4            0
             23          115            5   ...           30          0            0
             24          459            7   ...           46          1            0
             ..          ...          ...   ...          ...        ...          ...
             210           0            0   ...            2          0            0
             211           5           31   ...            3          4            0
             212           8            1   ...           18          0            0
             213         199            5   ...           68          0            0
             214          56            1   ...           48          1            0
             215           0            0   ...           22          0            0
             216         219            7   ...           82          0            0
             217          70            0   ...           12          0            0
             218           0            0   ...            0          0            0
             219           1            0   ...            0          0            0
             220          66           12   ...           24          0            0
             221          46            0   ...           15          0            1
             222          23            0   ...           12          0            0
             223          50            0   ...           17          0            0
             224         947           64   ...          336         48            0
             225          87            4   ...           87          5            0
             226          36            0   ...            0          0            0
             227           1            0   ...            0          0            0
             228         118            4   ...            0          0            0
             229         307            9   ...           75          0            0
             230           2            0   ...            0          0            0
             231         177           27   ...           25          0            0
             232          23            0   ...           20          0            0
             233          50            0   ...           52          2            0
             234           1            0   ...            0          0            0

                  언어능력-계(E) 언어능력-TOPIK4급 (예체능3급)이상 학생수 언어능력-영어트랙 TOEFL530 수준이상 학생수  \
             0           10                         10                           0
             1          235                        213                          22
             2           38                         38                           0
             3           41                         41                           0
             4            0                          0                           0
             5            8                          8                           0
             6            0                          0                           0
             7           19                         19                           0
             8           40                         40                           0
             9          115                        115                           0
             10           3                          3                           0
             11         789                        789                           0
             12         124                        124                           0
             13          33                         33                           0
             14          10                         10                           0
             15           0                          0                           0
             16          85                         59                          26
             17          84                         84                           0
             18           0                          0                           0
             19          40                         40                           0
             20         175                          2                         173
             21          19                          0                          19
             22         239                        239                           0
             23          86                         86                           0
             24         294                         96                         198
             ..         ...                        ...                         ...
             210          7                          7                           0
             211         28                         28                           0
             212         10                         10                           0
             213         35                         33                           2
             214          0                          0                           0
             215          0                          0                           0
             216         67                         66                           1
             217         28                         28                           0
             218          0                          0                           0
             219          0                          0                           0
             220         42                         42                           0
             221         37                         37                           0
             222         14                         14                           0
             223         24                         24                           0
             224      1,200                      1,190                          10
             225         91                         91                           0
             226          0                          0                           0
             227          0                          0                           0
             228         20                         20                           0
             229        163                        163                           0
             230          1                          1                           0
             231        200                        200                           0
             232         14                         14                           0
             233        353                        353                           0
             234         19                         19                           0

                  언어능력충족 학생비율(%) (E/A)x100  기숙사-계(F)  기숙사-수용 기숙사-미수용
             0                       21.74        54       8      46
             1                       39.63       919     312     607
             2                       51.35       253     152     101
             3                       18.22       353     286      67
             4                        0.00         1       0       1
             5                       53.33        15       8       7
             6                        0.00         2       1       1
             7                       14.07       451     387      64
             8                       41.24       188     115      73
             9                       53.49       685     268     417
             10                       8.82        93      27      66
             11                      62.03      1846     519   1,327
             12                      29.25      1032     172     860
             13                      40.24       221      22     199
             14                      18.87        53       6      47
             15                       0.00         0       0       0
             16                      23.68       670     117     553
             17                      30.11       314       3     311
             18                       0.00         2       0       2
             19                      31.75       211     165      46
             20                      43.97       422     169     253
             21                      70.37        27      27       0
             22                      40.51      1062     313     749
             23                      57.33       615      99     516
             24                      49.49      1450     167   1,283
             ..                        ...       ...     ...     ...
             210                    100.00         9       2       7
             211                     53.85       125      21     104
             212                     19.61       112      70      42
             213                     13.51       497     302     195
             214                      0.00       127      98      29
             215                      0.00        22      22       0
             216                     28.76       861     221     640
             217                     26.42       146      46     100
             218                      0.00         0       0       0
             219                      0.00         1       0       1
             220                     15.61       504     276     228
             221                     48.68       219      92     127
             222                     35.00        64      42      22
             223                     47.06       137      57      80
             224                     74.63      2464     279   2,185
             225                     36.55       416     216     200
             226                      0.00         0       0       0
             227                      0.00         1       0       1
             228                     14.29       262      71     191
             229                     31.71       982     517     465
             230                     50.00         2       1       1
             231                     60.79       542     280     262
             232                     34.15       109      48      61
             233                     55.33      1154      72   1,082
             234                     35.85        53       4      49

             [235 rows x 26 columns],
             '2017':        연도       학교종류 설립구분  지역  상태                학교 계 (D=A+B+C) 학위과정-소계(A)  \
             0    2017        대학교   사립  경남  기존     가야대학교(김해) _본교          61         44
             1    2017        대학교   사립  경기  기존         가천대학교 _본교         736        493
             2    2017        대학교   사립  강원  기존      가톨릭관동대학교 _본교         124         46
             3    2017        대학교   사립  경기  기존        가톨릭대학교 _본교         288        154
             4    2017        대학교   사립  서울  기존     가톨릭대학교 _제2캠퍼스           1          1
             5    2017        대학교   사립  서울  기존     가톨릭대학교 _제3캠퍼스          19         19
             6    2017        대학교   사립  서울  기존      감리교신학대학교 _본교           2          2
             7    2017        대학교   사립  경기  기존         강남대학교 _본교         238        119
             8    2017        대학교   국립  강원  기존       강릉원주대학교 _본교         143         83
             9    2017        대학교   국립  강원  기존    강릉원주대학교 _제2캠퍼스           0          0
             10   2017        대학교   국립  강원  기존         강원대학교 _본교         656        157
             11   2017        대학교   국립  강원  기존      강원대학교 _제2캠퍼스         120         13
             12   2017        대학교   사립  서울  기존         건국대학교 _본교       1,889      1,162
             13   2017        대학교   사립  충북  기존    건국대학교(글로컬) _분교         738        329
             14   2017        대학교   사립  충남  기존         건양대학교 _본교         219         88
             15   2017        대학교   사립  대전  기존      건양대학교 _제2캠퍼스          50         50
             16   2017  사이버대학(대학)   사립  대전  기존      건양사이버대학교 _본교          10         10
             17   2017        대학교   사립  경기  기존         경기대학교 _본교         641        355
             18   2017        대학교   사립  서울  기존      경기대학교 _제2캠퍼스         256        236
             19   2017        대학교   국립  경남  기존     경남과학기술대학교 _본교          10         10
             20   2017        대학교   사립  경남  기존         경남대학교 _본교         151         88
             21   2017        대학교   사립  강원  기존         경동대학교 _본교         343        301
             22   2017        대학교   국립  대구  기존         경북대학교 _본교         964        560
             23   2017        대학교   국립  경남  기존         경상대학교 _본교         391        129
             24   2017        대학교   사립  부산  기존         경성대학교 _본교         546        320
             ..    ...        ...  ...  ..  ..               ...         ...        ...
             208  2017        대학교   국립  서울  기존       한국체육대학교 _본교           7          4
             209  2017        대학교   사립  경기  기존       한국항공대학교 _본교          78         49
             210  2017        대학교   국립  부산  기존       한국해양대학교 _본교          66         50
             211  2017        대학교   사립  대전  기존         한남대학교 _본교         447        198
             212  2017        대학교   사립  경북  기존         한동대학교 _본교         123         65
             213  2017        대학교   사립  강원  기존         한라대학교 _본교          11          0
             214  2017        대학교   사립  강원  기존         한림대학교 _본교         318        162

# Functions

In [5]:
def convert_str2int(d, idx_numeric):
    d.iloc[::,idx_numeric:] = d.iloc[::,idx_numeric:].applymap(lambda x: pd.to_numeric(x.replace(',', '') if type(x)!=int and type(x)!=float else x))

# Index and Columns

In [6]:
df['2016'].columns

Index(['연도', '학교종류', '설립구분', '지역', '상태', '학교', '계 (D=A+B+C)', '학위과정-소계(A)',
       '학위과정-인문사회계열', '학위과정-자연과학계열', '학위과정-공학계열', '학위과정-예체능계열', '학위과정-의학계열',
       '교육과정 공동운영생(B)', '연수과정-소계(C)', '연수과정-어학연수생', '연수과정-교환학생', '연수과정-방문학생',
       '연수과정-기타 연수생', '언어능력-계(E)', '언어능력-TOPIK4급 (예체능3급)이상 학생수',
       '언어능력-영어트랙 TOEFL530 수준이상 학생수', '언어능력충족 학생비율(%) (E/A)x100', '기숙사-계(F)',
       '기숙사-수용', '기숙사-미수용'],
      dtype='object')

In [7]:
df['2017'].columns

Index(['연도', '학교종류', '설립구분', '지역', '상태', '학교', '계 (D=A+B+C)', '학위과정-소계(A)',
       '학위과정-인문사회계열', '학위과정-자연과학계열', '학위과정-공학계열', '학위과정-예체능계열', '학위과정-의학계열',
       '교육과정 공동운영생(B)', '연수과정-소계(C)', '연수과정-어학연수생', '연수과정-교환학생', '연수과정-방문학생',
       '연수과정-기타 연수생', '언어능력-계(E)', '언어능력-TOPIK4급 (예체능3급)이상 학생수',
       '언어능력-영어트랙 TOEFL530 수준이상 학생수', '언어능력충족 학생비율(%) (E/A)x100', '기숙사-계(F)',
       '기숙사-수용', '기숙사-미수용'],
      dtype='object')

In [8]:
df['2018'].columns

Index(['연도', '학교종류', '설립구분', '지역', '상태', '학교', '계 (D=A+B+C)', '학위과정-소계(A)',
       '학위과정-인문사회계열', '학위과정-자연과학계열', '학위과정-공학계열', '학위과정-예체능계열', '학위과정-의학계열',
       '교육과정 공동운영생(B)', '연수과정-소계(C)', '연수과정-어학연수생', '연수과정-교환학생', '연수과정-방문학생',
       '연수과정-기타 연수생', '언어능력-계(E)', '언어능력-TOPIK4급 (예체능3급)이상 학생수',
       '언어능력-영어트랙 TOEFL530 수준이상 학생수', '언어능력충족 학생비율(%) (E/A)x100', '기숙사-계(F)',
       '기숙사-수용', '기숙사-미수용'],
      dtype='object')

In [9]:
# 13 univ
univ_names = ['서울', '연세', '고려', '서강', '성균관', '한양', '중앙', '경희', '한국외국어', '서울시립', '건국', '동국', '홍익']
univ = [u + '대학교 _본교' for u in univ_names]

idx_2016 = df['2016']['학교'].isin(univ)
idx_2017 = df['2017']['학교'].isin(univ)
idx_2018 = df['2018']['학교'].isin(univ)

cols = ['학교', '계 (D=A+B+C)', '학위과정-소계(A)',
       '학위과정-인문사회계열', '학위과정-자연과학계열', '학위과정-공학계열', '학위과정-예체능계열', '학위과정-의학계열',
       '교육과정 공동운영생(B)', '연수과정-소계(C)', '연수과정-어학연수생', '연수과정-교환학생', '연수과정-방문학생',
       '연수과정-기타 연수생', '언어능력-계(E)', '언어능력-TOPIK4급 (예체능3급)이상 학생수',
       '언어능력-영어트랙 TOEFL530 수준이상 학생수', '언어능력충족 학생비율(%) (E/A)x100', '기숙사-계(F)',
       '기숙사-수용', '기숙사-미수용']

cols_numeric = [
    '입학금 (A)', '수업료 (B)',
       '등록금 (D=B)', '인문사회', '자연과학', '예체능', '공학', '의학'
]

# Pre-process

In [10]:
# df['2016_submission'][cols_sub] = df['2016_submission'][cols_sub].applymap(lambda x: pd.to_numeric(x.replace(',', '') if type(x)!=int else x))
convert_str2int(df['2016'], 6)
convert_str2int(df['2017'], 6)
convert_str2int(df['2018'], 6)

# Export TSV

In [15]:
name0 = 'e1-9-10_foreign.tsv'
file0 = os.path.join(root_dir, name0)
df['2018'].loc[idx_2018, cols].sort_values('계 (D=A+B+C)', ascending=False).to_csv(file0, sep='\t', index=False)

# -------------------------------------------------------------------

In [14]:
df['2018'].loc[idx_2018, cols].sort_values('계 (D=A+B+C)', ascending=False)

,학교,계 (D=A+B+C),학위과정-소계(A),학위과정-인문사회계열,학위과정-자연과학계열,학위과정-공학계열,학위과정-예체능계열,학위과정-의학계열,교육과정 공동운영생(B),연수과정-소계(C),연수과정-어학연수생,연수과정-교환학생,연수과정-방문학생,연수과정-기타 연수생,언어능력-계(E),언어능력-TOPIK4급 (예체능3급)이상 학생수,언어능력-영어트랙 TOEFL530 수준이상 학생수,언어능력충족 학생비율(%) (E/A)x100,기숙사-계(F),기숙사-수용,기숙사-미수용
32,고려대학교 _본교,4850,2327,1862,99,338,22,6,0,2523,1983,445,95,0,1278,1278,0,54.92,4850,419,4431
29,경희대학교 _본교,4626,2770,2237,71,56,404,2,0,1856,1446,410,0,0,1494,1416,78,53.94,4626,969,3657
119,성균관대학교 _본교,3853,2742,2166,45,342,187,2,0,1111,828,280,3,0,2139,2134,5,78.01,3853,0,3853
141,연세대학교 _본교,3140,1177,872,128,160,7,10,2,1961,1379,417,143,22,449,449,0,38.15,3140,1007,2133
176,중앙대학교 _본교,2519,1492,1364,16,74,32,6,0,1027,692,334,1,0,1138,1134,4,76.27,2519,469,2050
224,한양대학교 _본교,2464,1608,947,64,390,204,3,0,856,472,336,48,0,1200,1190,10,74.63,2464,279,2185
71,동국대학교 _본교,2454,1208,952,19,63,174,0,11,1235,1088,147,0,0,939,939,0,77.73,2454,113,2341
208,한국외국어대학교 _본교,2187,1270,1253,5,12,0,0,0,917,571,313,29,4,416,416,0,32.76,2186,422,1764
102,서강대학교 _본교,2087,752,712,13,27,0,0,0,1335,815,313,207,0,375,375,0,49.87,2087,193,1894
11,건국대학교 _본교,1846,1272,978,19,109,165,1,0,574,449,109,16,0,789,789,0,62.03,1846,519,1327
107,서울대학교 _본교,1410,197,61,23,81,20,12,0,1213,678,528,7,0,36,36,0,18.27,1410,204,1206
233,홍익대학교 _본교,1154,638,50,0,51,537,0,0,516,462,52,2,0,353,353,0,55.33,1154,72,1082
110,서울시립대학교 _본교,434,169,119,6,37,7,0,0,265,129,136,0,0,117,117,0,69.23,434,153,281

In [12]:
pd.set_option('display.max_column', None)
df['2018'].loc[~idx_2018, cols].sort_values('계 (D=A+B+C)', ascending=False)

,학교,계 (D=A+B+C),학위과정-소계(A),학위과정-인문사회계열,학위과정-자연과학계열,학위과정-공학계열,학위과정-예체능계열,학위과정-의학계열,교육과정 공동운영생(B),연수과정-소계(C),연수과정-어학연수생,연수과정-교환학생,연수과정-방문학생,연수과정-기타 연수생,언어능력-계(E),언어능력-TOPIK4급 (예체능3급)이상 학생수,언어능력-영어트랙 TOEFL530 수준이상 학생수,언어능력충족 학생비율(%) (E/A)x100,기숙사-계(F),기숙사-수용,기숙사-미수용
45,국민대학교 _본교,2436,1765,1305,74,226,160,0,22,649,420,210,0,19,646,633,13,36.60,2436,372,2064
161,이화여자대학교 _본교,1782,969,674,72,28,195,0,0,813,489,284,40,0,735,696,39,75.85,1782,549,1233
99,상명대학교 _본교,1739,1067,826,181,6,54,0,0,672,569,64,0,39,99,99,0,9.28,1739,164,1575
152,우송대학교 _본교,1668,1137,886,3,56,192,0,308,223,36,186,1,0,484,64,420,42.57,1668,826,842
24,경성대학교 _본교,1450,594,459,7,77,51,0,0,856,809,46,1,0,294,96,198,49.49,1450,167,1283
116,선문대학교 _본교,1389,836,623,43,117,53,0,0,553,535,18,0,0,611,611,0,73.09,1389,877,512
166,인하대학교 _본교,1374,801,565,31,198,7,0,0,573,395,178,0,0,457,368,89,57.05,1374,179,1195
122,세종대학교 _본교,1367,813,575,1,118,119,0,69,485,331,154,0,0,665,290,375,81.80,1367,337,1030
132,숭실대학교 _본교,1324,976,880,0,85,11,0,0,348,215,133,0,0,248,248,0,25.41,1324,464,860
31,계명대학교 _본교,1187,723,512,23,82,106,0,1,463,292,170,1,0,166,153,13,22.96,1187,492,695
90,부경대학교 _본교,1147,630,480,29,96,25,0,0,517,393,124,0,0,320,320,0,50.79,1147,486,661
170,전북대학교 _본교,1133,428,314,36,60,17,1,35,670,421,248,1,0,234,218,16,54.67,1133,393,740
190,충남대학교 _본교,1091,535,391,86,56,0,2,0,556,508,48,0,0,240,224,16,44.86,1091,214,877
168,전남대학교 _본교,1071,730,554,67,92,17,0,2,339,272,67,0,0,18,18,0,2.47,1071,482,589
93,부산대학교 _본교,1070,661,290,129,193,49,0,4,405,249,151,5,0,482,421,61,72.92,1070,296,774
22,경북대학교 _본교,1062,590,301,126,152,9,2,0,472,298,170,4,0,239,239,0,40.51,1062,313,749
12,건국대학교(글로컬) _분교,1032,424,278,11,8,127,0,0,608,569,39,0,0,124,124,0,29.25,1032,172,860
75,동서대학교 _본교,1029,164,88,0,67,9,0,558,307,203,104,0,0,122,31,91,74.39,1029,977,52
171,전주대학교 _본교,991,463,285,28,67,83,0,0,528,393,135,0,0,185,185,0,39.96,991,469,522
229,호남대학교 _본교,982,514,307,9,34,164,0,0,468,393,75,0,0,163,163,0,31.71,982,517,465
191,충북대학교 _본교,959,639,480,76,71,11,1,0,320,259,61,0,0,256,256,0,40.06,959,376,583
95,부산외국어대학교 _본교,949,420,413,0,1,6,0,0,529,206,323,0,0,170,164,6,40.48,949,601,348
1,가천대학교 _본교,919,593,470,20,74,27,2,0,326,326,0,0,0,235,213,22,39.63,919,312,607
58,단국대학교 _본교,892,559,313,0,51,195,0,39,294,155,139,0,0,183,167,16,32.74,892,704,188
62,대구대학교 _본교,882,233,147,20,38,28,0,0,649,588,61,0,0,112,112,0,48.07,882,359,523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,호남신학대학교 _본교,2,2,2,0,0,0,0,0,0,0,0,0,0,1,1,0,50.00,2,1,1
26,경인교육대학교 _본교,2,0,0,0,0,0,0,0,2,0,2,0,0,0,0,0,0.00,2,2,0
194,케이씨대학교 _본교,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,2,0,2
147,영산선학대학교 _본교,2,2,2,0,0,0,0,0,0,0,0,0,0,1,1,0,50.00,2,2,0
178,중앙승가대학교 _본교,2,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,2,2,0
227,한일장신대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,0,1
113,서울장신대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,1,0
4,가톨릭대학교 _제2캠퍼스,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.00,1,0,1
219,한북대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,0,1
81,루터대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,100.00,1,0,1
36,공주교육대학교 _본교,1,1,0,0,0,1,0,0,0,0,0,0,0,1,1,0,100.00,1,0,1
41,광주과학기술원 _본교,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,1,0
189,춘천교육대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,1,0
92,부산교육대학교 _본교,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0.00,1,1,0
87,목포해양대학교 _본교,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,100.00,1,1,0
163,인제대학교 _제2캠퍼스,1,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,100.00,1,0,1
85,목포가톨릭대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,1,0
188,추계예술대학교 _본교,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0.00,1,0,1
68,대전신학대학교 _본교,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,1,1,0
42,광주교육대학교 _본교,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0.00,1,1,0
218,한밭대학교(산업대) _본교,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0
105,서울과학기술대학교(산업대) _본교,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0
186,초당대학교(산업대) _본교,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0
53,꽃동네대학교 _본교,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0
57,남서울대학교(산업대) _본교,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0