# Import

In [3]:
import os
import pandas as pd

# File Path

In [2]:
data_directory = '/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/KCGI/Data/'
file_name = '20181120_ESG_Grade.tsv'
file_path = os.path.join(data_directory, file_name); file_path

'/Users/jake/OneDrive - leverage innovative users/Documents/News_Item/KCGI/Data/20181120_ESG_Grade.tsv'

# Load Data

In [5]:
esg = pd.read_csv(file_path, sep='\t'); esg
esg.fillna('', inplace=True); esg

      NO          기업명    기업코드 ESG등급   지배구조   사회   환경  평가년도    비고
0    771       AJ네트웍스   95570   B이하      C  B이하  B이하  2018
1    770        AJ렌터카   68400   B이하      B  B이하   B+  2018
2    769        AK홀딩스    6840   B이하      C  B이하  B이하  2018
3    768          BGF   27410            B            2018
4    767      BNK금융지주  138930    B+  B+ 이하   B+  B이하  2018  금융회사
5    766          BYC    1460   B이하     B+  B이하  B이하  2018
6    765           CJ    1040     A      A   A+  B이하  2018
7    764       CJ CGV   79160    B+      A   B+  B이하  2018
8    763       CJ대한통운     120    B+     B+   B+    A  2018
9    762        CJ씨푸드   11150   B이하      B   B+  B이하  2018
10   761       CJ제일제당   97950     A     B+   A+    A  2018
11   760         CJ헬로   37560    B+      A   B+  B이하  2018
12   759        CS홀딩스     590   B이하      B  B이하  B이하  2018
13   758           DB   12030   B이하      B  B이하  B이하  2018
14   757       DB금융투자   16610   B이하  B+ 이하  B이하  B이하  2018  금융회사
15   756       DB생명보험      25        B+ 이하            2018  금융회사
16   755       DB손해보험    5830    B+  B+ 이하    A    A  2018  금융회사
17   754        DB하이텍     990    B+      B   B+   B+  2018
18   753      DGB금융지주  139130    B+  B+ 이하   B+    A  2018  금융회사
19   752      DGB생명보험      16            A            2018  금융회사
20   751        DRB동일    4840   B이하      C  B이하  B이하  2018
21   750          DSR  155660   B이하      C  B이하  B이하  2018
22   749        DSR제강   69730   B이하      C  B이하  B이하  2018
23   748           E1   17940   B이하      B   B+  B이하  2018
24   747          F&F    7700   B이하      C  B이하  B이하  2018
25   746          GKL  114090   B이하      B   B+  B이하  2018
26   745           GS   78930   B이하     B+  B이하  B이하  2018
27   744         GS건설    6360    B+     B+   B+    A  2018
28   743        GS글로벌    1250   B이하     B+  B이하  B이하  2018
29   742        GS리테일    7070   B이하     B+   B+  B이하  2018
..   ...          ...     ...   ...    ...  ...  ...   ...   ...
741   30        현대중공업    9540    B+     B+   B+    A  2018
742   29        현대차증권    1500   B이하  B+ 이하  B이하  B이하  2018  금융회사
743   28         현대카드      32            A            2018  금융회사
744   27   현대코퍼레이션홀딩스  227840   B이하      B  B이하  B이하  2018
745   26         현대해상    1450     A      A   A+    A  2018  금융회사
746   25        현대홈쇼핑   57050    B+      A   B+  B이하  2018
747   24        형지엘리트   93240   B이하      C  B이하  B이하  2018
748   23           혜인    3010   B이하      C  B이하  B이하  2018
749   22         호텔신라    8770     A      A    A   B+  2018
750   21         화성산업    2460   B이하     B+  B이하  B이하  2018
751   20       화승알앤에이   13520    B+      B   B+   B+  2018
752   19     화승엔터프라이즈  241590   B이하      B  B이하  B이하  2018
753   18      화승인더스트리    6060   B이하      D  B이하   B+  2018
754   17           화신   10690   B이하      C  B이하  B이하  2018
755   16        화인베스틸  133820   B이하      B  B이하   B+  2018
756   15         화천기계   10660   B이하      C  B이하  B이하  2018
757   14         화천기공     850   B이하      B  B이하  B이하  2018
758   13         환인제약   16580   B이하     B+  B이하  B이하  2018
759   12        황금에스티   32560   B이하      C  B이하  B이하  2018
760   11           효성    4800   B이하      C   B+   B+  2018
761   10       효성 ITX   94280   B이하      B   B+  B이하  2018
762    9           후성   93370   B이하      B  B이하   B+  2018
763    8        휠라코리아   81660   B이하      B  B이하  B이하  2018
764    7    휴니드테크놀러지스    5870   B이하      B  B이하  B이하  2018
765    6          휴비스   79980    B+     B+   B+   B+  2018
766    5          휴스틸    5010   B이하      B  B이하  B이하  2018
767    4          휴켐스   69260   B이하      B  B이하   B+  2018
768    3       흥국생명보험      18        B+ 이하            2018  금융회사
769    2         흥국화재     540   B이하  B+ 이하  B이하  B이하  2018  금융회사
770    1         흥아해운    3280   B이하      C  B이하  B이하  2018

[771 rows x 9 columns]

In [8]:
len(esg)

771

In [7]:
grp_esg = esg.groupby(['ESG등급']).agg({'기업명': 'count'}); grp_esg

       기업명
ESG등급
        44
A       41
A+      11
B+     101
B이하    574

In [10]:
grp_gov = esg.groupby(['지배구조']).agg({'기업명': 'count'}); grp_gov

       기업명
지배구조
A       42
A+       9
B      289
B+     126
B+ 이하   60
C      219
D       26

In [11]:
grp_gov['기업명'].sum()

771