In [1]:
import re
import pandas as pd

from db.mongo import MyMongo

In [2]:
with MyMongo() as db:
    cvs = db.get_df_from_table('cvs', 'cvs')

<--Mongo Connected.
Mongo Connection Closed.-->

In [3]:
tobacco_path = 'cvs_from_tobacco4.tsv'

cvs_tobacco = pd.read_csv(tobacco_path, sep='\t', dtype=object)

print(len(cvs_tobacco))
cvs_tobacco.head(1)

# cvs_tobacco = pd.read_csv(tobacco_path, sep='\t', dtype=object).drop_duplicates(['관리번호'])
# print(f'cvs_tobacco: {len(cvs_tobacco)}')  # before: 67602, after: 65541

81607

,번호,개방서비스명,개방서비스ID,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,도로명우편번호,사업장명,최종수정시점,데이터갱신구분,데이터갱신일자,업태구분명,좌표정보(X),좌표정보(Y),지정일자,민원종류명
0,7,담배소매업,11_43_02_P,3000000,2006300010105600037,20060921,NaN,1,영업/정상,0,...,NaN,세븐일레븐 종로허브점,20080221000000,I,2018-08-31 23:59:59.0,NaN,198658.943470079,452604.254902527,NaN,NaN

In [4]:
# cols = ['영업상태명', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자', '소재지전화', '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명',
#         '좌표정보(X)', '좌표정보(Y)', '위생업태명', '남성종사자수', '여성종사자수', '영업장주변구분명', '등급구분명', '급수시설구분명', '총종업원수', '본사종업원수',
#         '건물소유구분명', '보증액', '월세액', '다중이용업소여부', '시설총규모', '전통업소지정번호', '전통업소주된음식', '홈페이지']

cols = ['관리번호', '사업장명', '상세영업상태명', '좌표정보(X)', '좌표정보(Y)', '도로명전체주소', '지정일자', '폐업일자', '최종수정시점', '데이터갱신일자',
        '업태구분명', 'lat', 'lng']

cvs_tobacco.columns

Index(['번호', '개방서비스명', '개방서비스ID', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(X)', '좌표정보(Y)',
       '지정일자', '민원종류명'],
      dtype='object')

In [5]:
cvs_tobacco.loc[::, cols].head(1)

/home/jake/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

,관리번호,사업장명,상세영업상태명,좌표정보(X),좌표정보(Y),도로명전체주소,지정일자,폐업일자,최종수정시점,데이터갱신일자,업태구분명,lat,lng
0,2006300010105600037,세븐일레븐 종로허브점,정상영업,198658.943470079,452604.254902527,"서울특별시 종로구 삼일대로 461 (경운동,운현궁SK허브 101동 102호)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN

In [6]:
tmp = cvs_tobacco.groupby('관리번호').agg({'상세영업상태명': 'count'}); tmp
# tmp.loc[tmp['상세영업상태명'] > 1]

                     상세영업상태명
관리번호
0000314011405600012        1
0000314011405600018        1
0001322008305600018        1
0001322008305600046        1
0084312007505601486        1
1080549009305600952        1
1197396000005600099        1
1898322008305600125        1
1900301010005600100        1
1967311008805600283        1
1968311008805600272        1
1973399000005600050        1
1973463001005600005        1
1974319007205600002        1
1974399000005600086        1
1974417008305600005        1
1976319007205600009        1
1976409004405600004        1
1977311008805600345        1
1978315010005614936        1
1978451007905617013        1
1979419008405600726        1
1979543000805600313        1
1980308007505600505        1
1980382007905600004        1
1980390000005600260        1
1980399000005600361        1
1980465000005600073        1
1980465003705600107        1
1980488000805600001        1
...                      ...
2018652003605600002        1
2018652003605600004        1
2018652003705600001        1
2018652003705600002        1
2018652003805600001        1
2018652003805600004        1
2018652003905600001        1
2018652003905600002        1
2018652003905600004        1
2018652004005600001        1
2018652004005600004        1
2018652004105600001        1
2018652004105600002        1
2018652004105600003        1
2018652004205600001        1
2018652004205600002        1
2018652004205600004        1
2018652004205600005        1
2018652004205600008        1
2018652004305600001        1
2018652004305600003        1
2018652004305600004        1
2018652004305600005        1
2018652004305600006        1
2018652004305600007        1
2018652004405600002        1
2018652004405600004        1
2018652004405600005        1
2022396012805600001        1
2117423007805600001        1

[81607 rows x 1 columns]

In [7]:
print(len(cvs_tobacco.drop_duplicates(['관리번호'])))

81607

In [8]:
print(len(cvs))

69532

In [9]:
74177 - 65541

8636

In [10]:
idx_new = ~cvs_tobacco['관리번호'].isin(cvs['관리번호'])
print(len(cvs_tobacco.loc[idx_new]))
cvs_tobacco.loc[idx_new, cols+['상세영업상태코드']].head(10)

12075

/home/jake/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

,관리번호,사업장명,상세영업상태명,좌표정보(X),좌표정보(Y),도로명전체주소,지정일자,폐업일자,최종수정시점,데이터갱신일자,업태구분명,lat,lng,상세영업상태코드
3,1999300007605600176,훼미리마트 강북삼성병원점,정상영업,196992.717515189,451776.429193029,NaN,NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
6,2006300010105600023,바이더웨이 종로관철점,정상영업,198867.92195634102,451906.885476295,"서울특별시 종로구 삼일대로 390-1 (관철동,1층)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
9,2008300012905600092,훼미리마트 안국로터리,정상영업,199781.435500989,452662.246926229,서울특별시 종로구 창경궁로22길 14 (원남동),20081125,NaN,20081125145603,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
32,2004300007605600122,LG25종로교남점,정상영업,196757.343302966,451841.321793744,서울특별시 종로구 통일로 164-3 (교남동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
47,2005300007605600033,(주)바이더웨이 종로코아점,정상영업,198697.70671262802,451897.834324531,서울특별시 종로구 종로12길 15 (관철동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
49,1997300007605600107,(주)바이더웨이 종로묘동점,정상영업,199194.522294596,452126.693878744,"서울특별시 종로구 돈화문로 33 (묘동,종로 묘동점)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
76,2012300012905600018,훼미리마트 대학로2호점,정상영업,199969.459458553,453437.96517395205,서울특별시 종로구 대명길 21 (명륜4가),20120306,NaN,20120417172741,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
86,2001300007605600027,훼미리마트신문로점,정상영업,NaN,NaN,NaN,NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
119,2016300016905600014,위드미 동대문역점,정상영업,201070.34835946801,452184.871706596,서울특별시 종로구 종로52길 3 (창신동),20160216,NaN,20160316091027,2018-08-31 23:59:59.0,NaN,NaN,NaN,0
124,2001300007605600008,(주)바이더웨이 상명대점,정상영업,196167.24792167,455302.372602988,서울특별시 종로구 홍지문길 2 (홍지동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN,0

In [11]:
# cvs_names = [
#     '지에스', 'GS',
#     '씨유', 'CU',  # '훼미리마트', '훼밀리마트', '패밀리마트', 'familymart',
#     '세븐일레븐', '코리아세븐',  # '바이더웨이', 'buytheway',
#     '이마트24', 'emart24',
#     '미니스톱', 
#     '씨스페이스', '씨스페이시스',
#     '미니스탑',
# ]
cvs_names = [
    '지에스', 'GS', 'LG25', '엘지25',
    '씨유', 'CU', '훼미리마트', '훼밀리마트', '패밀리마트', 'familymart',
    '세븐일레븐', '코리아세븐', '바이더웨이', 'buytheway',
    '이마트24', 'emart24', '위드미',
    '미니스톱', '미니스탑', '대상유통',
    '씨스페이스', '씨스페이시스',
]

cvs_string = '|'.join(cvs_names)
print(cvs_string)

지에스|GS|LG25|엘지25|씨유|CU|훼미리마트|훼밀리마트|패밀리마트|familymart|세븐일레븐|코리아세븐|바이더웨이|buytheway|이마트24|emart24|위드미|미니스톱|미니스탑|대상유통|씨스페이스|씨스페이시스

In [12]:
idx_cvs = cvs_tobacco['사업장명'].str.contains(cvs_string, flags=re.IGNORECASE, regex=True)

print(len(cvs_tobacco.loc[idx_cvs&(cvs_tobacco['상세영업상태명']=='정상영업')]))
cvs_tobacco.loc[idx_cvs&(cvs_tobacco['상세영업상태명']=='정상영업'), cols]

41293

/home/jake/.local/lib/python3.6/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

,관리번호,사업장명,상세영업상태명,좌표정보(X),좌표정보(Y),도로명전체주소,지정일자,폐업일자,최종수정시점,데이터갱신일자,업태구분명,lat,lng
0,2006300010105600037,세븐일레븐 종로허브점,정상영업,198658.943470079,452604.254902527,"서울특별시 종로구 삼일대로 461 (경운동,운현궁SK허브 101동 102호)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
1,1999300007605600150,GS25동숭점,정상영업,200156.610752518,453486.14839667897,서울특별시 종로구 동숭길 140 (혜화동),19990628,NaN,20120404135825,2018-08-31 23:59:59.0,NaN,NaN,NaN
2,2007300010105600043,이마트24 광화문시대점,정상영업,197559.791065754,452388.315239125,"서울특별시 종로구 사직로8길 42, 102-2호 (내수동,광화문시대 상가1층)",20070625,NaN,20180622133108,2018-08-31 23:59:59.0,NaN,NaN,NaN
3,1999300007605600176,훼미리마트 강북삼성병원점,정상영업,196992.717515189,451776.429193029,NaN,NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
4,1999300007605600094,(주)코리아세븐 성대점,정상영업,199678.15057905,453590.88118161296,서울특별시 종로구 성균관로 21-2 (명륜2가),19990408,NaN,20161109093314,2018-08-31 23:59:59.0,NaN,NaN,NaN
5,2008300012905600061,(주)코리아세븐 종로르메이에르점,정상영업,198150.30037412103,452019.21264293103,"서울특별시 종로구 종로 19, 101호 (종로1가,르메이에르종로타운1)",20080623,NaN,20121025133023,2018-08-31 23:59:59.0,NaN,NaN,NaN
6,2006300010105600023,바이더웨이 종로관철점,정상영업,198867.92195634102,451906.885476295,"서울특별시 종로구 삼일대로 390-1 (관철동,1층)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
7,2007300012905600006,세븐일레븐 독립문역점,정상영업,196230.717211362,452476.18106458295,서울특별시 종로구 통일로 248 (무악동),20070807,NaN,20130502163622,2018-08-31 23:59:59.0,NaN,NaN,NaN
8,2008300012905600082,세븐일레븐 종로배화점,정상영업,197231.292851585,452764.45729597396,서울특별시 종로구 필운대로 12 (필운동),20081007,NaN,20081007145235,2018-08-31 23:59:59.0,NaN,NaN,NaN
9,2008300012905600092,훼미리마트 안국로터리,정상영업,199781.435500989,452662.246926229,서울특별시 종로구 창경궁로22길 14 (원남동),20081125,NaN,20081125145603,2018-08-31 23:59:59.0,NaN,NaN,NaN
10,2003300007605600130,세븐일레븐 종로향기점,정상영업,201843.179937827,452443.27937024704,서울특별시 종로구 난계로29길 28 (숭인동),20031216,NaN,20150731160736,2018-08-31 23:59:59.0,NaN,NaN,NaN
11,2007300012905600047,GS25 명륜아남점,정상영업,199944.16729832898,453791.442084652,"서울특별시 종로구 혜화로 9 (명륜1가,1층)",20071119,NaN,20071119102124,2018-08-31 23:59:59.0,NaN,NaN,NaN
12,2007300012905600048,GS25 혜화대명점,정상영업,200031.226482075,453557.400004758,서울특별시 종로구 창경궁로34길 15 (혜화동),20071120,NaN,20090430153802,2018-08-31 23:59:59.0,NaN,NaN,NaN
13,2007300012905600055,GS25 평창문화로점,정상영업,197865.966333333,456429.34466666705,"서울특별시 종로구 평창문화로 154, 안성빌딩 (평창동)",20071204,NaN,20180503150542,2018-08-31 23:59:59.0,NaN,NaN,NaN
14,2004300007605600095,세븐일레븐 종로숭인점,정상영업,201923.40606958,452887.220420862,서울특별시 종로구 숭인동길 70-13 (숭인동),20040830,NaN,20090831141431,2018-08-31 23:59:59.0,NaN,NaN,NaN
15,2010300012905600067,GS25 종로방통대점,정상영업,200309.35812063699,453044.212129777,서울특별시 종로구 이화장길 99 (동숭동),20100806,NaN,20100830164822,2018-08-31 23:59:59.0,NaN,NaN,NaN
16,2010300012905600072,세븐일레븐 종로구기점,정상영업,196260.9162031,456159.784427484,서울특별시 종로구 진흥로 449 (구기동),20100901,NaN,20100902093017,2018-08-31 23:59:59.0,NaN,NaN,NaN
17,2008300012905600071,GS25종로관훈점,정상영업,198500.44755914,452243.43365493603,"서울특별시 종로구 인사동5길 42 (관훈동,종로빌딩 1층)",20080812,NaN,20080812195838,2018-08-31 23:59:59.0,NaN,NaN,NaN
18,2004300007605600116,GS25 동묘역점,정상영업,201350.47337553801,452279.74426029995,서울특별시 종로구 종로 344 (숭인동),20041126,NaN,20091120113929,2018-08-31 23:59:59.0,NaN,NaN,NaN
19,2008300012905600022,씨유 종로5가역점,정상영업,199936.591919229,452096.36720458604,서울특별시 종로구 종로 201-1 (종로4가),20080320,NaN,20120727105320,2018-08-31 23:59:59.0,NaN,NaN,NaN
20,2008300012905600073,미니스톱 종로충신점,정상영업,200374.51843675802,452616.256307724,서울특별시 종로구 율곡로 235 (충신동),20080828,NaN,20080828093531,2018-08-31 23:59:59.0,NaN,NaN,NaN
21,2008300012905600029,GS25 종로안국점,정상영업,198685.005097689,452737.39991695795,서울특별시 종로구 율곡로 61 (재동),20080408,NaN,20080408170518,2018-08-31 23:59:59.0,NaN,NaN,NaN
22,2010300012905600034,씨유 종로성대점,정상영업,199667.34921991,453570.52997439104,서울특별시 종로구 성균관로5길 6 (명륜2가),20100503,NaN,20120730111835,2018-08-31 23:59:59.0,NaN,NaN,NaN
23,2005300007605600012,세븐일레븐공평점,정상영업,198485.509749042,452102.52450196,서울특별시 종로구 우정국로 24 (공평동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
24,2002300007605600033,씨유 종로제일점,정상영업,198979.900757892,452173.28417043,서울특별시 종로구 수표로 118-1 (낙원동),20020325,NaN,20170321100321,2018-08-31 23:59:59.0,NaN,NaN,NaN
25,2018300016905600075,지에스25종로영풍점,정상영업,198351.81873748198,451921.60302604,"서울특별시 종로구 청계천로 41, 영풍빌딩 제2동 지하 2층 302호 (서린동)",20181129,NaN,20181129111120,2018-12-01 02:20:16.0,NaN,NaN,NaN
26,2012300012905600086,씨유 성균관대 인문관점,정상영업,199231.345644103,454019.36089002,"서울특별시 종로구 성균관로 25-2, 2층 (명륜3가, 퇴계인문관)",20121004,NaN,20121005090436,2018-08-31 23:59:59.0,NaN,NaN,NaN
27,1999300007605600122,세븐일레븐탑골공원점,정상영업,199001.895945417,452078.522023565,"서울특별시 종로구 수표로 110 (낙원동,탑골공원)",NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
28,1999300007605600123,세븐일레븐 평창점,정상영업,196915.715098031,456069.982694811,서울특별시 종로구 평창11길 17 (평창동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
29,1999300007605600124,세븐일레븐 인사점,정상영업,198783.662701312,452122.430070163,서울특별시 종로구 인사동길 5 (인사동),NaN,NaN,20080221000000,2018-08-31 23:59:59.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81577,2016652002805600015,씨유 모슬포점,정상영업,130639.957881,-29810.5327017,제주특별자치도 서귀포시 대정읍 상모대서로 25,20161111,NaN,20161111174018,2018-08-31 23:59:59.0,NaN,NaN,NaN
81578,2016652002805600016,지에스25마라도포구점,정상영업,131538.450456,-41513.9053236,제주특별자치도 서귀포시 대정읍 마라로 41,20161202,NaN,20161202154020,2018-08-31 23:59:59.0,NaN,NaN,NaN
81579,2016652002905600001,세븐일레븐 서귀포 신흥점,정상영업,178339.198869,-21618.8352434,제주특별자치도 서귀포시 남원읍 일주동로 6611,20160112,NaN,20160119143007,2018-08-31 23:59:59.0,NaN,NaN,NaN
81580,2018652003005600009,씨유성산온평점,정상영업,190406.125687,-9873.20523107,제주특별자치도 서귀포시 성산읍 온평애향로 2,20180702,NaN,20180702161103,2018-08-31 23:59:59.0,NaN,NaN,NaN
81581,2014652004105600007,씨유서귀법환점,정상영업,154501.757285,-28626.6473208,제주특별자치도 서귀포시 이어도로 916 (법환동),20141230,NaN,20141230115731,2018-08-31 23:59:59.0,NaN,NaN,NaN
81582,2014652004205600003,GS25신서귀포점,정상영업,154003.939397,-26714.8993806,제주특별자치도 서귀포시 신서귀로97번길 45 (강정동),20141016,NaN,20141016183550,2018-08-31 23:59:59.0,NaN,NaN,NaN
81583,2017652003105600014,씨유 서귀감산리점,정상영업,139845.92745,-26104.9032193,제주특별자치도 서귀포시 안덕면 일주서로 1499,20170822,NaN,20170822133730,2018-08-31 23:59:59.0,NaN,NaN,NaN
81584,2017652003105600015,GS25제주신화월드점,정상영업,136356.94232200002,-20780.8074936,제주특별자치도 서귀포시 안덕면 신화역사로304번길 38,20171108,NaN,20171108170325,2018-08-31 23:59:59.0,NaN,NaN,NaN
81585,2017652003105600017,씨유제주신화아띠점,정상영업,135526.538759,-21664.9798126,제주특별자치도 서귀포시 안덕면 신화역사로188번길 151,20171208,NaN,20171208110100,2018-08-31 23:59:59.0,NaN,NaN,NaN
81586,2017652003905600003,지에스25 동홍그린점,정상영업,160431.408546,-26408.4396603,제주특별자치도 서귀포시 동홍동로32번길 12 (동홍동),20170321,NaN,20170406102118,2018-08-31 23:59:59.0,NaN,NaN,NaN
81587,2017652003905600004,지에스25 동홍중앙점,정상영업,160017.501079,-27170.1870411999,"제주특별자치도 서귀포시 태평로 509, 101호 (동홍동, 제이원타워)",20170517,NaN,20170517141701,2018-08-31 23:59:59.0,NaN,NaN,NaN
81588,2017652003905600005,씨유 서귀포현대점,정상영업,160290.474613,-26465.2039851,"제주특별자치도 서귀포시 동홍남로 59, 1층 (동홍동)",20170717,NaN,20170717101248,2018-08-31 23:59:59.0,NaN,NaN,NaN
81589,2017652003905600006,씨유 서귀남고사거리점,정상영업,159727.292143,-25450.1151662,"제주특별자치도 서귀포시 중산간동로 7936, 1층 (동홍동)",20170814,NaN,20170814152954,2018-08-31 23:59:59.0,NaN,NaN,NaN
81590,2014652003005600005,세븐일레븐서귀포라사니아리조트점,정상영업,188085.926685,-13659.3646429,제주특별자치도 서귀포시 성산읍 일주동로 5199,20140605,NaN,20170221163128,2018-08-31 23:59:59.0,NaN,NaN,NaN
81591,2014652003005600006,씨유봄그리고가을리조트점,정상영업,191645.43531300002,-2470.43651019,제주특별자치도 서귀포시 성산읍 해맞이해안로 2660,20140610,NaN,20160624130000,2018-08-31 23:59:59.0,NaN,NaN,NaN
81592,2013652003105600007,GS25안덕대평점,정상영업,140940.290889,-28863.2545605,제주특별자치도 서귀포시 안덕면 난드르로 11,20130719,NaN,20130719171202,2018-08-31 23:59:59.0,NaN,NaN,NaN
81593,2013652004205600003,씨유제주풍림리조트점,정상영업,152324.829585,-29032.2870427,제주특별자치도 서귀포시 이어도로 684 (강정동),20131107,NaN,20131107104109,2018-08-31 23:59:59.0,NaN,NaN,NaN
81594,2012652004305600004,씨유제주중문점,정상영업,146404.42052,-26981.3158301,제주특별자치도 서귀포시 중문상로 38 (중문동),20120620,NaN,20120724114937,2018-08-31 23:59:59.0,NaN,NaN,NaN
81595,2012652004405600001,(주)코리아세븐 제주롯데리조트점,정상영업,146106.311197,-21464.0288838,NaN,20120327,NaN,20121114100906,2018-08-31 23:59:59.0,NaN,NaN,NaN
81596,2015652004205600006,세븐일레븐 서귀포강정점,정상영업,153957.2822,-27145.5004676,"제주특별자치도 서귀포시 신서귀로97번길 87, 1층 101호 (강정동, 대림한숲빌라)",20151105,NaN,20180712161922,2018-08-31 23:59:59.0,NaN,NaN,NaN
81597,2016652003205600007,세븐일레븐 서귀포 토산로점,정상영업,179485.314276,-20907.7064996,제주특별자치도 서귀포시 표선면 일주동로 6470,20160829,NaN,20160829181045,2018-08-31 23:59:59.0,NaN,NaN,NaN
81598,2016652003305600001,씨유 서귀포자구리점,정상영업,159580.85963599998,-28060.9524148,제주특별자치도 서귀포시 솔동산로21번길 31 (서귀동),20160701,NaN,20160701103110,2018-08-31 23:59:59.0,NaN,NaN,NaN
81599,2016652003305600003,세븐일레븐 서귀포솔동산점,정상영업,159197.160195,-28201.8379394,"제주특별자치도 서귀포시 천지연로29번길 8 (서귀동, 뉴서울호텔)",20160913,NaN,20160913103242,2018-08-31 23:59:59.0,NaN,NaN,NaN
81600,2017652003805600003,씨유서귀포보목길점,정상영업,NaN,NaN,NaN,20170825,NaN,20170828100557,2018-08-31 23:59:59.0,NaN,NaN,NaN
81601,2015652004005600008,씨유서귀홍중로점,정상영업,158740.645497,-26671.3778983,제주특별자치도 서귀포시 홍중로27번길 1 (서홍동),20151218,NaN,20151218103300,2018-08-31 23:59:59.0,NaN,NaN,NaN
81602,2015652004005600010,씨유서귀서홍로점,정상영업,158644.20361300002,-25647.4817751,"제주특별자치도 서귀포시 중산간동로 8048-2, 1층 (서홍동)",20151224,NaN,20151224175803,2018-08-31 23:59:59.0,NaN,NaN,NaN
81603,2016652003605600001,(주)코리아세븐서귀포서문로점,정상영업,158741.88971400002,-27321.1504967,"제주특별자치도 서귀포시 서문로41번길 2 (서귀동, 우리들 코사마트)",20160215,NaN,20160215171100,2018-08-31 23:59:59.0,NaN,NaN,NaN
81604,2016652003605600003,씨유서귀외돌개점,정상영업,158423.732149,-27921.9995709,제주특별자치도 서귀포시 남성중로 131 (서귀동),20160726,NaN,20160728094718,2018-08-31 23:59:59.0,NaN,NaN,NaN
81605,2016652003605600004,GS25서귀중정점,정상영업,158770.925971,-27501.9725236,"제주특별자치도 서귀포시 중정로 17-1, 1층 (서귀동)",20161104,NaN,20180905162357,2018-08-31 23:59:59.0,NaN,NaN,NaN
81606,2017652003105600013,세븐일레븐 서귀포창천점,정상영업,141198.828124,-25740.006185,제주특별자치도 서귀포시 안덕면 일주서로 1357,20170801,NaN,20170801130037,2018-08-31 23:59:59.0,NaN,NaN,NaN

In [13]:
docs = cvs_tobacco.loc[idx_cvs].to_dict(orient='records')
with MyMongo() as db:
    db.update_one_bulk('cvs', 'cvs', docs, '관리번호')

<--Mongo Connected.
- bulk_write result:
match, insert, modify, upsert
69532 0 351 12075
Mongo Connection Closed.-->